// Turn-by-turn instruction wording, per language.
//
// Extracted from a nest of `lang == 'it' ? … : …` ternaries that supported
// exactly two languages: everyone else — twenty-five of the twenty-seven the
// app ships — was navigated in English. That is not a missing translation, it
// is a driver being given directions in a language they may not read.
//
// A table rather than code: adding a language is a data change, and a missing
// key falls back to English rather than crashing.
//
// `{label}` is a motorway exit number, `{n}` a roundabout exit ordinal.
library;

/// Phrase table keyed by language code, then by phrase key.
const Map<String, Map<String, String>> navPhrases = {
  'en': {
    'on': ' on ',
    'depart': 'Start',
    'arrive': 'You have arrived at your destination',
    'turnLeft': 'Turn left',
    'turnRight': 'Turn right',
    'keepLeft': 'Keep left',
    'keepRight': 'Keep right',
    'sharpLeft': 'Sharp left',
    'sharpRight': 'Sharp right',
    'uturn': 'Make a U-turn',
    'continueStraight': 'Continue straight',
    'continueOn': 'Continue',
    'merge': 'Merge onto',
    'rampLeft': 'Turn left onto the on-ramp',
    'rampRight': 'Turn right onto the on-ramp',
    'takeRamp': 'Take the on-ramp',
    'exitLabelled': 'Take exit {label}',
    'exitPlain': 'Take the exit',
    'forkLeft': 'At the fork keep left',
    'forkRight': 'At the fork keep right',
    'endLeft': 'At the end of the road turn left',
    'endRight': 'At the end of the road turn right',
    'roundabout': 'At the roundabout take exit {n}',
    'rotary': 'At the rotary take exit {n}',
  },
  'it': {
    'on': ' su ',
    'depart': 'Parti',
    'arrive': 'Sei arrivato a destinazione',
    'turnLeft': 'Svolta a sinistra',
    'turnRight': 'Svolta a destra',
    'keepLeft': 'Tieni la sinistra',
    'keepRight': 'Tieni la destra',
    'sharpLeft': 'Svolta netta a sinistra',
    'sharpRight': 'Svolta netta a destra',
    'uturn': 'Fai inversione di marcia',
    'continueStraight': 'Continua dritto',
    'continueOn': 'Continua',
    'merge': 'Immettiti',
    'rampLeft': 'Svolta a sinistra sulla rampa',
    'rampRight': 'Svolta a destra sulla rampa',
    'takeRamp': 'Prendi la rampa',
    'exitLabelled': 'Esci all\'uscita {label}',
    'exitPlain': 'Esci dalla rampa',
    'forkLeft': 'Al bivio tieni la sinistra',
    'forkRight': 'Al bivio tieni la destra',
    'endLeft': 'Alla fine della strada svolta a sinistra',
    'endRight': 'Alla fine della strada svolta a destra',
    'roundabout': 'Alla rotonda prendi la {n}° uscita',
    'rotary': 'Alla rotatoria prendi la {n}° uscita',
  },
  'de': {
    'on': ' auf ',
    'depart': 'Losfahren',
    'arrive': 'Sie haben Ihr Ziel erreicht',
    'turnLeft': 'Links abbiegen',
    'turnRight': 'Rechts abbiegen',
    'keepLeft': 'Links halten',
    'keepRight': 'Rechts halten',
    'sharpLeft': 'Scharf links abbiegen',
    'sharpRight': 'Scharf rechts abbiegen',
    'uturn': 'Wenden',
    'continueStraight': 'Geradeaus weiter',
    'continueOn': 'Weiter',
    'merge': 'Auffahren',
    'rampLeft': 'Links auf die Auffahrt',
    'rampRight': 'Rechts auf die Auffahrt',
    'takeRamp': 'Auffahrt nehmen',
    'exitLabelled': 'Ausfahrt {label} nehmen',
    'exitPlain': 'Ausfahrt nehmen',
    'forkLeft': 'An der Gabelung links halten',
    'forkRight': 'An der Gabelung rechts halten',
    'endLeft': 'Am Ende der Straße links abbiegen',
    'endRight': 'Am Ende der Straße rechts abbiegen',
    'roundabout': 'Im Kreisverkehr die {n}. Ausfahrt nehmen',
    'rotary': 'Im Kreisverkehr die {n}. Ausfahrt nehmen',
  },
  'fr': {
    'on': ' sur ',
    'depart': 'Démarrez',
    'arrive': 'Vous êtes arrivé à destination',
    'turnLeft': 'Tournez à gauche',
    'turnRight': 'Tournez à droite',
    'keepLeft': 'Serrez à gauche',
    'keepRight': 'Serrez à droite',
    'sharpLeft': 'Tournez franchement à gauche',
    'sharpRight': 'Tournez franchement à droite',
    'uturn': 'Faites demi-tour',
    'continueStraight': 'Continuez tout droit',
    'continueOn': 'Continuez',
    'merge': 'Insérez-vous',
    'rampLeft': 'Tournez à gauche sur la bretelle',
    'rampRight': 'Tournez à droite sur la bretelle',
    'takeRamp': 'Prenez la bretelle',
    'exitLabelled': 'Prenez la sortie {label}',
    'exitPlain': 'Prenez la sortie',
    'forkLeft': 'À la fourche serrez à gauche',
    'forkRight': 'À la fourche serrez à droite',
    'endLeft': 'Au bout de la route tournez à gauche',
    'endRight': 'Au bout de la route tournez à droite',
    'roundabout': 'Au rond-point prenez la {n}e sortie',
    'rotary': 'Au rond-point prenez la {n}e sortie',
  },
  'es': {
    'on': ' en ',
    'depart': 'Comience',
    'arrive': 'Ha llegado a su destino',
    'turnLeft': 'Gire a la izquierda',
    'turnRight': 'Gire a la derecha',
    'keepLeft': 'Manténgase a la izquierda',
    'keepRight': 'Manténgase a la derecha',
    'sharpLeft': 'Gire bruscamente a la izquierda',
    'sharpRight': 'Gire bruscamente a la derecha',
    'uturn': 'Haga un cambio de sentido',
    'continueStraight': 'Siga recto',
    'continueOn': 'Continúe',
    'merge': 'Incorpórese',
    'rampLeft': 'Gire a la izquierda hacia la rampa',
    'rampRight': 'Gire a la derecha hacia la rampa',
    'takeRamp': 'Tome la rampa',
    'exitLabelled': 'Tome la salida {label}',
    'exitPlain': 'Tome la salida',
    'forkLeft': 'En la bifurcación manténgase a la izquierda',
    'forkRight': 'En la bifurcación manténgase a la derecha',
    'endLeft': 'Al final de la calle gire a la izquierda',
    'endRight': 'Al final de la calle gire a la derecha',
    'roundabout': 'En la rotonda tome la salida {n}',
    'rotary': 'En la rotonda tome la salida {n}',
  },
  'pt': {
    'on': ' na ',
    'depart': 'Siga',
    'arrive': 'Chegou ao seu destino',
    'turnLeft': 'Vire à esquerda',
    'turnRight': 'Vire à direita',
    'keepLeft': 'Mantenha-se à esquerda',
    'keepRight': 'Mantenha-se à direita',
    'sharpLeft': 'Vire acentuadamente à esquerda',
    'sharpRight': 'Vire acentuadamente à direita',
    'uturn': 'Faça inversão de marcha',
    'continueStraight': 'Siga em frente',
    'continueOn': 'Continue',
    'merge': 'Entre',
    'rampLeft': 'Vire à esquerda para o ramal',
    'rampRight': 'Vire à direita para o ramal',
    'takeRamp': 'Entre no ramal',
    'exitLabelled': 'Saia na saída {label}',
    'exitPlain': 'Saia',
    'forkLeft': 'Na bifurcação mantenha-se à esquerda',
    'forkRight': 'Na bifurcação mantenha-se à direita',
    'endLeft': 'No fim da rua vire à esquerda',
    'endRight': 'No fim da rua vire à direita',
    'roundabout': 'Na rotunda saia na {n}ª saída',
    'rotary': 'Na rotunda saia na {n}ª saída',
  },
  'nl': {
    'on': ' op ',
    'depart': 'Vertrek',
    'arrive': 'U hebt uw bestemming bereikt',
    'turnLeft': 'Sla linksaf',
    'turnRight': 'Sla rechtsaf',
    'keepLeft': 'Houd links aan',
    'keepRight': 'Houd rechts aan',
    'sharpLeft': 'Scherp linksaf',
    'sharpRight': 'Scherp rechtsaf',
    'uturn': 'Keer om',
    'continueStraight': 'Ga rechtdoor',
    'continueOn': 'Ga verder',
    'merge': 'Voeg in',
    'rampLeft': 'Sla linksaf de oprit op',
    'rampRight': 'Sla rechtsaf de oprit op',
    'takeRamp': 'Neem de oprit',
    'exitLabelled': 'Neem afrit {label}',
    'exitPlain': 'Neem de afrit',
    'forkLeft': 'Houd bij de splitsing links aan',
    'forkRight': 'Houd bij de splitsing rechts aan',
    'endLeft': 'Sla aan het einde van de weg linksaf',
    'endRight': 'Sla aan het einde van de weg rechtsaf',
    'roundabout': 'Neem op de rotonde de {n}e afslag',
    'rotary': 'Neem op de rotonde de {n}e afslag',
  },
  'pl': {
    'on': ' na ',
    'depart': 'Rusz',
    'arrive': 'Dotarłeś do celu',
    'turnLeft': 'Skręć w lewo',
    'turnRight': 'Skręć w prawo',
    'keepLeft': 'Trzymaj się lewej',
    'keepRight': 'Trzymaj się prawej',
    'sharpLeft': 'Skręć ostro w lewo',
    'sharpRight': 'Skręć ostro w prawo',
    'uturn': 'Zawróć',
    'continueStraight': 'Jedź prosto',
    'continueOn': 'Kontynuuj',
    'merge': 'Włącz się',
    'rampLeft': 'Skręć w lewo na wjazd',
    'rampRight': 'Skręć w prawo na wjazd',
    'takeRamp': 'Wjedź na wjazd',
    'exitLabelled': 'Zjedź zjazdem {label}',
    'exitPlain': 'Zjedź',
    'forkLeft': 'Na rozwidleniu trzymaj się lewej',
    'forkRight': 'Na rozwidleniu trzymaj się prawej',
    'endLeft': 'Na końcu drogi skręć w lewo',
    'endRight': 'Na końcu drogi skręć w prawo',
    'roundabout': 'Na rondzie wybierz {n}. zjazd',
    'rotary': 'Na rondzie wybierz {n}. zjazd',
  },
  'ru': {
    'on': ' на ',
    'depart': 'Начните движение',
    'arrive': 'Вы прибыли в пункт назначения',
    'turnLeft': 'Поверните налево',
    'turnRight': 'Поверните направо',
    'keepLeft': 'Держитесь левее',
    'keepRight': 'Держитесь правее',
    'sharpLeft': 'Резко поверните налево',
    'sharpRight': 'Резко поверните направо',
    'uturn': 'Развернитесь',
    'continueStraight': 'Продолжайте прямо',
    'continueOn': 'Продолжайте',
    'merge': 'Перестройтесь',
    'rampLeft': 'Поверните налево на съезд',
    'rampRight': 'Поверните направо на съезд',
    'takeRamp': 'Съезжайте на съезд',
    'exitLabelled': 'Съезд {label}',
    'exitPlain': 'Съезжайте',
    'forkLeft': 'На развилке держитесь левее',
    'forkRight': 'На развилке держитесь правее',
    'endLeft': 'В конце дороги поверните налево',
    'endRight': 'В конце дороги поверните направо',
    'roundabout': 'На круге сверните на {n}-й съезд',
    'rotary': 'На круге сверните на {n}-й съезд',
  },
  'zh': {
    'on': '在',
    'depart': '出发',
    'arrive': '您已到达目的地',
    'turnLeft': '左转',
    'turnRight': '右转',
    'keepLeft': '靠左行驶',
    'keepRight': '靠右行驶',
    'sharpLeft': '急左转',
    'sharpRight': '急右转',
    'uturn': '调头',
    'continueStraight': '直行',
    'continueOn': '继续',
    'merge': '并线',
    'rampLeft': '左转进入匝道',
    'rampRight': '右转进入匝道',
    'takeRamp': '进入匝道',
    'exitLabelled': '从{label}出口驶出',
    'exitPlain': '驶出',
    'forkLeft': '在岔路口靠左',
    'forkRight': '在岔路口靠右',
    'endLeft': '在道路尽头左转',
    'endRight': '在道路尽头右转',
    'roundabout': '在环岛走第{n}个出口',
    'rotary': '在环岛走第{n}个出口',
  },
  'ja': {
    'on': 'を',
    'depart': '出発',
    'arrive': '目的地に到着しました',
    'turnLeft': '左折',
    'turnRight': '右折',
    'keepLeft': '左側を進む',
    'keepRight': '右側を進む',
    'sharpLeft': '鋭く左折',
    'sharpRight': '鋭く右折',
    'uturn': 'Uターン',
    'continueStraight': '直進',
    'continueOn': '続行',
    'merge': '合流',
    'rampLeft': '左折してランプへ',
    'rampRight': '右折してランプへ',
    'takeRamp': 'ランプに入る',
    'exitLabelled': '出口{label}へ',
    'exitPlain': '出口へ',
    'forkLeft': '分岐を左へ',
    'forkRight': '分岐を右へ',
    'endLeft': '突き当たりを左折',
    'endRight': '突き当たりを右折',
    'roundabout': 'ロータリーで{n}番目の出口',
    'rotary': 'ロータリーで{n}番目の出口',
  },
  'cs': {
    'on': ' na ',
    'depart': 'Vyrazte',
    'arrive': 'Dorazili jste do cíle',
    'turnLeft': 'Odbočte vlevo',
    'turnRight': 'Odbočte vpravo',
    'keepLeft': 'Držte se vlevo',
    'keepRight': 'Držte se vpravo',
    'sharpLeft': 'Ostře odbočte vlevo',
    'sharpRight': 'Ostře odbočte vpravo',
    'uturn': 'Otočte se',
    'continueStraight': 'Pokračujte rovně',
    'continueOn': 'Pokračujte',
    'merge': 'Zařaďte se',
    'rampLeft': 'Odbočte vlevo na nájezd',
    'rampRight': 'Odbočte vpravo na nájezd',
    'takeRamp': 'Najeďte na nájezd',
    'exitLabelled': 'Sjeďte výjezdem {label}',
    'exitPlain': 'Sjeďte',
    'forkLeft': 'Na rozcestí se držte vlevo',
    'forkRight': 'Na rozcestí se držte vpravo',
    'endLeft': 'Na konci silnice odbočte vlevo',
    'endRight': 'Na konci silnice odbočte vpravo',
    'roundabout': 'Na kruhovém objezdu {n}. výjezd',
    'rotary': 'Na kruhovém objezdu {n}. výjezd',
  },
  'sk': {
    'on': ' na ',
    'depart': 'Vyrazte',
    'arrive': 'Dorazili ste do cieľa',
    'turnLeft': 'Odbočte vľavo',
    'turnRight': 'Odbočte vpravo',
    'keepLeft': 'Držte sa vľavo',
    'keepRight': 'Držte sa vpravo',
    'sharpLeft': 'Ostro odbočte vľavo',
    'sharpRight': 'Ostro odbočte vpravo',
    'uturn': 'Otočte sa',
    'continueStraight': 'Pokračujte rovno',
    'continueOn': 'Pokračujte',
    'merge': 'Zaraďte sa',
    'rampLeft': 'Odbočte vľavo na nájazd',
    'rampRight': 'Odbočte vpravo na nájazd',
    'takeRamp': 'Choďte na nájazd',
    'exitLabelled': 'Zíďte výjazdom {label}',
    'exitPlain': 'Zíďte',
    'forkLeft': 'Na rázcestí sa držte vľavo',
    'forkRight': 'Na rázcestí sa držte vpravo',
    'endLeft': 'Na konci cesty odbočte vľavo',
    'endRight': 'Na konci cesty odbočte vpravo',
    'roundabout': 'Na kruhovom objazde {n}. výjazd',
    'rotary': 'Na kruhovom objazde {n}. výjazd',
  },
  'sv': {
    'on': ' på ',
    'depart': 'Starta',
    'arrive': 'Du har kommit fram',
    'turnLeft': 'Sväng vänster',
    'turnRight': 'Sväng höger',
    'keepLeft': 'Håll till vänster',
    'keepRight': 'Håll till höger',
    'sharpLeft': 'Skarp vänstersväng',
    'sharpRight': 'Skarp högersväng',
    'uturn': 'Gör en U-sväng',
    'continueStraight': 'Fortsätt rakt fram',
    'continueOn': 'Fortsätt',
    'merge': 'Kör in',
    'rampLeft': 'Sväng vänster till påfarten',
    'rampRight': 'Sväng höger till påfarten',
    'takeRamp': 'Ta påfarten',
    'exitLabelled': 'Ta avfart {label}',
    'exitPlain': 'Ta avfarten',
    'forkLeft': 'Håll vänster i gaffeln',
    'forkRight': 'Håll höger i gaffeln',
    'endLeft': 'Sväng vänster vid vägens slut',
    'endRight': 'Sväng höger vid vägens slut',
    'roundabout': 'Ta {n}:e avfarten i rondellen',
    'rotary': 'Ta {n}:e avfarten i rondellen',
  },
  'da': {
    'on': ' ad ',
    'depart': 'Start',
    'arrive': 'Du er ankommet til destinationen',
    'turnLeft': 'Drej til venstre',
    'turnRight': 'Drej til højre',
    'keepLeft': 'Hold til venstre',
    'keepRight': 'Hold til højre',
    'sharpLeft': 'Skarpt til venstre',
    'sharpRight': 'Skarpt til højre',
    'uturn': 'Foretag en U-vending',
    'continueStraight': 'Fortsæt ligeud',
    'continueOn': 'Fortsæt',
    'merge': 'Flet ind',
    'rampLeft': 'Drej til venstre ad tilkørslen',
    'rampRight': 'Drej til højre ad tilkørslen',
    'takeRamp': 'Tag tilkørslen',
    'exitLabelled': 'Tag afkørsel {label}',
    'exitPlain': 'Tag afkørslen',
    'forkLeft': 'Hold til venstre ved forgreningen',
    'forkRight': 'Hold til højre ved forgreningen',
    'endLeft': 'Drej til venstre for enden af vejen',
    'endRight': 'Drej til højre for enden af vejen',
    'roundabout': 'Tag den {n}. afkørsel i rundkørslen',
    'rotary': 'Tag den {n}. afkørsel i rundkørslen',
  },
  'fi': {
    'on': ' tielle ',
    'depart': 'Lähde',
    'arrive': 'Olet saapunut määränpäähän',
    'turnLeft': 'Käänny vasemmalle',
    'turnRight': 'Käänny oikealle',
    'keepLeft': 'Pysy vasemmalla',
    'keepRight': 'Pysy oikealla',
    'sharpLeft': 'Käänny jyrkästi vasemmalle',
    'sharpRight': 'Käänny jyrkästi oikealle',
    'uturn': 'Tee U-käännös',
    'continueStraight': 'Jatka suoraan',
    'continueOn': 'Jatka',
    'merge': 'Liity',
    'rampLeft': 'Käänny vasemmalle liittymärampille',
    'rampRight': 'Käänny oikealle liittymärampille',
    'takeRamp': 'Aja rampille',
    'exitLabelled': 'Poistu liittymästä {label}',
    'exitPlain': 'Poistu',
    'forkLeft': 'Pysy risteyksessä vasemmalla',
    'forkRight': 'Pysy risteyksessä oikealla',
    'endLeft': 'Käänny tien päässä vasemmalle',
    'endRight': 'Käänny tien päässä oikealle',
    'roundabout': 'Aja liikenneympyrästä {n}. ulos',
    'rotary': 'Aja liikenneympyrästä {n}. ulos',
  },
  'el': {
    'on': ' στην ',
    'depart': 'Ξεκινήστε',
    'arrive': 'Φτάσατε στον προορισμό σας',
    'turnLeft': 'Στρίψτε αριστερά',
    'turnRight': 'Στρίψτε δεξιά',
    'keepLeft': 'Κρατηθείτε αριστερά',
    'keepRight': 'Κρατηθείτε δεξιά',
    'sharpLeft': 'Στρίψτε απότομα αριστερά',
    'sharpRight': 'Στρίψτε απότομα δεξιά',
    'uturn': 'Κάντε αναστροφή',
    'continueStraight': 'Συνεχίστε ευθεία',
    'continueOn': 'Συνεχίστε',
    'merge': 'Εισέλθετε',
    'rampLeft': 'Στρίψτε αριστερά στη ράμπα',
    'rampRight': 'Στρίψτε δεξιά στη ράμπα',
    'takeRamp': 'Πάρτε τη ράμπα',
    'exitLabelled': 'Βγείτε στην έξοδο {label}',
    'exitPlain': 'Βγείτε',
    'forkLeft': 'Στη διακλάδωση κρατηθείτε αριστερά',
    'forkRight': 'Στη διακλάδωση κρατηθείτε δεξιά',
    'endLeft': 'Στο τέλος του δρόμου στρίψτε αριστερά',
    'endRight': 'Στο τέλος του δρόμου στρίψτε δεξιά',
    'roundabout': 'Στον κυκλικό κόμβο πάρτε την {n}η έξοδο',
    'rotary': 'Στον κυκλικό κόμβο πάρτε την {n}η έξοδο',
  },
  'hu': {
    'on': ' a ',
    'depart': 'Induljon',
    'arrive': 'Megérkezett az úti céljához',
    'turnLeft': 'Forduljon balra',
    'turnRight': 'Forduljon jobbra',
    'keepLeft': 'Tartson balra',
    'keepRight': 'Tartson jobbra',
    'sharpLeft': 'Forduljon élesen balra',
    'sharpRight': 'Forduljon élesen jobbra',
    'uturn': 'Forduljon vissza',
    'continueStraight': 'Haladjon egyenesen',
    'continueOn': 'Folytassa',
    'merge': 'Soroljon be',
    'rampLeft': 'Forduljon balra a felhajtóra',
    'rampRight': 'Forduljon jobbra a felhajtóra',
    'takeRamp': 'Hajtson fel',
    'exitLabelled': 'Hajtson le a {label} kijáraton',
    'exitPlain': 'Hajtson le',
    'forkLeft': 'Az elágazásnál tartson balra',
    'forkRight': 'Az elágazásnál tartson jobbra',
    'endLeft': 'Az út végén forduljon balra',
    'endRight': 'Az út végén forduljon jobbra',
    'roundabout': 'A körforgalomban a {n}. kijárat',
    'rotary': 'A körforgalomban a {n}. kijárat',
  },
  'ro': {
    'on': ' pe ',
    'depart': 'Porniți',
    'arrive': 'Ați ajuns la destinație',
    'turnLeft': 'Virați la stânga',
    'turnRight': 'Virați la dreapta',
    'keepLeft': 'Păstrați stânga',
    'keepRight': 'Păstrați dreapta',
    'sharpLeft': 'Virați brusc la stânga',
    'sharpRight': 'Virați brusc la dreapta',
    'uturn': 'Întoarceți',
    'continueStraight': 'Continuați drept',
    'continueOn': 'Continuați',
    'merge': 'Intrați',
    'rampLeft': 'Virați la stânga pe rampă',
    'rampRight': 'Virați la dreapta pe rampă',
    'takeRamp': 'Luați rampa',
    'exitLabelled': 'Ieșiți la ieșirea {label}',
    'exitPlain': 'Ieșiți',
    'forkLeft': 'La bifurcație păstrați stânga',
    'forkRight': 'La bifurcație păstrați dreapta',
    'endLeft': 'La capătul drumului virați la stânga',
    'endRight': 'La capătul drumului virați la dreapta',
    'roundabout': 'În sensul giratoriu luați ieșirea {n}',
    'rotary': 'În sensul giratoriu luați ieșirea {n}',
  },
  'bg': {
    'on': ' по ',
    'depart': 'Тръгнете',
    'arrive': 'Пристигнахте до целта',
    'turnLeft': 'Завийте наляво',
    'turnRight': 'Завийте надясно',
    'keepLeft': 'Дръжте се вляво',
    'keepRight': 'Дръжте се вдясно',
    'sharpLeft': 'Завийте рязко наляво',
    'sharpRight': 'Завийте рязко надясно',
    'uturn': 'Обърнете',
    'continueStraight': 'Продължете направо',
    'continueOn': 'Продължете',
    'merge': 'Включете се',
    'rampLeft': 'Завийте наляво по рампата',
    'rampRight': 'Завийте надясно по рампата',
    'takeRamp': 'Поемете по рампата',
    'exitLabelled': 'Излезте на изход {label}',
    'exitPlain': 'Излезте',
    'forkLeft': 'На разклона дръжте вляво',
    'forkRight': 'На разклона дръжте вдясно',
    'endLeft': 'В края на пътя завийте наляво',
    'endRight': 'В края на пътя завийте надясно',
    'roundabout': 'На кръговото вземете {n}-ия изход',
    'rotary': 'На кръговото вземете {n}-ия изход',
  },
  'hr': {
    'on': ' na ',
    'depart': 'Krenite',
    'arrive': 'Stigli ste na odredište',
    'turnLeft': 'Skrenite lijevo',
    'turnRight': 'Skrenite desno',
    'keepLeft': 'Držite se lijevo',
    'keepRight': 'Držite se desno',
    'sharpLeft': 'Oštro skrenite lijevo',
    'sharpRight': 'Oštro skrenite desno',
    'uturn': 'Okrenite se',
    'continueStraight': 'Nastavite ravno',
    'continueOn': 'Nastavite',
    'merge': 'Uključite se',
    'rampLeft': 'Skrenite lijevo na priključak',
    'rampRight': 'Skrenite desno na priključak',
    'takeRamp': 'Uđite na priključak',
    'exitLabelled': 'Izađite na izlaz {label}',
    'exitPlain': 'Izađite',
    'forkLeft': 'Na račvanju držite se lijevo',
    'forkRight': 'Na račvanju držite se desno',
    'endLeft': 'Na kraju ceste skrenite lijevo',
    'endRight': 'Na kraju ceste skrenite desno',
    'roundabout': 'Na kružnom toku {n}. izlaz',
    'rotary': 'Na kružnom toku {n}. izlaz',
  },
  'sl': {
    'on': ' na ',
    'depart': 'Speljite',
    'arrive': 'Prispeli ste na cilj',
    'turnLeft': 'Zavijte levo',
    'turnRight': 'Zavijte desno',
    'keepLeft': 'Držite se levo',
    'keepRight': 'Držite se desno',
    'sharpLeft': 'Ostro zavijte levo',
    'sharpRight': 'Ostro zavijte desno',
    'uturn': 'Obrnite se',
    'continueStraight': 'Nadaljujte naravnost',
    'continueOn': 'Nadaljujte',
    'merge': 'Vključite se',
    'rampLeft': 'Zavijte levo na uvoz',
    'rampRight': 'Zavijte desno na uvoz',
    'takeRamp': 'Zapeljite na uvoz',
    'exitLabelled': 'Izvozite na izvozu {label}',
    'exitPlain': 'Izvozite',
    'forkLeft': 'Na razcepu se držite levo',
    'forkRight': 'Na razcepu se držite desno',
    'endLeft': 'Na koncu ceste zavijte levo',
    'endRight': 'Na koncu ceste zavijte desno',
    'roundabout': 'V krožišču zapeljite na {n}. izvoz',
    'rotary': 'V krožišču zapeljite na {n}. izvoz',
  },
  'et': {
    'on': ' teele ',
    'depart': 'Alustage',
    'arrive': 'Olete jõudnud sihtkohta',
    'turnLeft': 'Pöörake vasakule',
    'turnRight': 'Pöörake paremale',
    'keepLeft': 'Hoidke vasakule',
    'keepRight': 'Hoidke paremale',
    'sharpLeft': 'Pöörake järsult vasakule',
    'sharpRight': 'Pöörake järsult paremale',
    'uturn': 'Pöörake tagasi',
    'continueStraight': 'Sõitke otse',
    'continueOn': 'Jätkake',
    'merge': 'Suubuge',
    'rampLeft': 'Pöörake vasakule kaldteele',
    'rampRight': 'Pöörake paremale kaldteele',
    'takeRamp': 'Sõitke kaldteele',
    'exitLabelled': 'Sõitke välja väljasõidul {label}',
    'exitPlain': 'Sõitke välja',
    'forkLeft': 'Hargnemisel hoidke vasakule',
    'forkRight': 'Hargnemisel hoidke paremale',
    'endLeft': 'Tee lõpus pöörake vasakule',
    'endRight': 'Tee lõpus pöörake paremale',
    'roundabout': 'Ringteel valige {n}. väljasõit',
    'rotary': 'Ringteel valige {n}. väljasõit',
  },
  'lt': {
    'on': ' į ',
    'depart': 'Pradėkite',
    'arrive': 'Atvykote į kelionės tikslą',
    'turnLeft': 'Sukite kairėn',
    'turnRight': 'Sukite dešinėn',
    'keepLeft': 'Laikykitės kairės',
    'keepRight': 'Laikykitės dešinės',
    'sharpLeft': 'Sukite staigiai kairėn',
    'sharpRight': 'Sukite staigiai dešinėn',
    'uturn': 'Apsisukite',
    'continueStraight': 'Važiuokite tiesiai',
    'continueOn': 'Tęskite',
    'merge': 'Įsiliekite',
    'rampLeft': 'Sukite kairėn į įvažą',
    'rampRight': 'Sukite dešinėn į įvažą',
    'takeRamp': 'Važiuokite į įvažą',
    'exitLabelled': 'Išvažiuokite išvaža {label}',
    'exitPlain': 'Išvažiuokite',
    'forkLeft': 'Išsišakojime laikykitės kairės',
    'forkRight': 'Išsišakojime laikykitės dešinės',
    'endLeft': 'Kelio gale sukite kairėn',
    'endRight': 'Kelio gale sukite dešinėn',
    'roundabout': 'Žiede pasirinkite {n}-ą išvažiavimą',
    'rotary': 'Žiede pasirinkite {n}-ą išvažiavimą',
  },
  'lv': {
    'on': ' uz ',
    'depart': 'Sāciet',
    'arrive': 'Esat sasniedzis galamērķi',
    'turnLeft': 'Nogriezieties pa kreisi',
    'turnRight': 'Nogriezieties pa labi',
    'keepLeft': 'Turieties pa kreisi',
    'keepRight': 'Turieties pa labi',
    'sharpLeft': 'Strauji nogriezieties pa kreisi',
    'sharpRight': 'Strauji nogriezieties pa labi',
    'uturn': 'Apgriezieties',
    'continueStraight': 'Brauciet taisni',
    'continueOn': 'Turpiniet',
    'merge': 'Iekļaujieties',
    'rampLeft': 'Nogriezieties pa kreisi uz uzbrauktuves',
    'rampRight': 'Nogriezieties pa labi uz uzbrauktuves',
    'takeRamp': 'Brauciet uz uzbrauktuvi',
    'exitLabelled': 'Nobrauciet pa nobrauktuvi {label}',
    'exitPlain': 'Nobrauciet',
    'forkLeft': 'Sazarojumā turieties pa kreisi',
    'forkRight': 'Sazarojumā turieties pa labi',
    'endLeft': 'Ceļa galā nogriezieties pa kreisi',
    'endRight': 'Ceļa galā nogriezieties pa labi',
    'roundabout': 'Aplī izvēlieties {n}. nobrauktuvi',
    'rotary': 'Aplī izvēlieties {n}. nobrauktuvi',
  },
  'ga': {
    'on': ' ar ',
    'depart': 'Tosaigh',
    'arrive': 'Tá tú tagtha ag do cheann scríbe',
    'turnLeft': 'Cas ar chlé',
    'turnRight': 'Cas ar dheis',
    'keepLeft': 'Fan ar chlé',
    'keepRight': 'Fan ar dheis',
    'sharpLeft': 'Cas go géar ar chlé',
    'sharpRight': 'Cas go géar ar dheis',
    'uturn': 'Déan casadh U',
    'continueStraight': 'Lean ar aghaidh díreach',
    'continueOn': 'Lean ar aghaidh',
    'merge': 'Cumaisc',
    'rampLeft': 'Cas ar chlé ar an rampa',
    'rampRight': 'Cas ar dheis ar an rampa',
    'takeRamp': 'Tóg an rampa',
    'exitLabelled': 'Tóg slí amach {label}',
    'exitPlain': 'Tóg an tslí amach',
    'forkLeft': 'Ag an ngabhal fan ar chlé',
    'forkRight': 'Ag an ngabhal fan ar dheis',
    'endLeft': 'Ag deireadh an bhóthair cas ar chlé',
    'endRight': 'Ag deireadh an bhóthair cas ar dheis',
    'roundabout': 'Ag an timpeallán tóg an {n}ú slí amach',
    'rotary': 'Ag an timpeallán tóg an {n}ú slí amach',
  },
  'mt': {
    'on': ' fi ',
    'depart': 'Ibda',
    'arrive': 'Wasalt fid-destinazzjoni tiegħek',
    'turnLeft': 'Dur xellug',
    'turnRight': 'Dur lemin',
    'keepLeft': 'Żomm ix-xellug',
    'keepRight': 'Żomm il-lemin',
    'sharpLeft': 'Dur bil-qawwi xellug',
    'sharpRight': 'Dur bil-qawwi lemin',
    'uturn': 'Agħmel U-turn',
    'continueStraight': 'Kompli dritt',
    'continueOn': 'Kompli',
    'merge': 'Ingħaqad',
    'rampLeft': 'Dur xellug għar-rampa',
    'rampRight': 'Dur lemin għar-rampa',
    'takeRamp': 'Ħu r-rampa',
    'exitLabelled': 'Oħroġ mill-ħruġ {label}',
    'exitPlain': 'Oħroġ',
    'forkLeft': 'Fil-furkettun żomm ix-xellug',
    'forkRight': 'Fil-furkettun żomm il-lemin',
    'endLeft': 'Fl-aħħar tat-triq dur xellug',
    'endRight': 'Fl-aħħar tat-triq dur lemin',
    'roundabout': 'Fir-rawndabawt ħu l-{n} ħruġ',
    'rotary': 'Fir-rawndabawt ħu l-{n} ħruġ',
  },
};

/// Looks up [key] for [lang], falling back to English.
String navPhrase(String lang, String key) =>
    navPhrases[lang]?[key] ?? navPhrases['en']![key] ?? '';
