import 'dart:convert';
import 'dart:io';

import 'package:roadstr/services/routing_request_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/routing_requests_v1.tsv';

typedef _Case = ({
  String operation,
  String name,
  RoutingRequestPoint? origin,
  RoutingRequestPoint? destination,
  String? arg1,
  String? arg2,
  String? arg3,
  String? arg4,
  double? number,
  bool flag,
  List<RoutingRequestPoint> via,
});

String buildRoutingRequestsFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_routing_requests_fixture.dart.',
    '# operation\tname\torigin_lat\torigin_lon\tdestination_lat\tdestination_lon\targ1_b64\targ2_b64\targ3_b64\targ4_b64\tnumber\tflag\tvia_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    final expected = _evaluate(value);
    rows.add([
      value.operation,
      value.name,
      value.origin?.latitude.toString() ?? '-',
      value.origin?.longitude.toString() ?? '-',
      value.destination?.latitude.toString() ?? '-',
      value.destination?.longitude.toString() ?? '-',
      _encodeOptional(value.arg1),
      _encodeOptional(value.arg2),
      _encodeOptional(value.arg3),
      _encodeOptional(value.arg4),
      value.number?.toString() ?? '-',
      value.flag.toString(),
      _encode(value.via
          .map((point) => '${point.latitude},${point.longitude}')
          .join(';')),
      _encode(expected),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  switch (value.operation) {
    case 'ors_language':
      return 'value=${RoutingRequestProtocol.openRouteServiceLanguage(value.arg1!)}';
    case 'valhalla_language':
      return 'value=${RoutingRequestProtocol.valhallaLanguage(value.arg1!)}';
    case 'gh_endpoint':
      return 'value=${RoutingRequestProtocol.graphHopperEndpoint(value.arg1)}';
    case 'ors':
      return _canonical(RoutingRequestProtocol.openRouteService(
        origin: value.origin!,
        destination: value.destination!,
        apiKey: value.arg1!,
        languageCode: value.arg2!,
        vehicle: value.arg3!,
      ));
    case 'gh_route':
      return _canonical(RoutingRequestProtocol.graphHopperRoute(
        origin: value.origin!,
        destination: value.destination!,
        server: RoutingRequestProtocol.graphHopperEndpoint(value.arg1),
        languageCode: value.arg2!,
        vehicle: value.arg3!,
        apiKey: value.arg4,
      ));
    case 'gh_probe':
      return _canonical(RoutingRequestProtocol.graphHopperProbe(
        server: RoutingRequestProtocol.graphHopperEndpoint(value.arg1),
        apiKey: value.arg4,
      ));
    case 'osrm':
      return _canonical(RoutingRequestProtocol.osrmRoute(
        origin: value.origin!,
        destination: value.destination!,
        vehicle: value.arg1!,
        endpoint: value.arg2,
        via: value.via,
        requestAlternatives: value.flag,
        originBearingDegrees: value.number,
      ));
    case 'valhalla':
      return _canonical(RoutingRequestProtocol.valhalla(
        origin: value.origin!,
        destination: value.destination!,
        languageCode: value.arg1!,
        endpoint: value.arg2,
        costingPolicy: ValhallaCostingPolicy.values.byName(value.arg3!),
      ));
    case 'retime':
      return _canonical(RoutingRequestProtocol.osrmRetime(
        waypoints: value.arg1!,
        endpoint: value.arg2,
      ));
  }
  throw StateError('Unknown routing fixture operation: ${value.operation}');
}

String _canonical(RoutingProviderRequest request) {
  final headers = request.headers.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  return [
    'method=${request.method.name}',
    'uri=${request.uri}',
    'headers=${headers.map((e) => '${_encode(e.key)}:${_encode(e.value)}').join(',')}',
    'body=${request.body == null ? '-' : _encode(request.body!)}',
  ].join('\n');
}

Iterable<_Case> _cases() sync* {
  for (final code in <String>[
    'cs',
    'de',
    'en',
    'es',
    'fr',
    'el',
    'hu',
    'it',
    'ja',
    'nl',
    'pl',
    'pt',
    'ro',
    'ru',
    'tr',
    'uk',
    'zh',
    'EL',
    'xx',
    '',
  ]) {
    yield _valueCase('ors_language', code.isEmpty ? 'empty' : code, code);
  }
  for (final code in <String>[
    'bg',
    'cs',
    'da',
    'de',
    'el',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'hu',
    'it',
    'ja',
    'nl',
    'pl',
    'pt',
    'ro',
    'ru',
    'sk',
    'sl',
    'sv',
    'zh',
    'PT',
    'xx',
    '',
  ]) {
    yield _valueCase('valhalla_language', code.isEmpty ? 'empty' : code, code);
  }

  yield _valueCase('gh_endpoint', 'null', null);
  yield _valueCase('gh_endpoint', 'empty', '');
  yield _valueCase('gh_endpoint', 'ascii-whitespace', '  \t ');
  yield _valueCase(
      'gh_endpoint', 'trimmed-custom', '  https://routes.example/route  ');
  yield _valueCase('gh_endpoint', 'unicode-whitespace',
      '\u00a0https://routes.example/route\ufeff');

  const turin = RoutingRequestPoint(45.0703, 7.6869);
  const milan = RoutingRequestPoint(45.4642, 9.19);
  const negative = RoutingRequestPoint(-33.8688, -151.2093);
  const tiny = RoutingRequestPoint(-0.0, 0.0000005);

  yield _requestCase('ors', 'driving-it', turin, milan,
      arg1: 'fixture-key', arg2: 'it', arg3: 'driving');
  yield _requestCase('ors', 'walking-greek', turin, milan,
      arg1: 'key +&?', arg2: 'el', arg3: 'walking');
  yield _requestCase('ors', 'cycling-ukrainian', negative, turin,
      arg1: '', arg2: 'uk', arg3: 'cycling');
  yield _requestCase('ors', 'unknown-mode-language', tiny, negative,
      arg1: 'test', arg2: 'xx', arg3: 'scooter');
  yield _requestCase('ors', 'uppercase-language', turin, tiny,
      arg1: 'test', arg2: 'EL', arg3: 'driving');

  yield _requestCase('gh_route', 'public-no-key', turin, milan,
      arg1: null, arg2: 'it', arg3: 'driving');
  yield _requestCase('gh_route', 'public-empty-key', turin, milan,
      arg1: '', arg2: 'en', arg3: 'driving', arg4: '');
  yield _requestCase('gh_route', 'public-special-key-and-locale', turin, milan,
      arg1: null, arg2: 'pt BR+?', arg3: 'walking', arg4: 'key +&?');
  yield _requestCase('gh_route', 'public-cycling', negative, turin,
      arg1: null, arg2: 'de', arg3: 'cycling', arg4: 'fixture');
  yield _requestCase('gh_route', 'unknown-vehicle', tiny, negative,
      arg1: null, arg2: '日本語', arg3: 'scooter');
  yield _requestCase('gh_route', 'self-hosted-omits-key', turin, milan,
      arg1: 'https://routes.example/route',
      arg2: 'fr',
      arg3: 'driving',
      arg4: 'must-not-be-sent');
  yield _requestCase('gh_route', 'self-hosted-replaces-query', turin, milan,
      arg1: 'https://routes.example/route?old=1#frag',
      arg2: 'en',
      arg3: 'walking',
      arg4: 'ignored');

  yield _simpleCase('gh_probe', 'public-no-key', arg1: null, arg4: null);
  yield _simpleCase('gh_probe', 'public-empty-key', arg1: null, arg4: '');
  yield _simpleCase('gh_probe', 'public-special-key',
      arg1: null, arg4: 'key +&?');
  yield _simpleCase('gh_probe', 'self-hosted-omits-key',
      arg1: 'https://routes.example/route', arg4: 'ignored');

  yield _requestCase('osrm', 'driving-single', turin, milan, arg1: 'driving');
  yield _requestCase('osrm', 'walking-single', turin, milan, arg1: 'walking');
  yield _requestCase('osrm', 'cycling-single', turin, milan, arg1: 'cycling');
  yield _requestCase('osrm', 'unknown-mode', negative, tiny, arg1: 'horse');
  yield _requestCase('osrm', 'plain-alternatives', turin, milan,
      arg1: 'driving', flag: true);
  yield _requestCase('osrm', 'one-via-no-alternatives', turin, milan,
      arg1: 'driving', flag: true, via: const [RoutingRequestPoint(45.2, 8.1)]);
  yield _requestCase('osrm', 'waypoint-cap', turin, milan,
      arg1: 'driving',
      flag: true,
      via: const [
        RoutingRequestPoint(45.1, 8.1),
        RoutingRequestPoint(45.2, 8.2),
        RoutingRequestPoint(45.3, 8.3),
        RoutingRequestPoint(45.4, 8.4),
        RoutingRequestPoint(45.5, 8.5),
      ]);
  yield _requestCase('osrm', 'bearing-round-down', turin, milan,
      arg1: 'driving', flag: true, number: 12.4);
  yield _requestCase('osrm', 'bearing-round-up', turin, milan,
      arg1: 'driving', flag: true, number: 12.5);
  yield _requestCase('osrm', 'bearing-wrap', turin, milan,
      arg1: 'driving', number: 359.5);
  yield _requestCase('osrm', 'bearing-full-turn', turin, milan,
      arg1: 'driving', number: 360);
  yield _requestCase('osrm', 'bearing-negative-half', turin, milan,
      arg1: 'driving', number: -0.5);
  yield _requestCase('osrm', 'bearing-negative', turin, milan,
      arg1: 'driving', number: -1.6);
  yield _requestCase('osrm', 'custom-endpoint', tiny, negative,
      arg1: 'driving', arg2: 'http://127.0.0.1:8989/route');

  for (final policy in ValhallaCostingPolicy.values) {
    yield _requestCase('valhalla', policy.name, turin, milan,
        arg1: 'it', arg3: policy.name);
  }
  yield _requestCase('valhalla', 'language-fallback', negative, turin,
      arg1: 'xx', arg3: ValhallaCostingPolicy.avoidTracks.name);
  yield _requestCase('valhalla', 'uppercase-language', tiny, negative,
      arg1: 'PT', arg3: ValhallaCostingPolicy.softHighwayAndTollAvoidance.name);
  yield _requestCase('valhalla', 'custom-endpoint-replaces-query', turin, milan,
      arg1: 'en',
      arg2: 'http://127.0.0.1:8002/route?old=1#frag',
      arg3: ValhallaCostingPolicy.hardHighwayAndTollExclusion.name);

  yield _simpleCase('retime', 'public',
      arg1: '7.68690,45.07030;9.19000,45.46420');
  yield _simpleCase('retime', 'custom',
      arg1: '-0.00000,-0.00000;0.00001,0.00001',
      arg2: 'http://127.0.0.1:5000/route');
  yield _simpleCase('retime', 'empty-waypoints', arg1: '');
}

_Case _valueCase(String operation, String name, String? value) => (
      operation: operation,
      name: name,
      origin: null,
      destination: null,
      arg1: value,
      arg2: null,
      arg3: null,
      arg4: null,
      number: null,
      flag: false,
      via: const [],
    );

_Case _simpleCase(String operation, String name,
        {String? arg1, String? arg2, String? arg3, String? arg4}) =>
    (
      operation: operation,
      name: name,
      origin: null,
      destination: null,
      arg1: arg1,
      arg2: arg2,
      arg3: arg3,
      arg4: arg4,
      number: null,
      flag: false,
      via: const [],
    );

_Case _requestCase(
  String operation,
  String name,
  RoutingRequestPoint origin,
  RoutingRequestPoint destination, {
  String? arg1,
  String? arg2,
  String? arg3,
  String? arg4,
  double? number,
  bool flag = false,
  List<RoutingRequestPoint> via = const [],
}) =>
    (
      operation: operation,
      name: name,
      origin: origin,
      destination: destination,
      arg1: arg1,
      arg2: arg2,
      arg3: arg3,
      arg4: arg4,
      number: number,
      flag: flag,
      via: via,
    );

String _encodeOptional(String? value) => value == null ? '-' : _encode(value);

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildRoutingRequestsFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
