import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/search_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/search_responses_v1.tsv';

typedef _Case = ({
  String operation,
  String name,
  LatLng center,
  String? fallbackName,
  String input,
});

String buildSearchResponsesFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_search_responses_fixture.dart.',
    '# operation\tname\tcenter_lat\tcenter_lon\tfallback_b64\tinput_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.operation,
      value.name,
      value.center.latitude,
      value.center.longitude,
      value.fallbackName == null ? '-' : _encode(value.fallbackName!),
      _encode(value.input),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  try {
    return switch (value.operation) {
      'nominatim' => _canonicalResults(
          SearchResponseProtocol.parseNominatimSearch(value.input),
        ),
      'reverse' => _canonicalReverse(
          SearchResponseProtocol.parseNominatimReverse(value.input),
        ),
      'photon' => _canonicalResults(
          SearchResponseProtocol.parsePhoton(value.input),
        ),
      'overpass' => _canonicalResults([
          for (final element
              in SearchResponseProtocol.parseOverpassElements(value.input))
            if (SearchResponseProtocol.overpassElementToResult(
              element,
              value.center,
              fallbackName: value.fallbackName,
            )
                case final result?)
              result,
        ]),
      'overpass_elements' => _canonicalElements(
          SearchResponseProtocol.parseOverpassElements(value.input),
        ),
      _ => throw StateError('Unknown operation ${value.operation}'),
    };
  } catch (_) {
    return 'error';
  }
}

String _canonicalResults(List<NominatimResult> results) => [
      'count=${results.length}',
      'items=${results.map(_canonicalResult).join(';')}',
    ].join('\n');

String _canonicalResult(NominatimResult result) => [
      _encode(result.displayName),
      _encode(result.shortName),
      _f6(result.position.latitude),
      _f6(result.position.longitude),
      _optional(result.cls),
      _optional(result.type),
      _optional(result.city),
      _optional(result.openingHours),
      result.distanceM == null ? '-' : _f3(result.distanceM!),
      _optional(result.brand),
      _encode(result.emoji),
      _encode(result.categoryLabel),
    ].join(',');

String _canonicalReverse(NominatimReverseDetail? detail) => detail == null
    ? 'null'
    : [
        'display=${_encode(detail.display)}',
        'wiki=${_optional(detail.wikiQuery)}',
        'opening=${_optional(detail.openingHours)}',
        'label=${_encode(detail.label)}',
      ].join('\n');

String _canonicalElements(List<Map<String, dynamic>> elements) => [
      'count=${elements.length}',
      'items=${elements.map((element) {
        final type = element['type'];
        final id = element['id'];
        final keys = element.keys.toList()..sort();
        return '${_encode(type is String ? type : '')},'
            '${id is num ? id : '-'},${keys.map(_encode).join('.')}';
      }).join(';')}',
    ].join('\n');

String _optional(String? value) => value == null ? '-' : _encode(value);

String _f3(double value) => value.toStringAsFixed(3);

String _f6(double value) => value.toStringAsFixed(6);

Iterable<_Case> _cases() sync* {
  const center = LatLng(41.9028, 12.4964);

  yield _jsonCase('nominatim', 'address-poi-and-city', [
    _nominatim(
      lat: '45.4642',
      lon: '9.1900',
      display: '12, Via Roma, Milano, Lombardia, Italia',
      cls: 'highway',
      type: 'residential',
      address: const {
        'road': 'Via Roma',
        'house_number': '12',
        'city': 'Milano',
      },
    ),
    _nominatim(
      lat: '44.285',
      lon: '11.882',
      display: 'Usato Faenza, Faenza, Italia',
      cls: 'shop',
      type: 'second_hand',
      address: const {'town': 'Faenza'},
      extra: const {'brand': " Mercatino dell'Usato "},
    ),
    _nominatim(
      lat: '-33.8688',
      lon: '151.2093',
      display: 'Sydney, New South Wales, Australia',
      cls: 'place',
      type: 'city',
    ),
  ]);
  yield _jsonCase('nominatim', 'mixed-malformed-entries', [
    null,
    42,
    {'lat': 'not-a-number', 'lon': '9', 'display_name': 'Bad'},
    {'lat': '91', 'lon': '9', 'display_name': 'Out of range'},
    {'lat': '45', 'lon': '9'},
    _nominatim(
      lat: '45',
      lon: '9',
      display: 'Kept, Italia',
      cls: 'amenity',
      type: 'cafe',
    ),
  ]);
  yield _jsonCase('nominatim', 'remote-text-bounds', [
    _nominatim(
      lat: '45',
      lon: '9',
      display: ' D${'x' * 400} ',
      cls: 'C' * 100,
      type: 'T' * 100,
      address: {
        'road': 'R' * 150,
        'house_number': '1' * 30,
        'municipality': 'M' * 150,
      },
      extra: {'brand': 'B' * 200},
    ),
  ]);
  yield _jsonCase('nominatim', 'address-hierarchy', [
    _nominatim(
      lat: '64.1466',
      lon: '-21.9426',
      display: 'Laugavegur, Reykjavík, Ísland',
      cls: 'highway',
      type: 'pedestrian',
      address: const {
        'road': 'Laugavegur',
        'hamlet': 'ignored after village',
        'village': 'Reykjavík',
      },
    ),
  ]);
  yield _jsonCase('nominatim', 'category-matrix', [
    for (final entry in _categoryMatrix.indexed)
      _nominatim(
        lat: '${40 + entry.$1 * 0.001}',
        lon: '${10 + entry.$1 * 0.001}',
        display: '${entry.$2.$1}, Context, Region, Country',
        cls: entry.$2.$1,
        type: entry.$2.$2,
      ),
  ]);
  yield _rawCase('nominatim', 'invalid-json', '{');
  yield _jsonCase('nominatim', 'wrong-top-level-shape', {'items': []});

  yield _jsonCase('reverse', 'named-poi-with-city-and-hours', {
    'display_name': 'Colosseo, Piazza del Colosseo, Roma, Italia',
    'name': 'Colosseo',
    'address': {
      'tourism': 'Colosseo',
      'road': 'Piazza del Colosseo',
      'house_number': '1',
      'city': 'Roma',
    },
    'extratags': {'opening_hours': ' 09:00-19:00 '},
  });
  yield _jsonCase('reverse', 'street-label-and-town', {
    'display_name': '12, Via Roberto Ricci, Torino, Piemonte, Italia',
    'address': {
      'house_number': '12',
      'road': 'Via Roberto Ricci',
      'town': 'Torino',
    },
  });
  yield _jsonCase('reverse', 'numeric-poi-is-ignored', {
    'display_name': '5, Piazza del Popolo, Roma, Italia',
    'name': '5',
    'address': {'neighbourhood': '7', 'city': 'Roma'},
  });
  yield _jsonCase('reverse', 'county-fallback', {
    'display_name': 'Somewhere, County',
    'address': {'county': 'County'},
    'extratags': {'opening_hours': '   '},
  });
  yield _jsonCase('reverse', 'control-and-length-sanitizing', {
    'display_name': '5, Piazza, Torino',
    'address': {
      'road': 'Via\u0000Roma\u001f',
      'house_number': '42',
      'city': 'C' * 100,
    },
  });
  yield _jsonCase('reverse', 'wrong-field-type', {
    'display_name': 42,
    'address': {},
  });
  yield _rawCase('reverse', 'invalid-json', '[');

  yield _jsonCase('photon', 'street-name-and-city', {
    'features': [
      _photon(
        lon: 7.6869,
        lat: 45.0703,
        properties: const {
          'name': 'Farmacia Centrale',
          'street': 'Via Roma',
          'housenumber': '7',
          'city': 'Torino',
          'state': 'Piemonte',
          'country': 'Italia',
          'osm_key': 'amenity',
          'osm_value': 'pharmacy',
        },
      ),
    ],
  });
  yield _jsonCase('photon', 'name-only-and-city-only', {
    'features': [
      _photon(
        lon: 2.3522,
        lat: 48.8566,
        properties: const {
          'name': 'Louvre',
          'city': 'Paris',
          'country': 'France',
          'osm_key': 'tourism',
          'osm_value': 'museum',
        },
      ),
      _photon(
        lon: 13.405,
        lat: 52.52,
        properties: const {'city': 'Berlin', 'country': 'Deutschland'},
      ),
    ],
  });
  yield _jsonCase('photon', 'deduplicated-display-components', {
    'features': [
      _photon(
        lon: 9,
        lat: 45,
        properties: const {
          'name': 'Milano',
          'city': 'Milano',
          'state': 'Milano',
          'country': 'Italia',
        },
      ),
    ],
  });
  yield _jsonCase('photon', 'control-and-length-sanitizing', {
    'features': [
      _photon(
        lon: 9,
        lat: 45,
        properties: {
          'name': ' N\u0000ame ',
          'street': 'S' * 180,
          'city': 'Town',
          'osm_key': 'shop',
          'osm_value': 'supermarket',
        },
      ),
    ],
  });
  yield _jsonCase('photon', 'mixed-malformed-features', {
    'features': [
      null,
      {
        'geometry': {
          'coordinates': [9]
        }
      },
      _photon(lon: 181, lat: 45, properties: const {'name': 'Bad'}),
      _photon(lon: 9, lat: 45, properties: const {'state': 'Nameless'}),
      _photon(lon: 9, lat: 45, properties: const {'name': 'Kept'}),
    ],
  });
  yield _jsonCase('photon', 'missing-features', {'type': 'FeatureCollection'});
  yield _jsonCase('photon', 'wrong-features-shape', {'features': {}});
  yield _rawCase('photon', 'invalid-json', '{');

  yield _jsonCase(
      'overpass',
      'node-way-brand-and-fallback',
      {
        'elements': [
          _node(
              1, 41.9058, 12.4964, const {'amenity': 'bank', 'name': 'Intesa'}),
          {
            'type': 'way',
            'id': 2,
            'center': {'lat': 41.9078, 'lon': 12.4964},
            'tags': {'shop': 'supermarket', 'brand': ' Conad '},
          },
          _node(3, 41.9128, 12.4964, const {'amenity': 'atm'}),
        ],
      },
      center: center,
      fallbackName: 'Nearby');
  yield _jsonCase(
      'overpass',
      'class-priority-and-hours',
      {
        'elements': [
          _node(1, 41.9, 12.5, const {
            'shop': 'bakery',
            'amenity': 'cafe',
            'tourism': 'attraction',
            'name': 'Forno',
            'opening_hours': ' Mo-Fr 08:00-18:00 ',
          }),
        ],
      },
      center: center);
  yield _jsonCase(
      'overpass',
      'remote-text-bounds',
      {
        'elements': [
          _node(1, 41.9, 12.5, {
            'tourism': 'T' * 100,
            'name': 'N' * 150,
            'opening_hours': 'O' * 350,
          }),
        ],
      },
      center: center);
  yield _jsonCase(
      'overpass',
      'invalid-coordinates-and-unnamed',
      {
        'elements': [
          _node(1, 95, 12, const {'name': 'Bad'}),
          _node(2, 41, 12, const {}),
          {
            'type': 'way',
            'id': 3,
            'tags': const {'name': 'No center'}
          },
          _node(4, 41, 12, const {'name': 'Kept'}),
        ],
      },
      center: center);
  yield _jsonCase(
      'overpass',
      'non-map-elements-are-filtered',
      {
        'elements': [
          null,
          42,
          'bad',
          _node(1, 41.9, 12.5, const {'name': 'Kept'}),
        ],
      },
      center: center);
  yield _jsonCase(
      'overpass',
      'wrong-element-field-type-errors',
      {
        'elements': [
          {
            'type': 'node',
            'id': 1,
            'lat': '41',
            'lon': 12,
            'tags': const {'name': 'Bad'}
          },
        ],
      },
      center: center);
  yield _jsonCase('overpass', 'missing-elements', {'version': 0.6},
      center: center);
  yield _rawCase('overpass', 'invalid-json', '{', center: center);

  yield _jsonCase('overpass_elements', 'filters-and-preserves-maps', {
    'elements': [
      {'type': 'node', 'id': 1, 'lat': 41.9},
      null,
      'bad',
      {'type': 'way', 'id': 2, 'center': const {}},
    ],
  });
  yield _jsonCase(
      'overpass_elements', 'missing-elements', {'generator': 'Overpass'});
  yield _jsonCase(
      'overpass_elements', 'wrong-elements-shape', {'elements': {}});
  yield _rawCase('overpass_elements', 'wrong-top-level-shape', '[]');
}

const _categoryMatrix = <(String, String)>[
  ('highway', 'residential'),
  ('place', 'city'),
  ('place', 'village'),
  ('place', 'suburb'),
  ('amenity', 'restaurant'),
  ('amenity', 'cafe'),
  ('amenity', 'pub'),
  ('amenity', 'hospital'),
  ('amenity', 'pharmacy'),
  ('amenity', 'school'),
  ('amenity', 'university'),
  ('amenity', 'bank'),
  ('amenity', 'atm'),
  ('amenity', 'fuel'),
  ('amenity', 'parking'),
  ('amenity', 'police'),
  ('amenity', 'post_office'),
  ('amenity', 'library'),
  ('amenity', 'theatre'),
  ('amenity', 'cinema'),
  ('amenity', 'place_of_worship'),
  ('amenity', 'townhall'),
  ('tourism', 'museum'),
  ('tourism', 'hotel'),
  ('tourism', 'attraction'),
  ('tourism', 'artwork'),
  ('tourism', 'gallery'),
  ('tourism', 'camp_site'),
  ('tourism', 'zoo'),
  ('shop', 'supermarket'),
  ('shop', 'bakery'),
  ('shop', 'clothes'),
  ('shop', 'electronics'),
  ('shop', 'books'),
  ('shop', 'florist'),
  ('office', 'government'),
  ('office', 'company'),
  ('building', 'public'),
  ('building', 'hospital'),
  ('building', 'school'),
  ('natural', 'beach'),
  ('natural', 'water'),
  ('natural', 'peak'),
  ('natural', 'forest'),
  ('leisure', 'park'),
  ('leisure', 'stadium'),
  ('leisure', 'swimming_pool'),
  ('historic', 'castle'),
  ('railway', 'station'),
  ('aeroway', 'aerodrome'),
  ('waterway', 'river'),
  ('landuse', 'forest'),
  ('unknown', 'thing'),
];

Map<String, dynamic> _nominatim({
  required String lat,
  required String lon,
  required String display,
  String? cls,
  String? type,
  Map<String, Object?>? address,
  Map<String, Object?>? extra,
}) =>
    {
      'lat': lat,
      'lon': lon,
      'display_name': display,
      if (cls != null) 'class': cls,
      if (type != null) 'type': type,
      if (address != null) 'address': address,
      if (extra != null) 'extratags': extra,
    };

Map<String, dynamic> _photon({
  required Object lon,
  required Object lat,
  required Map<String, Object?> properties,
}) =>
    {
      'type': 'Feature',
      'geometry': {
        'type': 'Point',
        'coordinates': [lon, lat],
      },
      'properties': properties,
    };

Map<String, dynamic> _node(
  int id,
  Object lat,
  Object lon,
  Map<String, Object?> tags,
) =>
    {'type': 'node', 'id': id, 'lat': lat, 'lon': lon, 'tags': tags};

_Case _jsonCase(
  String operation,
  String name,
  Object? input, {
  LatLng center = const LatLng(0, 0),
  String? fallbackName,
}) =>
    (
      operation: operation,
      name: name,
      center: center,
      fallbackName: fallbackName,
      input: jsonEncode(input),
    );

_Case _rawCase(
  String operation,
  String name,
  String input, {
  LatLng center = const LatLng(0, 0),
  String? fallbackName,
}) =>
    (
      operation: operation,
      name: name,
      center: center,
      fallbackName: fallbackName,
      input: input,
    );

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildSearchResponsesFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
