import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/routing_orchestration_protocol.dart';
import 'package:roadstr/services/routing_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/routing_orchestration_v1.tsv';

typedef _Event = ({
  RoutingRouteAttempt attempt,
  RoutingAttemptOutcome outcome,
  List<RouteResult> routes,
});
typedef _Case = ({
  String name,
  RoutingProvider provider,
  double speedKmh,
  double? bearing,
  double straightLineM,
  List<_Event> events,
});

String buildRoutingOrchestrationFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_routing_orchestration_fixture.dart.',
    '# name\tprovider\tspeed_kmh\tbearing\tstraight_m\tevents_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.name,
      value.provider.name,
      value.speedKmh,
      value.bearing ?? '-',
      value.straightLineM,
      _encode(jsonEncode(value.events.map(_eventJson).toList())),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  final state = RoutingOrchestrationProtocol(
    provider: value.provider,
    speedKmh: value.speedKmh,
    originBearingDegrees: value.bearing,
    straightLineDistanceM: value.straightLineM,
  );
  final transcript = <String>['initial=${state.initialAttempt.name}'];
  for (var index = 0; index < value.events.length; index++) {
    final event = value.events[index];
    final decision = state.accept(
      event.attempt,
      event.outcome,
      event.routes,
    );
    transcript.add(_decision(index, decision, state.isCompleted));
  }
  return transcript.join('\n');
}

String _decision(
  int index,
  RoutingOrchestrationDecision decision,
  bool completed,
) =>
    '$index:'
    'next=${decision.nextAttempt?.name ?? '-'};'
    'final=${_distances(decision.finalRoutes)};'
    'propagate=${decision.propagateFailure ? 1 : 0};'
    'done=${completed ? 1 : 0}';

String _distances(List<RouteResult>? routes) => routes == null
    ? '-'
    : routes.map((route) => route.totalDistanceM.toStringAsFixed(0)).join(',');

Map<String, Object> _eventJson(_Event event) => {
      'attempt': event.attempt.name,
      'outcome': event.outcome.name,
      'distances': [for (final route in event.routes) route.totalDistanceM],
    };

RouteResult _route(double distanceM) => RouteResult(
      polyline: const [LatLng(45, 9), LatLng(45.01, 9.01)],
      steps: const [],
      totalDistanceM: distanceM,
      totalDurationS: 60,
    );

_Event _success(RoutingRouteAttempt attempt,
        [List<double> distances = const []]) =>
    (
      attempt: attempt,
      outcome: RoutingAttemptOutcome.success,
      routes: distances.map(_route).toList(),
    );

_Event _failure(RoutingRouteAttempt attempt) => (
      attempt: attempt,
      outcome: RoutingAttemptOutcome.routingFailure,
      routes: const [],
    );

_Case _case(
  String name, {
  RoutingProvider provider = RoutingProvider.osrm,
  double speedKmh = 30,
  double? bearing = 90,
  double straightLineM = 1000,
  required List<_Event> events,
}) =>
    (
      name: name,
      provider: provider,
      speedKmh: speedKmh,
      bearing: bearing,
      straightLineM: straightLineM,
      events: events,
    );

Iterable<_Case> _cases() sync* {
  yield _case(
    'moving-osrm-accepts-constrained',
    events: [
      _success(RoutingRouteAttempt.constrained, [2000])
    ],
  );
  yield _case(
    'speed-at-threshold-is-unconstrained',
    speedKmh: 3,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'speed-below-threshold-is-unconstrained',
    speedKmh: 2.99,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'nan-speed-is-unconstrained',
    speedKmh: double.nan,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'infinite-speed-is-unconstrained',
    speedKmh: double.infinity,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'missing-bearing-is-unconstrained',
    bearing: null,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'openroute-never-constrains',
    provider: RoutingProvider.openRoute,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'graphhopper-never-constrains',
    provider: RoutingProvider.graphHopper,
    events: [
      _success(RoutingRouteAttempt.unconstrained, [2000])
    ],
  );
  yield _case(
    'empty-constrained-retries',
    events: [
      _success(RoutingRouteAttempt.constrained),
      _success(RoutingRouteAttempt.unconstrained, [2100]),
    ],
  );
  yield _case(
    'routing-failure-constrained-retries',
    events: [
      _failure(RoutingRouteAttempt.constrained),
      _success(RoutingRouteAttempt.unconstrained, [2200]),
    ],
  );
  yield _case(
    'implausible-constrained-retries',
    events: [
      _success(RoutingRouteAttempt.constrained, [13001]),
      _success(RoutingRouteAttempt.unconstrained, [2300]),
    ],
  );
  yield _case(
    'exact-implausible-boundary-is-accepted',
    events: [
      _success(RoutingRouteAttempt.constrained, [13000])
    ],
  );
  yield _case(
    'shortest-constrained-route-controls-admission',
    events: [
      _success(RoutingRouteAttempt.constrained, [14000, 2000])
    ],
  );
  yield _case(
    'accepted-route-order-is-preserved',
    events: [
      _success(RoutingRouteAttempt.constrained, [3000, 2000])
    ],
  );
  yield _case(
    'direct-unconstrained-empty-is-terminal',
    bearing: null,
    events: [_success(RoutingRouteAttempt.unconstrained)],
  );
  yield _case(
    'direct-unconstrained-failure-propagates',
    bearing: null,
    events: [_failure(RoutingRouteAttempt.unconstrained)],
  );
  yield _case(
    'fallback-empty-is-terminal',
    events: [
      _success(RoutingRouteAttempt.constrained),
      _success(RoutingRouteAttempt.unconstrained),
    ],
  );
  yield _case(
    'fallback-failure-propagates',
    events: [
      _failure(RoutingRouteAttempt.constrained),
      _failure(RoutingRouteAttempt.unconstrained),
    ],
  );
  yield _case(
    'premature-unconstrained-completion-is-ignored',
    events: [
      _success(RoutingRouteAttempt.unconstrained, [999]),
      _success(RoutingRouteAttempt.constrained, [2000]),
    ],
  );
  yield _case(
    'duplicate-constrained-after-final-is-ignored',
    events: [
      _success(RoutingRouteAttempt.constrained, [2000]),
      _success(RoutingRouteAttempt.constrained, [999]),
    ],
  );
  yield _case(
    'constrained-duplicate-after-retry-is-ignored',
    events: [
      _failure(RoutingRouteAttempt.constrained),
      _success(RoutingRouteAttempt.constrained, [2000]),
      _success(RoutingRouteAttempt.unconstrained, [2400]),
    ],
  );
  yield _case(
    'late-unconstrained-after-final-is-ignored',
    events: [
      _success(RoutingRouteAttempt.constrained, [2000]),
      _success(RoutingRouteAttempt.unconstrained, [999]),
    ],
  );
  yield _case(
    'constrained-result-for-openroute-is-ignored',
    provider: RoutingProvider.openRoute,
    events: [
      _success(RoutingRouteAttempt.constrained, [999]),
      _success(RoutingRouteAttempt.unconstrained, [2500]),
    ],
  );
  yield _case(
    'fallback-order-is-preserved',
    events: [
      _success(RoutingRouteAttempt.constrained),
      _success(RoutingRouteAttempt.unconstrained, [4000, 2600]),
    ],
  );
  yield _case(
    'negative-bearing-still-constrains',
    bearing: -10,
    events: [
      _success(RoutingRouteAttempt.constrained, [2000])
    ],
  );
  yield _case(
    'nan-bearing-preserves-existing-constrained-policy',
    bearing: double.nan,
    events: [
      _success(RoutingRouteAttempt.constrained, [2000])
    ],
  );
  yield _case(
    'zero-distance-boundary-is-five-kilometres',
    straightLineM: 0,
    events: [
      _success(RoutingRouteAttempt.constrained, [5000])
    ],
  );
  yield _case(
    'zero-distance-over-boundary-retries',
    straightLineM: 0,
    events: [
      _success(RoutingRouteAttempt.constrained, [5001]),
      _success(RoutingRouteAttempt.unconstrained, [100]),
    ],
  );
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildRoutingOrchestrationFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
