import 'dart:convert';
import 'dart:io';

import 'package:roadstr/services/routing_provider_config.dart';

const outputPath =
    'android/app/src/test/resources/parity/routing_provider_config_v1.tsv';

typedef _Case = ({
  String name,
  String providerKey,
  String? secureApiKey,
  String legacyApiKey,
  String graphHopperServer,
  bool deferCredentialReadForOsrm,
});

String buildRoutingProviderConfigFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_routing_provider_config_fixture.dart.',
    '# name\tinput_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    final input = jsonEncode({
      'provider': value.providerKey,
      'secure': value.secureApiKey,
      'legacy': value.legacyApiKey,
      'server': value.graphHopperServer,
      'deferOsrm': value.deferCredentialReadForOsrm,
    });
    rows.add([
      value.name,
      _encode(input),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  final result = RoutingProviderConfigProtocol.resolve(
    providerKey: value.providerKey,
    secureApiKey: value.secureApiKey,
    legacyApiKey: value.legacyApiKey,
    graphHopperServer: value.graphHopperServer,
    deferCredentialReadForOsrm: value.deferCredentialReadForOsrm,
  );
  return 'provider=${result.provider.name};'
      'api=${result.apiKey ?? '-'};'
      'server=${result.graphHopperServer ?? '-'};'
      'issue=${result.issue.name};'
      'reads=${result.readsCredentials ? 1 : 0};'
      'migration=${result.legacyApiKeyMigration ?? '-'}';
}

_Case _case(
  String name, {
  String providerKey = 'osrm',
  String? secureApiKey,
  String legacyApiKey = '',
  String graphHopperServer = '',
  bool deferCredentialReadForOsrm = false,
}) =>
    (
      name: name,
      providerKey: providerKey,
      secureApiKey: secureApiKey,
      legacyApiKey: legacyApiKey,
      graphHopperServer: graphHopperServer,
      deferCredentialReadForOsrm: deferCredentialReadForOsrm,
    );

Iterable<_Case> _cases() sync* {
  yield _case(
    'maplibre-osrm-skips-all-credentials',
    secureApiKey: 'secret',
    legacyApiKey: 'legacy',
    graphHopperServer: 'https://stale.example/route',
    deferCredentialReadForOsrm: true,
  );
  yield _case('raster-osrm-reads-empty-credentials');
  yield _case(
    'raster-osrm-retains-secure-and-server',
    secureApiKey: ' key ',
    graphHopperServer: ' https://routing.example/route ',
  );
  yield _case(
    'raster-osrm-still-migrates-legacy-key',
    legacyApiKey: ' legacy ',
  );
  yield _case('unknown-provider-falls-back-to-osrm', providerKey: 'unknown');
  yield _case(
    'uppercase-osrm-is-unknown-and-reads-credentials',
    providerKey: 'OSRM',
    secureApiKey: 'key',
    deferCredentialReadForOsrm: true,
  );
  yield _case(
    'whitespace-provider-is-not-normalized',
    providerKey: ' osrm ',
    graphHopperServer: 'https://routing.example/route',
    deferCredentialReadForOsrm: true,
  );

  yield _case(
    'self-hosted-graphhopper-needs-only-server',
    providerKey: 'graphhopper',
    graphHopperServer: 'https://routing.example/route',
  );
  yield _case(
    'self-hosted-server-is-trimmed',
    providerKey: 'graphhopper',
    graphHopperServer: '  http://localhost:8989/route  ',
  );
  yield _case(
    'self-hosted-missing-server-falls-back',
    providerKey: 'graphhopper',
  );
  yield _case(
    'self-hosted-whitespace-server-is-missing',
    providerKey: 'graphhopper',
    graphHopperServer: '\t\n ',
  );
  yield _case(
    'self-hosted-retains-unneeded-secure-key',
    providerKey: 'graphhopper',
    secureApiKey: 'cloud-key',
    graphHopperServer: 'https://routing.example/route',
  );
  yield _case(
    'self-hosted-also-migrates-legacy-key',
    providerKey: 'graphhopper',
    legacyApiKey: ' old-key ',
    graphHopperServer: 'https://routing.example/route',
  );
  yield _case(
    'self-hosted-server-validation-remains-separate',
    providerKey: 'graphhopper',
    graphHopperServer: 'not a validated URL',
  );

  yield _case(
    'graphhopper-cloud-uses-secure-key',
    providerKey: 'graphhopper_public',
    secureApiKey: 'cloud-key',
  );
  yield _case(
    'graphhopper-cloud-trims-secure-key',
    providerKey: 'graphhopper_public',
    secureApiKey: '  cloud-key  ',
  );
  yield _case(
    'graphhopper-cloud-null-key-falls-back',
    providerKey: 'graphhopper_public',
  );
  yield _case(
    'graphhopper-cloud-empty-key-falls-back',
    providerKey: 'graphhopper_public',
    secureApiKey: '',
  );
  yield _case(
    'graphhopper-cloud-whitespace-key-blocks-legacy-migration',
    providerKey: 'graphhopper_public',
    secureApiKey: '   ',
    legacyApiKey: 'legacy-key',
  );
  yield _case(
    'graphhopper-cloud-null-key-migrates-trimmed-legacy',
    providerKey: 'graphhopper_public',
    legacyApiKey: '  legacy-key  ',
  );
  yield _case(
    'graphhopper-cloud-empty-key-migrates-legacy',
    providerKey: 'graphhopper_public',
    secureApiKey: '',
    legacyApiKey: 'legacy-key',
  );
  yield _case(
    'graphhopper-cloud-secure-key-wins-over-legacy',
    providerKey: 'graphhopper_public',
    secureApiKey: 'secure-key',
    legacyApiKey: 'legacy-key',
  );
  yield _case(
    'graphhopper-cloud-retains-stale-server-field',
    providerKey: 'graphhopper_public',
    secureApiKey: 'key',
    graphHopperServer: 'https://stale.example/route',
  );

  yield _case(
    'openroute-uses-secure-key',
    providerKey: 'openroute',
    secureApiKey: 'ors-key',
  );
  yield _case(
    'openroute-missing-key-falls-back',
    providerKey: 'openroute',
  );
  yield _case(
    'openroute-migrates-legacy-key',
    providerKey: 'openroute',
    legacyApiKey: ' legacy-ors ',
  );
  yield _case(
    'openroute-retains-unrelated-server-field',
    providerKey: 'openroute',
    secureApiKey: 'ors-key',
    graphHopperServer: 'https://stale.example/route',
  );

  yield _case(
    'unknown-provider-retains-read-values',
    providerKey: 'future-provider',
    secureApiKey: 'key',
    graphHopperServer: 'https://routing.example/route',
  );
  yield _case(
    'null-secure-and-empty-legacy-do-not-migrate',
    providerKey: 'graphhopper_public',
    secureApiKey: null,
    legacyApiKey: '',
  );
  yield _case(
    'empty-secure-and-whitespace-legacy-do-not-migrate',
    providerKey: 'graphhopper_public',
    secureApiKey: '',
    legacyApiKey: '\u00a0\u3000',
  );
  yield _case(
    'dart-bom-trim-applies-to-legacy-key',
    providerKey: 'graphhopper_public',
    legacyApiKey: '\ufefflegacy\ufeff',
  );
  yield _case(
    'dart-bom-only-secure-key-blocks-legacy-before-trim',
    providerKey: 'graphhopper_public',
    secureApiKey: '\ufeff',
    legacyApiKey: 'legacy',
  );
  yield _case(
    'dart-unicode-trim-applies-to-server',
    providerKey: 'graphhopper',
    graphHopperServer: '\u2003https://routing.example/route\u202f',
  );
  yield _case(
    'empty-secure-migrates-unicode-trimmed-key',
    providerKey: 'openroute',
    secureApiKey: '',
    legacyApiKey: '\u205fkey\u00a0',
  );
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildRoutingProviderConfigFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
