import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/search_orchestration_protocol.dart';
import 'package:roadstr/services/search_ranking_protocol.dart';
import 'package:roadstr/services/search_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/search_orchestration_v1.tsv';

typedef _Event = ({
  SearchProviderBatch batch,
  SearchProviderKind provider,
  List<NominatimResult> results,
});
typedef _Case = ({
  String name,
  String query,
  bool settled,
  LatLng? near,
  List<_Event> events,
});

String buildSearchOrchestrationFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_search_orchestration_fixture.dart.',
    '# name\tsettled\tnear_lat\tnear_lon\tquery_b64\tevents_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.name,
      value.settled ? '1' : '0',
      value.near?.latitude ?? '-',
      value.near?.longitude ?? '-',
      _encode(value.query),
      _encode(jsonEncode(value.events.map(_eventJson).toList())),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  final plan = SearchRankingProtocol.executionPlan(
    value.query,
    settled: value.settled,
    hasNear: value.near != null,
  )!;
  final state = SearchOrchestrationProtocol(plan: plan, near: value.near);
  final transcript = <String>[];
  for (var index = 0; index < value.events.length; index++) {
    final event = value.events[index];
    final decision = state.accept(event.batch, event.provider, event.results);
    transcript.add(_decision(index, decision, state.isCompleted));
  }
  return transcript.join('\n');
}

String _decision(
  int index,
  SearchOrchestrationDecision decision,
  bool completed,
) =>
    '$index:'
    'partial=${_ids(decision.partialResults)};'
    'retry=${decision.retryQuery ?? '-'};'
    'final=${_ids(decision.finalResults)};'
    'done=${completed ? 1 : 0}';

String _ids(List<NominatimResult>? values) =>
    values == null ? '-' : values.map((value) => value.shortName).join(',');

Map<String, Object?> _eventJson(_Event event) => {
      'batch': event.batch.name,
      'provider': event.provider.name,
      'results': event.results.map(_resultJson).toList(),
    };

Map<String, Object?> _resultJson(NominatimResult result) => {
      'display': result.displayName,
      'short': result.shortName,
      'lat': result.position.latitude,
      'lon': result.position.longitude,
      'city': result.city,
      'brand': result.brand,
    };

NominatimResult _r(
  String id, {
  double lat = 45,
  double lon = 9,
  String? city,
  String? brand,
}) =>
    NominatimResult(
      displayName: id,
      shortName: id,
      position: LatLng(lat, lon),
      city: city,
      brand: brand,
    );

_Event _initial(SearchProviderKind provider,
        [List<NominatimResult> results = const []]) =>
    (batch: SearchProviderBatch.initial, provider: provider, results: results);

_Event _retry(SearchProviderKind provider,
        [List<NominatimResult> results = const []]) =>
    (batch: SearchProviderBatch.retry, provider: provider, results: results);

_Case _case(
  String name, {
  String query = 'via roberto ricci',
  bool settled = true,
  LatLng? near,
  required List<_Event> events,
}) =>
    (
      name: name,
      query: query,
      settled: settled,
      near: near,
      events: events,
    );

Iterable<_Case> _cases() sync* {
  const near = LatLng(45, 9);
  final photon = _r('Photon', lat: 45.01, lon: 9.01);
  final nominatim = _r('Nominatim', lat: 45.02, lon: 9.02);
  final poi = _r('Poi', lat: 45.03, lon: 9.03);

  yield _case(
    'typeahead-no-near-hit',
    settled: false,
    events: [
      _initial(SearchProviderKind.photon, [photon])
    ],
  );
  yield _case(
    'typeahead-no-near-empty',
    settled: false,
    events: [_initial(SearchProviderKind.photon)],
  );
  yield _case(
    'typeahead-near-photon-first',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.poi, [poi]),
    ],
  );
  yield _case(
    'typeahead-near-poi-first',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.poi, [poi]),
      _initial(SearchProviderKind.photon, [photon]),
    ],
  );
  yield _case(
    'typeahead-empty-before-hit',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.photon),
      _initial(SearchProviderKind.poi, [poi]),
    ],
  );
  yield _case(
    'settled-no-near-nominatim-first',
    events: [
      _initial(SearchProviderKind.nominatim, [nominatim]),
      _initial(SearchProviderKind.photon, [photon]),
    ],
  );
  yield _case(
    'settled-no-near-photon-first',
    events: [
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.nominatim, [nominatim]),
    ],
  );
  yield _case(
    'settled-near-poi-precedence',
    near: near,
    events: [
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.nominatim, [nominatim]),
      _initial(SearchProviderKind.poi, [poi]),
    ],
  );
  yield _case(
    'partial-provider-results-are-ranked',
    query: 'via roma',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.photon, [
        _r('Via Roma Far', lat: 46, lon: 10),
        _r('Via Roma Near', lat: 45.001, lon: 9.001),
      ]),
      _initial(SearchProviderKind.poi),
    ],
  );
  yield _case(
    'nominatim-wins-cross-provider-duplicate',
    query: 'same place',
    events: [
      _initial(SearchProviderKind.photon, [_r('Photon Copy')]),
      _initial(
        SearchProviderKind.nominatim,
        [_r('Nominatim Copy', lat: 45.00001, lon: 9.00001)],
      ),
    ],
  );
  yield _case(
    'poi-suppresses-nearby-geocoder-copy',
    query: 'pharmacy',
    near: near,
    events: [
      _initial(SearchProviderKind.photon, [_r('Geo Pharmacy')]),
      _initial(SearchProviderKind.nominatim),
      _initial(
        SearchProviderKind.poi,
        [_r('Poi Pharmacy', lat: 45.00001, lon: 9.00001)],
      ),
    ],
  );
  yield _case(
    'two-word-empty-has-no-retry',
    query: 'via ricci',
    events: [
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
    ],
  );
  yield _case(
    'poi-hit-suppresses-retry',
    near: near,
    events: [
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
      _initial(SearchProviderKind.poi, [poi]),
    ],
  );
  yield _case(
    'geocoder-hit-suppresses-retry',
    near: near,
    events: [
      _initial(SearchProviderKind.poi),
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.nominatim),
    ],
  );
  yield _case(
    'typeahead-never-retries',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.photon),
      _initial(SearchProviderKind.poi),
    ],
  );
  yield _case(
    'retry-photon-hit',
    events: [
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
      _retry(SearchProviderKind.photon, [_r('Retry Photon')]),
      _retry(SearchProviderKind.nominatim),
    ],
  );
  yield _case(
    'retry-nominatim-hit',
    events: [
      _initial(SearchProviderKind.photon),
      _initial(SearchProviderKind.nominatim),
      _retry(SearchProviderKind.nominatim, [_r('Retry Nominatim')]),
      _retry(SearchProviderKind.photon),
    ],
  );
  yield _case(
    'retry-both-empty',
    events: [
      _initial(SearchProviderKind.photon),
      _initial(SearchProviderKind.nominatim),
      _retry(SearchProviderKind.nominatim),
      _retry(SearchProviderKind.photon),
    ],
  );
  yield _case(
    'retry-results-use-relaxed-query-ranking',
    near: near,
    events: [
      _initial(SearchProviderKind.poi),
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
      _retry(SearchProviderKind.photon, [
        _r('Via Ricci Far', lat: 46, lon: 10),
        _r('Via Ricci Near', lat: 45.001, lon: 9.001),
      ]),
      _retry(SearchProviderKind.nominatim),
    ],
  );

  final initialOrders = <List<SearchProviderKind>>[
    [
      SearchProviderKind.nominatim,
      SearchProviderKind.photon,
      SearchProviderKind.poi
    ],
    [
      SearchProviderKind.nominatim,
      SearchProviderKind.poi,
      SearchProviderKind.photon
    ],
    [
      SearchProviderKind.photon,
      SearchProviderKind.nominatim,
      SearchProviderKind.poi
    ],
    [
      SearchProviderKind.photon,
      SearchProviderKind.poi,
      SearchProviderKind.nominatim
    ],
    [
      SearchProviderKind.poi,
      SearchProviderKind.nominatim,
      SearchProviderKind.photon
    ],
    [
      SearchProviderKind.poi,
      SearchProviderKind.photon,
      SearchProviderKind.nominatim
    ],
  ];
  for (var i = 0; i < initialOrders.length; i++) {
    yield _case(
      'all-empty-order-$i',
      near: near,
      events: [
        for (final provider in initialOrders[i]) _initial(provider),
        if (i.isEven) ...[
          _retry(SearchProviderKind.nominatim),
          _retry(SearchProviderKind.photon),
        ] else ...[
          _retry(SearchProviderKind.photon),
          _retry(SearchProviderKind.nominatim),
        ],
      ],
    );
  }

  yield _case(
    'duplicate-initial-completion-is-ignored',
    settled: false,
    near: near,
    events: [
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.photon, [_r('Duplicate')]),
      _initial(SearchProviderKind.poi),
    ],
  );
  yield _case(
    'disabled-initial-providers-are-ignored',
    settled: false,
    events: [
      _initial(SearchProviderKind.nominatim, [nominatim]),
      _initial(SearchProviderKind.poi, [poi]),
      _initial(SearchProviderKind.photon, [photon]),
    ],
  );
  yield _case(
    'retry-before-admission-is-ignored',
    events: [
      _retry(SearchProviderKind.photon, [_r('Too Early')]),
      _initial(SearchProviderKind.nominatim, [nominatim]),
      _initial(SearchProviderKind.photon),
    ],
  );
  yield _case(
    'poi-is-never-a-retry-provider',
    events: [
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
      _retry(SearchProviderKind.poi, [poi]),
      _retry(SearchProviderKind.photon),
      _retry(SearchProviderKind.nominatim),
    ],
  );
  yield _case(
    'duplicate-retry-completion-is-ignored',
    events: [
      _initial(SearchProviderKind.nominatim),
      _initial(SearchProviderKind.photon),
      _retry(SearchProviderKind.photon, [_r('First Retry')]),
      _retry(SearchProviderKind.photon, [_r('Duplicate Retry')]),
      _retry(SearchProviderKind.nominatim),
    ],
  );
  yield _case(
    'completion-after-final-is-ignored',
    settled: false,
    events: [
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.photon, [_r('Late')]),
      _retry(SearchProviderKind.nominatim, [_r('Late Retry')]),
    ],
  );
  yield _case(
    'partial-is-emitted-only-once',
    near: near,
    events: [
      _initial(SearchProviderKind.poi, [poi]),
      _initial(SearchProviderKind.photon, [photon]),
      _initial(SearchProviderKind.nominatim, [nominatim]),
    ],
  );
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> args) {
  final generated = buildSearchOrchestrationFixture();
  final file = File(outputPath);
  if (args.contains('--check')) {
    if (!file.existsSync() || file.readAsStringSync() != generated) {
      stderr.writeln('Stale fixture: $outputPath');
      exitCode = 1;
    }
    return;
  }
  file.writeAsStringSync(generated);
}
