import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/search_ranking_protocol.dart';
import 'package:roadstr/services/search_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/search_ranking_v1.tsv';

typedef _Case = ({
  String operation,
  String name,
  String query,
  bool settled,
  LatLng? near,
  List<NominatimResult> primary,
  List<NominatimResult> secondary,
});

String buildSearchRankingFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_search_ranking_fixture.dart.',
    '# operation\tname\tsettled\tnear_lat\tnear_lon\tquery_b64\tprimary_b64\tsecondary_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.operation,
      value.name,
      value.settled ? '1' : '0',
      value.near?.latitude ?? '-',
      value.near?.longitude ?? '-',
      _encode(value.query),
      _encode(jsonEncode(value.primary.map(_resultJson).toList())),
      _encode(jsonEncode(value.secondary.map(_resultJson).toList())),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  try {
    return switch (value.operation) {
      'plan' => _canonicalPlan(SearchRankingProtocol.executionPlan(
          value.query,
          settled: value.settled,
          hasNear: value.near != null,
        )),
      'relax' => _optional(SearchRankingProtocol.relaxQuery(value.query)),
      'match' => SearchRankingProtocol.matchScore(
          value.query,
          value.primary.single,
        ).toStringAsFixed(9),
      'dedupe' => _canonicalResults(
          SearchRankingProtocol.dedupeByProximity(value.primary),
        ),
      'rank' => _canonicalResults(SearchRankingProtocol.rankResults(
          value.query,
          value.primary,
          value.near,
        )),
      'rank_geo' => _canonicalResults(SearchRankingProtocol.rankGeocoders(
          value.query,
          value.primary,
          value.secondary,
          value.near,
        )),
      'merge_poi' => _canonicalResults(SearchRankingProtocol.mergePoiFirst(
          value.primary,
          value.secondary,
        )),
      'retry' => _optional(SearchRankingProtocol.relaxedRetryQuery(
          SearchRankingProtocol.executionPlan(
            value.query,
            settled: value.settled,
            hasNear: value.near != null,
          )!,
          value.primary,
          value.secondary,
        )),
      _ => throw StateError('Unknown operation ${value.operation}'),
    };
  } catch (_) {
    return 'error';
  }
}

String _canonicalPlan(SearchExecutionPlan? plan) => plan == null
    ? 'null'
    : [
        'query=${_encode(plan.query)}',
        'nominatim=${plan.useNominatim ? 1 : 0}',
        'photon=${plan.usePhoton ? 1 : 0}',
        'poi=${plan.usePoi ? 1 : 0}',
        'relax=${plan.allowRelaxedRetry ? 1 : 0}',
      ].join('\n');

String _canonicalResults(List<NominatimResult> results) => [
      'count=${results.length}',
      'items=${results.map(_canonicalResult).join(';')}',
    ].join('\n');

String _canonicalResult(NominatimResult result) => [
      _encode(result.displayName),
      _encode(result.shortName),
      result.position.latitude.toStringAsFixed(6),
      result.position.longitude.toStringAsFixed(6),
      _optional(result.cls),
      _optional(result.type),
      _optional(result.city),
      _optional(result.openingHours),
      result.distanceM?.toStringAsFixed(3) ?? '-',
      _optional(result.brand),
    ].join(',');

Map<String, Object?> _resultJson(NominatimResult result) => {
      'display': result.displayName,
      'short': result.shortName,
      'lat': result.position.latitude,
      'lon': result.position.longitude,
      'class': result.cls,
      'type': result.type,
      'city': result.city,
      'opening': result.openingHours,
      'distance': result.distanceM,
      'brand': result.brand,
    };

Iterable<_Case> _cases() sync* {
  const ravenna = LatLng(44.4184, 12.2035);
  const torino = LatLng(45.0703, 7.6869);

  yield _case('plan', 'empty-query', '   ', settled: true, near: ravenna);
  yield _case('plan', 'settled-near-trims', '  farmacia roma  ',
      settled: true, near: ravenna);
  yield _case('plan', 'typeahead-near', 'farm', settled: false, near: ravenna);
  yield _case('plan', 'settled-without-fix', 'Via Roma', settled: true);
  yield _case('plan', 'typeahead-without-fix', 'Via Ro', settled: false);
  yield _case('plan', 'caps-query-at-200', 'q' * 205,
      settled: true, near: ravenna);
  yield _case('plan', 'unicode-trim', '\u00a0\u2003Museo Torino\u3000',
      settled: true, near: torino);

  yield _case('relax', 'street-given-surname', 'via roberto ricci');
  yield _case('relax', 'five-words', 'piazza santa maria del fiore');
  yield _case('relax', 'two-words', 'via ricci');
  yield _case('relax', 'empty', '  ');
  yield _case('relax', 'irregular-spacing', '  corso   giuseppe   garibaldi ');
  yield _case('relax', 'unicode-spacing', 'via\u00a0roberto\u2003ricci');

  yield _case('match', 'street-label-with-city', 'via roberto ricci',
      primary: [_r('street', 'Via Roberto Ricci, Torino')]);
  yield _case('match', 'full-address-fallback', 'torino piemonte', primary: [
    _r(
      'full',
      'Via Ricci',
      display: 'Via Ricci, Torino, Piemonte, Italia',
    ),
  ]);
  yield _case('match', 'typo', 'via robberto ricc',
      primary: [_r('typo', 'Via Roberto Ricci, Torino')]);
  yield _case('match', 'accent-folding', 'citta castello',
      primary: [_r('accent', 'Città di Castello')]);
  yield _case('match', 'unrelated', 'via garibaldi',
      primary: [_r('other', 'Via Napoleone, Milano')]);
  yield _case('match', 'empty-query', '', primary: [_r('empty', 'Via Roma')]);

  yield _case('dedupe', 'empty', '');
  yield _case('dedupe', 'near-copy-first-wins', '', primary: [
    _r('first', 'Via Ricci, Torino', lat: 45.07000, lon: 7.68000),
    _r('copy', 'Via Ricci', lat: 45.07005, lon: 7.68005),
  ]);
  yield _case('dedupe', 'far-apart', '', primary: [
    _r('torino', 'Via Ricci, Torino', lat: 45.07, lon: 7.68),
    _r('cesena', 'Via Ricci, Cesena', lat: 44.14, lon: 12.24),
  ]);
  yield _case('dedupe', 'rounded-under-threshold', '', primary: [
    _r('origin', 'Origin', lat: 45, lon: 9),
    _r('under', 'Under', lat: 45.00025, lon: 9),
  ]);
  yield _case('dedupe', 'rounded-over-threshold', '', primary: [
    _r('origin', 'Origin', lat: 45, lon: 9),
    _r('over', 'Over', lat: 45.00029, lon: 9),
  ]);
  yield _case('dedupe', 'non-transitive-first-kept', '', primary: [
    _r('a', 'A', lat: 45, lon: 9),
    _r('b', 'B', lat: 45.00022, lon: 9),
    _r('c', 'C', lat: 45.00044, lon: 9),
  ]);

  yield _case('rank', 'street-omitted-given-name', 'via roberto ricci',
      primary: [
        _r('wrong', 'Via Roberto Baldini, Torino', lat: 45.08, lon: 7.69),
        _r('right', 'Via Ricci, Torino', lat: 45.09, lon: 7.70),
      ]);
  yield _case('rank', 'typo', 'via robberto ricc', primary: [
    _r('wrong', 'Via Fabbri Roberto, Torino', lat: 45.08, lon: 7.69),
    _r('right', 'Via Roberto Ricci, Torino', lat: 45.09, lon: 7.70),
  ]);
  yield _case('rank', 'confident-distance', 'via roma', near: torino, primary: [
    _r('milano', 'Via Roma, Milano', lat: 45.46, lon: 9.19),
    _r('torino', 'Via Roma, Torino', lat: 45.08, lon: 7.68),
  ]);
  yield _case('rank', 'brand-confidence', 'mercatino usato',
      near: ravenna,
      primary: [
        _r('generic', 'Mercatino delle Pulci', lat: 44.41, lon: 12.21),
        _r('brand', 'Il Mercatino di Paolo',
            lat: 44.30, lon: 11.90, brand: "Mercatino dell'Usato"),
      ]);
  yield _case('rank', 'named-city-one-word', 'mercatino usato faenza',
      near: ravenna,
      primary: [
        _r('near', 'Mercatino Usato Ravenna',
            lat: 44.41, lon: 12.20, city: 'Ravenna'),
        _r('city', 'Mercatino Usato Faenza',
            lat: 44.29, lon: 11.88, city: 'Faenza'),
      ]);
  yield _case('rank', 'named-city-two-words', 'libreria reggio emilia',
      near: ravenna,
      primary: [
        _r('near', 'Libreria Ravenna', lat: 44.42, lon: 12.20, city: 'Ravenna'),
        _r('city', 'Libreria Ariosto',
            lat: 44.70, lon: 10.63, city: 'Reggio Emilia'),
      ]);
  yield _case('rank', 'named-city-three-words', 'hotel citta di castello',
      near: ravenna,
      primary: [
        _r('near', 'Hotel Ravenna', lat: 44.42, lon: 12.20, city: 'Ravenna'),
        _r('city', 'Hotel Tiferno',
            lat: 43.46, lon: 12.24, city: 'Città di Castello'),
      ]);
  yield _case(
      'rank', 'unknown-city-not-invented', 'mercatino usato nowhereville',
      near: ravenna,
      primary: [
        _r('near', 'Mercatino Usato A',
            lat: 44.41, lon: 12.20, city: 'Ravenna'),
        _r('far', 'Mercatino Usato B', lat: 44.29, lon: 11.88, city: 'Faenza'),
      ]);
  yield _case('rank', 'confident-before-closer-weak', 'farmacia',
      near: torino,
      primary: [
        _r('weak', 'Bar Centrale', lat: 45.071, lon: 7.687),
        _r('match', 'Farmacia Comunale', lat: 45.09, lon: 7.70),
      ]);
  yield _case('rank', 'weak-score-bands', 'museo arte moderna',
      near: torino,
      primary: [
        _r('low', 'Galleria Storica', lat: 45.071, lon: 7.687),
        _r('higher', 'Museo Civico', lat: 45.09, lon: 7.70),
      ]);
  yield _case('rank', 'weak-same-band-distance', 'centro culturale',
      near: torino,
      primary: [
        _r('far', 'Centro Congressi', lat: 45.15, lon: 7.75),
        _r('near', 'Centro Sportivo', lat: 45.071, lon: 7.687),
      ]);
  yield _case('rank', 'city-only-effective-query', 'faenza',
      near: ravenna,
      primary: [
        _r('near', 'Ravenna', lat: 44.42, lon: 12.20, city: 'Ravenna'),
        _r('city', 'Faenza', lat: 44.29, lon: 11.88, city: 'Faenza'),
      ]);
  yield _case('rank', 'single-untouched', 'anything',
      primary: [_r('one', 'Via Roma')]);
  yield _case('rank', 'caps-at-ten', 'farmacia', near: torino, primary: [
    for (var index = 0; index < 14; index++)
      _r(
        'pharmacy-$index',
        'Farmacia $index',
        lat: 45.071 + index * 0.002,
        lon: 7.687,
      ),
  ]);
  yield _case('rank', 'full-address-breaks-weak-tie', 'piemonte torino',
      primary: [
        _r('plain', 'Via Uno', display: 'Via Uno, Italia'),
        _r('full', 'Via Due', display: 'Via Due, Torino, Piemonte, Italia'),
      ]);

  yield _case('rank_geo', 'nominatim-duplicate-wins', 'via roma',
      near: torino,
      primary: [
        _r('nominatim', 'Via Roma, Torino', lat: 45.0700, lon: 7.6800),
      ],
      secondary: [
        _r('photon-copy', 'Via Roma', lat: 45.07005, lon: 7.68005),
      ]);
  yield _case(
      'rank_geo', 'provider-order-does-not-beat-ranking', 'via roberto ricci',
      primary: [
        _r('nominatim-wrong', 'Via Roberto Baldini, Torino'),
      ],
      secondary: [
        _r('photon-right', 'Via Ricci, Torino', lat: 45.1, lon: 7.7),
      ]);
  yield _case('rank_geo', 'empty-provider-safe', 'museum',
      near: torino,
      secondary: [
        _r('photon', 'Museum', lat: 45.08, lon: 7.69),
      ]);

  yield _case('merge_poi', 'empty-poi', '', secondary: [
    _r('geo', 'Via Roma'),
  ]);
  yield _case('merge_poi', 'poi-leads', '', primary: [
    _r('poi', 'Farmacia', lat: 45, lon: 9),
  ], secondary: [
    _r('geo', 'Via Roma', lat: 46, lon: 10),
  ]);
  yield _case('merge_poi', 'near-geo-copy-suppressed', '', primary: [
    _r('poi', 'Farmacia Centrale', lat: 45, lon: 9),
  ], secondary: [
    _r('copy', 'Farmacia', lat: 45.00005, lon: 9.00005),
    _r('far', 'Via Roma', lat: 45.01, lon: 9.01),
  ]);
  yield _case('merge_poi', 'over-threshold-geo-kept', '', primary: [
    _r('poi', 'Origin', lat: 45, lon: 9),
  ], secondary: [
    _r('geo', 'Other', lat: 45.00029, lon: 9),
  ]);
  yield _case('merge_poi', 'duplicates-among-poi-are-preserved', '', primary: [
    _r('poi-a', 'A', lat: 45, lon: 9),
    _r('poi-b', 'B', lat: 45.00005, lon: 9),
  ]);

  yield _case('retry', 'settled-empty-relaxes', 'via roberto ricci',
      settled: true, near: torino);
  yield _case('retry', 'typeahead-never-relaxes', 'via roberto ricci',
      settled: false, near: torino);
  yield _case('retry', 'geo-result-blocks-retry', 'via roberto ricci',
      settled: true, near: torino, primary: [_r('geo', 'Via Ricci')]);
  yield _case('retry', 'poi-result-blocks-retry', 'via roberto ricci',
      settled: true, near: torino, secondary: [_r('poi', 'Ricci')]);
  yield _case('retry', 'short-query-has-no-fallback', 'via ricci',
      settled: true, near: torino);
}

_Case _case(
  String operation,
  String name,
  String query, {
  bool settled = true,
  LatLng? near,
  List<NominatimResult> primary = const [],
  List<NominatimResult> secondary = const [],
}) =>
    (
      operation: operation,
      name: name,
      query: query,
      settled: settled,
      near: near,
      primary: primary,
      secondary: secondary,
    );

NominatimResult _r(
  String id,
  String shortName, {
  String? display,
  double lat = 44.4,
  double lon = 12.2,
  String? cls,
  String? type,
  String? city,
  String? openingHours,
  double? distanceM,
  String? brand,
}) =>
    NominatimResult(
      displayName: display ?? '$shortName [$id]',
      shortName: shortName,
      position: LatLng(lat, lon),
      cls: cls,
      type: type,
      city: city,
      openingHours: openingHours,
      distanceM: distanceM,
      brand: brand,
    );

String _optional(String? value) => value == null ? '-' : _encode(value);

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildSearchRankingFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
