import 'dart:io';

import 'package:bech32/bech32.dart';
import 'package:nostr_tools/nostr_tools.dart' show Nip19;
import 'package:roadstr/services/nostr_nip19.dart';

const outputPath = 'android/app/src/test/resources/parity/nostr_nip19_v1.tsv';

String _oracleEncode(NostrNip19Kind kind, String hex) => switch (kind) {
      NostrNip19Kind.publicKey => Nip19().npubEncode(hex),
      NostrNip19Kind.privateKey => Nip19().nsecEncode(hex),
    };

String _encode(NostrNip19Kind kind, String hex) => switch (kind) {
      NostrNip19Kind.publicKey => NostrNip19.encodePublicKey(hex),
      NostrNip19Kind.privateKey => NostrNip19.encodePrivateKey(hex),
    };

String _brokenChecksum(String value) {
  final replacement = value.endsWith('q') ? 'p' : 'q';
  return '${value.substring(0, value.length - 1)}$replacement';
}

String _invalidPadding(String value) {
  final decoded = const Bech32Codec().decode(value);
  final words = decoded.data.toList();
  words[words.length - 1] ^= 1;
  return const Bech32Codec().encode(Bech32(decoded.hrp, words));
}

String _tryEncode(NostrNip19Kind kind, String hex) {
  try {
    return _encode(kind, hex);
  } catch (_) {
    return 'reject';
  }
}

({String outcome, String hex}) _tryDecode(String encoded) {
  try {
    final decoded = NostrNip19.decode(encoded);
    return (outcome: decoded.kind.hrp, hex: decoded.hex);
  } catch (_) {
    return (outcome: 'reject', hex: '-');
  }
}

Future<String> buildNip19Fixture() async {
  final keys = <String, String>{
    'zero': '00' * 32,
    'ones': '11' * 32,
    'incrementing': [
      for (var value = 0; value < 32; value++)
        value.toRadixString(16).padLeft(2, '0'),
    ].join(),
    'max': 'ff' * 32,
  };
  final lines = <String>[
    '# Roadstr NIP-19 fixed-size key fixture v1.',
    '# Generated by tools/kotlin_rewrite/generate_nostr_nip19_fixture.dart.',
  ];

  for (final entry in keys.entries) {
    for (final kind in NostrNip19Kind.values) {
      final encoded = _encode(kind, entry.value);
      final oracle = _oracleEncode(kind, entry.value);
      if (encoded != oracle) {
        throw StateError('NIP-19 oracle mismatch for ${entry.key}/${kind.hrp}');
      }
      final oracleDecoded = Nip19().decode(encoded);
      if (oracleDecoded['type'] != kind.hrp ||
          oracleDecoded['data'] != entry.value) {
        throw StateError('NIP-19 oracle decode mismatch for ${entry.key}');
      }
      lines.add([
        'encode',
        '${entry.key}-${kind.hrp}',
        kind.hrp,
        entry.value,
        encoded,
      ].join('\t'));
      lines.add([
        'decode',
        '${entry.key}-${kind.hrp}-lower',
        encoded,
        kind.hrp,
        entry.value,
      ].join('\t'));
    }
  }

  final upperHex = keys['incrementing']!.toUpperCase();
  for (final kind in NostrNip19Kind.values) {
    lines.add([
      'encode',
      'uppercase-hex-${kind.hrp}',
      kind.hrp,
      upperHex,
      _encode(kind, upperHex),
    ].join('\t'));
    final encoded = _encode(kind, keys['incrementing']!);
    lines.add([
      'decode',
      'uppercase-bech32-${kind.hrp}',
      encoded.toUpperCase(),
      kind.hrp,
      keys['incrementing']!,
    ].join('\t'));
  }

  final publicKey = _encode(NostrNip19Kind.publicKey, keys['incrementing']!);
  final invalidDecode = <String, String>{
    'mixed-case': 'N${publicKey.substring(1)}',
    'wrong-checksum': _brokenChecksum(publicKey),
    'wrong-prefix': Nip19().noteEncode(keys['incrementing']!),
    'short-payload': Nip19().npubEncode('00' * 31),
    'long-payload': Nip19().npubEncode('00' * 33),
    'invalid-padding': _invalidPadding(publicKey),
    'missing-separator': publicKey.replaceFirst('1', ''),
    'invalid-character':
        '${publicKey.substring(0, 10)}!${publicKey.substring(11)}',
    'leading-space': ' $publicKey',
    'over-basic-limit': '${publicKey}qqqqqqqqqqqqqqqqqqqqqqqqqqqq',
    'empty-payload': const Bech32Codec().encode(Bech32('npub', const [])),
  };
  for (final entry in invalidDecode.entries) {
    final decoded = _tryDecode(entry.value);
    lines.add([
      'decode',
      entry.key,
      entry.value,
      decoded.outcome,
      decoded.hex,
    ].join('\t'));
  }

  final invalidEncode = <String, String>{
    'short-hex': '00' * 31,
    'long-hex': '00' * 33,
    'non-hex': '${'00' * 31}gg',
    'empty-hex': '',
  };
  for (final entry in invalidEncode.entries) {
    lines.add([
      'encode',
      entry.key,
      'npub',
      entry.value.isEmpty ? '-' : entry.value,
      _tryEncode(NostrNip19Kind.publicKey, entry.value),
    ].join('\t'));
  }

  return '${lines.join('\n')}\n';
}

Future<void> main(List<String> arguments) async {
  final generated = await buildNip19Fixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
