import 'dart:convert';
import 'dart:io';

import 'package:nostr_tools/nostr_tools.dart';
import 'package:roadstr/services/nostr_protocol_codec.dart';

const outputPath =
    'android/app/src/test/resources/parity/nostr_protocol_v1.tsv';

const categories = <({String name, String key, int ttl})>[
  (name: 'police', key: 'police', ttl: 4 * 3600),
  (name: 'policeStation', key: 'police_station', ttl: 30 * 86400),
  (name: 'speedCamera', key: 'speed_camera', ttl: 30 * 86400),
  (name: 'trafficJam', key: 'traffic_jam', ttl: 1 * 3600),
  (name: 'accident', key: 'accident', ttl: 4 * 3600),
  (name: 'roadClosure', key: 'road_closure', ttl: 24 * 3600),
  (name: 'construction', key: 'construction', ttl: 15 * 86400),
  (name: 'hazard', key: 'hazard', ttl: 4 * 3600),
  (name: 'roadCondition', key: 'road_condition', ttl: 15 * 86400),
  (name: 'pothole', key: 'pothole', ttl: 7 * 86400),
  (name: 'fog', key: 'fog', ttl: 4 * 3600),
  (name: 'ice', key: 'ice', ttl: 4 * 3600),
  (name: 'animal', key: 'animal', ttl: 1 * 3600),
  (name: 'other', key: 'other', ttl: 4 * 3600),
];

String b64(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

String encodeTags(List<List<String>> tags) =>
    tags.map((tag) => tag.map(b64).join('.')).join(',');

String eventSuffix(NostrEventDraft draft) {
  final oracle = Event(
    pubkey: draft.pubkey,
    created_at: draft.createdAt,
    kind: draft.kind,
    tags: draft.tags.map((tag) => tag.toList()).toList(),
    content: draft.content,
  );
  final oracleId = EventApi().getEventHash(oracle);
  if (oracleId != draft.id) {
    throw StateError('codec disagrees with nostr_tools for kind ${draft.kind}');
  }
  return '${b64(draft.canonicalJson)}\t${draft.id}';
}

String buildFixture() {
  final pubkey = List.filled(64, '1').join();
  final owner = List.filled(64, '3').join();
  final requester = List.filled(64, '4').join();
  final target = List.filled(64, '2').join();
  final requestId = List.filled(64, '5').join();
  final signature = List.filled(128, 'a').join();
  final locations = <(double, double)>[
    (41.9028, 12.4964),
    (-33.8688, 151.2093),
    (37.7749, -122.4194),
    (-0.0, 0.0),
    (1.2345675, -1.2345675),
    (89.999999, -179.999999),
  ];
  final drafts = <String, NostrEventDraft>{};
  final lines = <String>[
    '# Roadstr Nostr deterministic protocol fixture v1.',
    '# Text, canonical JSON and complete wire frames use unpadded base64url.',
    '# Generated by tools/kotlin_rewrite/generate_nostr_protocol_fixture.dart.',
  ];

  for (final category in categories) {
    lines.add(
      'category\t${category.name}\t${category.key}\t${category.ttl}',
    );
  }

  for (var index = 0; index < categories.length; index++) {
    final category = categories[index];
    final location = locations[index % locations.length];
    final createdAt = 1700000000 + index;
    final expiresAt = createdAt + category.ttl;
    final speedLimit = category.name == 'speedCamera' ? 90 : null;
    final content = '${category.key}: café — strada ${index + 1}';
    final id = 'report-${category.name}';
    final draft = RoadstrNostrEvents.report(
      pubkey: pubkey,
      createdAt: createdAt,
      latitude: location.$1,
      longitude: location.$2,
      category: category.key,
      expiresAt: expiresAt,
      content: content,
      speedLimit: speedLimit,
    );
    drafts[id] = draft;
    lines.add([
      'report',
      id,
      pubkey,
      '$createdAt',
      '${location.$1}',
      '${location.$2}',
      category.key,
      '$expiresAt',
      speedLimit?.toString() ?? '-',
      b64(content),
      eventSuffix(draft),
    ].join('\t'));
  }

  for (final stillThere in [true, false]) {
    final id = stillThere ? 'vote-still-there' : 'vote-gone';
    final draft = RoadstrNostrEvents.vote(
      pubkey: requester,
      createdAt: stillThere ? 1700000200 : 1700000201,
      eventId: target,
      stillThere: stillThere,
    );
    drafts[id] = draft;
    lines.add([
      'vote',
      id,
      requester,
      '${draft.createdAt}',
      target,
      '$stillThere',
      eventSuffix(draft),
    ].join('\t'));
  }

  for (final withRequest in [false, true]) {
    final id = withRequest ? 'update-with-request' : 'update-direct';
    final content = withRequest ? 'limite corretto "ora"\nverificato' : '';
    final draft = RoadstrNostrEvents.update(
      ownerPubkey: owner,
      createdAt: withRequest ? 1700000301 : 1700000300,
      eventId: target,
      speedLimit: withRequest ? 110 : 50,
      latitude: 45.4642,
      longitude: 9.1900,
      content: content,
      requestId: withRequest ? requestId : null,
    );
    drafts[id] = draft;
    lines.add([
      'update',
      id,
      owner,
      '${draft.createdAt}',
      target,
      withRequest ? '110' : '50',
      '45.4642',
      '9.19',
      withRequest ? requestId : '-',
      b64(content),
      eventSuffix(draft),
    ].join('\t'));
  }

  final edit = RoadstrNostrEvents.editRequest(
    requesterPubkey: requester,
    ownerPubkey: owner,
    createdAt: 1700000400,
    eventId: target,
    speedLimit: 130,
    latitude: -22.9068,
    longitude: -43.1729,
  );
  drafts['edit-request'] = edit;
  lines.add([
    'edit',
    'edit-request',
    requester,
    owner,
    '${edit.createdAt}',
    target,
    '130',
    '-22.9068',
    '-43.1729',
    eventSuffix(edit),
  ].join('\t'));

  for (final isPublic in [false, true]) {
    final id = isPublic ? 'profile-public' : 'profile-private';
    final draft = RoadstrNostrEvents.profileVisibility(
      pubkey: pubkey,
      createdAt: isPublic ? 1700000501 : 1700000500,
      isPublic: isPublic,
    );
    drafts[id] = draft;
    lines.add([
      'profile',
      id,
      pubkey,
      '${draft.createdAt}',
      '$isPublic',
      eventSuffix(draft),
    ].join('\t'));
  }

  final escaping = NostrEventDraft(
    pubkey: pubkey,
    createdAt: 1700000600,
    kind: 1,
    tags: [
      ['client', 'roadstr'],
      ['quoted', 'quote" slash/ backslash\\ line\n\t\b\f\r'],
      ['unicode', 'café', '😀', 'x y z'],
      ['control', '\u0000\u001f'],
    ],
    content:
        'Unicode 🛣️; controls:\u0000\u001f; quote:"; slash:/; backslash:\\',
  );
  drafts['json-escaping'] = escaping;
  lines.add([
    'event',
    'json-escaping',
    pubkey,
    '${escaping.createdAt}',
    '${escaping.kind}',
    encodeTags(escaping.tags),
    b64(escaping.content),
    eventSuffix(escaping),
  ].join('\t'));

  final published = drafts['report-speedCamera']!;
  lines.add([
    'wire-publish',
    'publish-report',
    'report-speedCamera',
    signature,
    b64(NostrRelayWire.encode(
      NostrRelayWire.publish(published.toJson(signature: signature)),
    )),
  ].join('\t'));

  const wireNow = 1700001000;
  lines.add([
    'wire-area',
    'area-request',
    '0123456789abcdef',
    '$wireNow',
    'sr2y',
    b64(NostrRelayWire.encode(NostrRelayWire.areaRequest(
      subscriptionId: '0123456789abcdef',
      geohashes: const ['sr2y'],
      now: wireNow,
    ))),
  ].join('\t'));
  lines.add([
    'wire-confirmations',
    'confirmation-request',
    'fedcba9876543210',
    '$wireNow',
    '$target,${drafts['report-police']!.id}',
    b64(NostrRelayWire.encode(NostrRelayWire.confirmationRequest(
      subscriptionId: 'fedcba9876543210',
      eventIds: [target, drafts['report-police']!.id],
      now: wireNow,
    ))),
  ].join('\t'));
  lines.add([
    'wire-close',
    'close-request',
    '0123456789abcdef',
    b64(NostrRelayWire.encode(
      NostrRelayWire.close('0123456789abcdef'),
    )),
  ].join('\t'));

  return '${lines.join('\n')}\n';
}

void main(List<String> arguments) {
  final generated = buildFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
