import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/routing_avoidance_protocol.dart';
import 'package:roadstr/services/routing_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/routing_avoidance_v1.tsv';

typedef _Case = ({String operation, String name, Map<String, Object?> input});

String buildRoutingAvoidanceFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_routing_avoidance_fixture.dart.',
    '# operation\tname\tinput_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.operation,
      value.name,
      _encode(jsonEncode(value.input)),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) => switch (value.operation) {
      'orchestration' => _evaluateOrchestration(value.input),
      'retime' => _evaluateRetime(value.input),
      _ => throw StateError('Unknown operation ${value.operation}'),
    };

String _evaluateOrchestration(Map<String, Object?> input) {
  final mode = RoutingAvoidanceMode.values.byName(input['mode']! as String);
  final state = RoutingAvoidanceProtocol(mode);
  final transcript = <String>['initial=${state.initialAttempt.name}'];
  final events = input['events']! as List<Map<String, Object?>>;
  for (var index = 0; index < events.length; index++) {
    final event = events[index];
    final routeId = (event['route'] as num?)?.toDouble();
    final decision = state.accept(
      RoutingAvoidanceAttempt.values.byName(event['attempt']! as String),
      RoutingAvoidanceAttemptOutcome.values.byName(event['outcome']! as String),
      routeId == null ? null : _route(const [LatLng(0, 0)], routeId: routeId),
    );
    transcript.add('$index:'
        'next=${decision.nextAttempt?.name ?? '-'};'
        'final=${decision.finalRoute?.totalDistanceM.toStringAsFixed(0) ?? '-'};'
        'propagate=${decision.propagateFailure ? 1 : 0};'
        'done=${state.isCompleted ? 1 : 0}');
  }
  return transcript.join('\n');
}

String _evaluateRetime(Map<String, Object?> input) {
  final points = (input['points']! as List<Object?>).map((raw) {
    final pair = raw as List<Object?>;
    return LatLng((pair[0] as num).toDouble(), (pair[1] as num).toDouble());
  }).toList();
  final route = _route(
    points,
    routeId: (input['distance'] as num).toDouble(),
    durationS: (input['duration'] as num).toDouble(),
    avoidance: RouteAvoidance.values.byName(input['avoidance']! as String),
    fromAvoidanceRouter: input['fromAvoidance']! as bool,
  );
  final rawLegs = input['legs'] as List<Object?>?;
  final legs = rawLegs?.map((raw) {
    final leg = raw as Map<String, Object?>;
    return OsrmRetimeLeg(
      distanceM: (leg['distance'] as num?)?.toDouble(),
      durationS: (leg['duration'] as num?)?.toDouble(),
    );
  }).toList();
  final plan = RoutingRetimePolicy.buildPlan(route);
  final result =
      plan == null ? route : RoutingRetimePolicy.apply(route, plan, legs);
  final canonicalPlan = plan == null
      ? 'plan=-'
      : 'plan=samples=${plan.sampleIndices.length};'
          'indices=${plan.sampleIndices.join(',')};'
          'shape=${plan.shapeLengthM.toStringAsFixed(3)};'
          'crossings=${plan.seaCrossings.join(',')};'
          'waypoints=${plan.waypoints}';
  return '$canonicalPlan\n'
      'result=duration=${result.totalDurationS.toStringAsFixed(3)};'
      'distance=${result.totalDistanceM.toStringAsFixed(3)};'
      'avoidance=${result.avoidance.name};'
      'retimed=${result.fromAvoidanceRouter ? 1 : 0}';
}

RouteResult _route(
  List<LatLng> points, {
  required double routeId,
  double durationS = 300,
  RouteAvoidance avoidance = RouteAvoidance.highwayAndTollFree,
  bool fromAvoidanceRouter = false,
}) =>
    RouteResult(
      polyline: points,
      steps: const [],
      totalDistanceM: routeId,
      totalDurationS: durationS,
      avoidance: avoidance,
      fromAvoidanceRouter: fromAvoidanceRouter,
    );

Map<String, Object?> _event(
  RoutingAvoidanceAttempt attempt,
  RoutingAvoidanceAttemptOutcome outcome, {
  double? route,
}) =>
    {'attempt': attempt.name, 'outcome': outcome.name, 'route': route};

_Case _orchestration(
  String name,
  RoutingAvoidanceMode mode,
  List<Map<String, Object?>> events,
) =>
    (
      operation: 'orchestration',
      name: name,
      input: {'mode': mode.name, 'events': events},
    );

List<LatLng> _line(List<double> segmentLengthsM) {
  final result = <LatLng>[const LatLng(0, 0)];
  var longitude = 0.0;
  for (final metres in segmentLengthsM) {
    longitude += metres / 111320.0;
    result.add(LatLng(0, longitude));
  }
  return result;
}

Map<String, Object?> _leg(double? distanceM, double? durationS) =>
    {'distance': distanceM, 'duration': durationS};

_Case _retime(
  String name, {
  required List<LatLng> points,
  double distanceM = 3000,
  double durationS = 300,
  RouteAvoidance avoidance = RouteAvoidance.highwayAndTollFree,
  bool fromAvoidanceRouter = false,
  List<Map<String, Object?>>? legs,
}) =>
    (
      operation: 'retime',
      name: name,
      input: {
        'points': [
          for (final point in points) [point.latitude, point.longitude],
        ],
        'distance': distanceM,
        'duration': durationS,
        'avoidance': avoidance.name,
        'fromAvoidance': fromAvoidanceRouter,
        'legs': legs,
      },
    );

Iterable<_Case> _cases() sync* {
  yield _orchestration(
    'hard-success-is-terminal',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(
          RoutingAvoidanceAttempt.hard, RoutingAvoidanceAttemptOutcome.success,
          route: 101)
    ],
  );
  yield _orchestration(
    'hard-failure-retries-soft',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(
          RoutingAvoidanceAttempt.soft, RoutingAvoidanceAttemptOutcome.success,
          route: 202),
    ],
  );
  yield _orchestration(
    'soft-failure-propagates',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(RoutingAvoidanceAttempt.soft,
          RoutingAvoidanceAttemptOutcome.routingFailure),
    ],
  );
  yield _orchestration(
    'tracks-success-is-terminal',
    RoutingAvoidanceMode.offRoad,
    [
      _event(RoutingAvoidanceAttempt.tracks,
          RoutingAvoidanceAttemptOutcome.success,
          route: 303)
    ],
  );
  yield _orchestration(
    'tracks-failure-propagates',
    RoutingAvoidanceMode.offRoad,
    [
      _event(RoutingAvoidanceAttempt.tracks,
          RoutingAvoidanceAttemptOutcome.routingFailure)
    ],
  );
  yield _orchestration(
    'premature-soft-is-ignored',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(
          RoutingAvoidanceAttempt.soft, RoutingAvoidanceAttemptOutcome.success,
          route: 999),
      _event(
          RoutingAvoidanceAttempt.hard, RoutingAvoidanceAttemptOutcome.success,
          route: 104),
    ],
  );
  yield _orchestration(
    'duplicate-hard-after-retry-is-ignored',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(
          RoutingAvoidanceAttempt.hard, RoutingAvoidanceAttemptOutcome.success,
          route: 999),
      _event(
          RoutingAvoidanceAttempt.soft, RoutingAvoidanceAttemptOutcome.success,
          route: 205),
    ],
  );
  yield _orchestration(
    'late-soft-after-hard-success-is-ignored',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(
          RoutingAvoidanceAttempt.hard, RoutingAvoidanceAttemptOutcome.success,
          route: 106),
      _event(
          RoutingAvoidanceAttempt.soft, RoutingAvoidanceAttemptOutcome.success,
          route: 999),
    ],
  );
  yield _orchestration(
    'hard-event-for-tracks-is-ignored',
    RoutingAvoidanceMode.offRoad,
    [
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(RoutingAvoidanceAttempt.tracks,
          RoutingAvoidanceAttemptOutcome.success,
          route: 307),
    ],
  );
  yield _orchestration(
    'duplicate-hard-failure-cannot-skip-soft',
    RoutingAvoidanceMode.highwaysAndTolls,
    [
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(RoutingAvoidanceAttempt.hard,
          RoutingAvoidanceAttemptOutcome.routingFailure),
      _event(RoutingAvoidanceAttempt.soft,
          RoutingAvoidanceAttemptOutcome.routingFailure),
    ],
  );

  yield _retime('one-point-has-no-plan', points: const [LatLng(0, 0)]);
  yield _retime('nonpositive-route-distance-has-no-plan',
      points: _line([1000]), distanceM: 0);
  yield _retime('coincident-shape-has-no-plan',
      points: const [LatLng(1, 1), LatLng(1, 1)]);
  yield _retime('minimum-four-waypoints', points: _line([1000, 1000, 1000]));
  yield _retime('two-points-duplicate-sample-indices',
      points: _line([1000]), distanceM: 1000);
  yield _retime('exact-road-step-is-not-ferry',
      points: _line([25000]), distanceM: 25000);
  yield _retime('over-road-step-is-ferry',
      points: _line([25000.01]), distanceM: 25000.01);
  yield _retime('half-up-sample-rounding',
      points: _line(List.filled(7, 2500)), distanceM: 17500);
  yield _retime('waypoint-rounding-preserves-negative-zero',
      points: const [
        LatLng(-0.0000049, -0.0000049),
        LatLng(0.00123456, 0.00123456)
      ],
      distanceM: 200);
  yield _retime('waypoint-count-is-capped',
      points: _line(List.filled(125, 5000)), distanceM: 625000);

  yield _retime(
    'all-matching-legs-are-retimed',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40), _leg(1000, 50), _leg(1000, 60)],
  );
  yield _retime(
    'one-diverged-leg-keeps-proportional-time',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40), _leg(5000, 1), _leg(1000, 60)],
  );
  yield _retime(
    'less-than-half-verified-keeps-original',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40), _leg(5000, 1), _leg(5000, 1)],
  );
  yield _retime(
    'exactly-half-verified-is-accepted',
    points: _line([1000, 1000, 1000, 1000]),
    distanceM: 4000,
    durationS: 400,
    legs: [_leg(1000, 10), _leg(1000, 20), _leg(5000, 1), _leg(5000, 1)],
  );
  yield _retime(
    'wrong-leg-count-keeps-original',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40)],
  );
  yield _retime(
    'null-distance-keeps-original',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40), _leg(null, 50), _leg(1000, 60)],
  );
  yield _retime(
    'null-duration-keeps-original',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 40), _leg(1000, null), _leg(1000, 60)],
  );
  yield _retime(
    'zero-result-duration-keeps-original',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1000, 0), _leg(1000, 0), _leg(1000, 0)],
  );
  yield _retime(
    'short-slice-150m-slack-is-inclusive',
    points: _line([100, 100, 100]),
    distanceM: 300,
    legs: [_leg(250, 10), _leg(250, 10), _leg(250, 10)],
  );
  yield _retime(
    'short-slice-over-150m-is-rejected',
    points: _line([100, 100, 100]),
    distanceM: 300,
    legs: [_leg(251, 10), _leg(251, 10), _leg(251, 10)],
  );
  yield _retime(
    'twenty-percent-slack-is-inclusive',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1200, 10), _leg(1200, 10), _leg(1200, 10)],
  );
  yield _retime(
    'over-twenty-percent-is-rejected',
    points: _line([1000, 1000, 1000]),
    legs: [_leg(1201, 10), _leg(1201, 10), _leg(1201, 10)],
  );
  yield _retime(
    'ferry-keeps-valhalla-share-and-leaves-road-budget',
    points: _line([1000, 30000, 1000]),
    distanceM: 32000,
    durationS: 320,
    legs: [_leg(1000, 1), _leg(30000, 5), _leg(1000, 2)],
  );
  yield _retime(
    'all-ferry-route-has-empty-road-budget',
    points: _line([30000]),
    distanceM: 30000,
    legs: [_leg(null, null), _leg(30000, 1), _leg(null, null)],
  );
  yield _retime(
    'zero-arc-leg-is-skipped-before-validation',
    points: _line([1000, 0, 1000]),
    distanceM: 2000,
    legs: [_leg(1000, 50), _leg(null, null), _leg(1000, 60)],
  );
  yield _retime(
    'accepted-route-preserves-offroad-classification',
    points: _line([1000, 1000, 1000]),
    avoidance: RouteAvoidance.offRoadAvoided,
    legs: [_leg(1000, 40), _leg(1000, 50), _leg(1000, 60)],
  );
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildRoutingAvoidanceFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
