import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/services/nav_phrases.dart';
import 'package:roadstr/services/routing_response_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/routing_responses_v1.tsv';

typedef _Case = ({
  String operation,
  String name,
  String language,
  LatLng fallback,
  String input,
});

String buildRoutingResponsesFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_routing_responses_fixture.dart.',
    '# operation\tname\tlanguage\tfallback_lat\tfallback_lon\tinput_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.operation,
      value.name,
      value.language,
      value.fallback.latitude,
      value.fallback.longitude,
      _encode(value.input),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  try {
    return switch (value.operation) {
      'osrm' => RoutingResponseProtocol.parseOsrmRoutes(
          value.input,
          languageCode: value.language,
        ).map(_canonicalRoute).join('\n--route--\n'),
      'ors' => _canonicalRoute(
          RoutingResponseProtocol.parseOpenRouteService(
            value.input,
            fallbackOrigin: value.fallback,
          ),
        ),
      'graphhopper' => _canonicalRoute(
          RoutingResponseProtocol.parseGraphHopper(
            value.input,
            fallbackOrigin: value.fallback,
          ),
        ),
      'valhalla' => _canonicalValhalla(
          RoutingResponseProtocol.parseValhalla(value.input),
        ),
      'retime' => _canonicalRetime(
          RoutingResponseProtocol.parseOsrmRetimeLegs(value.input),
        ),
      'exit' =>
        'exit=${RoutingResponseProtocol.parseExitNumber(value.input) ?? '-'}',
      'polyline' => RoutingResponseProtocol.decodeValhallaPolyline(value.input)
          .map(_point)
          .join(';'),
      _ => throw StateError('Unknown operation ${value.operation}'),
    };
  } on RoutingException catch (error) {
    return 'error=${error.message}';
  } catch (error) {
    return 'error=$error';
  }
}

String _canonicalValhalla(ValhallaRouteResponse response) => [
      _canonicalRoute(response.route),
      'summary=${response.summary['has_highway'] ?? '-'},'
          '${response.summary['has_toll'] ?? '-'}',
    ].join('\n');

String _canonicalRetime(List<OsrmRetimeLeg>? legs) => legs == null
    ? 'null'
    : legs
        .map((leg) => '${leg.distanceM == null ? '-' : _f3(leg.distanceM!)},'
            '${leg.durationS == null ? '-' : _f3(leg.durationS!)}')
        .join(';');

String _canonicalRoute(RouteResult route) => [
      'distance=${_f3(route.totalDistanceM)}',
      'duration=${_f3(route.totalDurationS)}',
      'avoidance=${route.avoidance.name}',
      'from_avoidance=${route.fromAvoidanceRouter}',
      'points=${route.polyline.map(_point).join(';')}',
      'steps=${route.steps.map(_step).join(';')}',
      'speeds=${route.speedLimits.map((entry) => '${_f3(entry.distFromStartM)},${entry.speedKmh ?? '-'}').join(';')}',
    ].join('\n');

String _step(RouteStep step) => [
      _encode(step.instruction),
      _encode(step.direction),
      _encode(step.modifier),
      _f3(step.distanceM),
      _point(step.location),
      step.exitNumber ?? '-',
      step.roundaboutArmCount ?? '-',
      step.exitLabel == null ? '-' : _encode(step.exitLabel!),
      _encode(step.roadName),
      _encode(step.roadRef),
    ].join(',');

String _point(LatLng point) =>
    '${point.latitude.toStringAsFixed(6)},${point.longitude.toStringAsFixed(6)}';

String _f3(double value) => value.toStringAsFixed(3);

Iterable<_Case> _cases() sync* {
  const fallback = LatLng(44.5, 8.5);
  for (final language in [...navPhrases.keys, 'xx']) {
    yield (
      operation: 'osrm',
      name: 'language-$language',
      language: language,
      fallback: fallback,
      input: jsonEncode(_simpleOsrm()),
    );
  }
  yield _responseCase('osrm', 'complex-maneuvers', _complexOsrm(),
      language: 'it');
  yield _responseCase(
    'osrm',
    'alternatives',
    {
      'code': 'Ok',
      'routes': [
        _simpleOsrm()['routes'][0],
        _simpleOsrm(offset: 0.02)['routes'][0]
      ],
    },
  );
  yield _responseCase('osrm', 'provider-error', {'code': 'NoRoute'});
  yield _responseCase('osrm', 'missing-routes', {'code': 'Ok'});
  yield _responseCase('osrm', 'missing-legs', {
    'code': 'Ok',
    'routes': [
      {
        'distance': 100,
        'duration': 10,
        'geometry': {'coordinates': _coordinates(2)},
      },
    ],
  });
  yield _responseCase(
      'osrm',
      'invalid-coordinate',
      _simpleOsrm(coordinates: const [
        [9.0, 95.0],
        [9.1, 45.1]
      ]));
  yield _responseCase('osrm', 'zero-distance', _simpleOsrm(distance: 0));
  yield _responseCase('osrm', 'negative-step', _simpleOsrm(stepDistance: -1));

  yield _responseCase('ors', 'all-maneuvers', _orsAllManeuvers());
  yield _responseCase('ors', 'missing-features', {'type': 'FeatureCollection'});
  yield _responseCase(
      'ors', 'missing-steps', _orsAllManeuvers(steps: const []));

  yield _responseCase('graphhopper', 'all-signs-and-speeds', _graphHopper());
  yield _responseCase(
    'graphhopper',
    'partial-malformed-speed-details',
    _graphHopper(speedIntervals: const [
      [0, 1, 30],
      ['bad'],
    ]),
  );
  yield _responseCase('graphhopper', 'missing-paths', {'message': 'none'});

  yield _responseCase('valhalla', 'all-maneuvers', _valhallaAllManeuvers());
  yield _responseCase(
      'valhalla', 'two-legs-shared-endpoint', _valhallaTwoLegs());
  yield _responseCase('valhalla', 'status-error', {
    'trip': {'status': 171},
  });
  yield _responseCase('valhalla', 'missing-legs', {
    'trip': {
      'status': 0,
      'summary': {'length': 1, 'time': 1},
    },
  });
  yield _responseCase('valhalla', 'malformed-shape', {
    'trip': {
      'status': 0,
      'summary': {'length': 1, 'time': 1},
      'legs': [
        {
          'shape': '~',
          'maneuvers': const [],
        },
      ],
    },
  });

  yield _responseCase('retime', 'valid', {
    'code': 'Ok',
    'routes': [
      {
        'legs': [
          {'distance': 123.4, 'duration': 10},
          {'distance': 456, 'duration': 20.5},
          {'distance': null, 'duration': 30},
        ],
      },
    ],
  });
  yield _responseCase('retime', 'provider-error', {'code': 'NoRoute'});
  yield _responseCase('retime', 'malformed', {'code': 'Ok', 'routes': []});

  for (final entry in <String, String>{
    'numeric-first': 'Take the 1st exit',
    'numeric-twelve': 'Uscita 12ª',
    'italian': 'Prendi la terza uscita',
    'french': 'Prenez la quatrième sortie',
    'spanish': 'Tome la segunda salida',
    'portuguese': 'Pegue a sexta saída',
    'unknown': 'Continue around the circle',
  }.entries) {
    yield (
      operation: 'exit',
      name: entry.key,
      language: '-',
      fallback: fallback,
      input: entry.value,
    );
  }

  const polylinePoints = [
    LatLng(45.0703, 7.6869),
    LatLng(45.071111, 7.688222),
    LatLng(-0.000001, 0.000002),
  ];
  yield (
    operation: 'polyline',
    name: 'signed-polyline6',
    language: '-',
    fallback: fallback,
    input: _encodePolyline6(polylinePoints),
  );
  yield (
    operation: 'polyline',
    name: 'malformed',
    language: '-',
    fallback: fallback,
    input: '~',
  );
}

_Case _responseCase(
  String operation,
  String name,
  Object body, {
  String language = 'en',
}) =>
    (
      operation: operation,
      name: name,
      language: language,
      fallback: const LatLng(44.5, 8.5),
      input: jsonEncode(body),
    );

Map<String, dynamic> _simpleOsrm({
  double offset = 0,
  double distance = 1000,
  double stepDistance = 500,
  List<List<double>>? coordinates,
}) {
  final points = coordinates ??
      [
        [9.0 + offset, 45.0 + offset],
        [9.1 + offset, 45.1 + offset],
      ];
  return {
    'code': 'Ok',
    'routes': [
      {
        'distance': distance,
        'duration': 120,
        'geometry': {'coordinates': points},
        'legs': [
          {
            'steps': [
              _osrmStep('depart', points[0], stepDistance, name: 'Start Road'),
              _osrmStep('turn', points[0], 500,
                  modifier: 'right', name: 'Via Roma'),
              _osrmStep('arrive', points[1], 0),
            ],
          },
        ],
      },
    ],
  };
}

Map<String, dynamic> _complexOsrm() {
  final points = _coordinates(7);
  return {
    'code': 'Ok',
    'routes': [
      {
        'distance': 4200,
        'duration': 360,
        'geometry': {'coordinates': points},
        'legs': [
          {
            'steps': [
              _osrmStep('depart', points[0], 100,
                  name: 'Strada Statale', ref: 'E45;SS3bis'),
              _osrmStep('new name', points[1], 50,
                  modifier: 'straight', name: 'Renamed'),
              _osrmStep('continue', points[2], 300,
                  modifier: 'straight',
                  name: 'Via Po',
                  intersections: const [
                    {
                      'bearings': [0, 90],
                      'in': 0,
                      'out': 1,
                    },
                  ]),
              _osrmStep('off ramp', points[3], 400,
                  modifier: 'right', name: 'Tangenziale', exits: ' 12A '),
              _osrmStep('roundabout', points[4], 200, name: 'Piazza', exit: 3),
              _osrmStep('rotary', points[5], 200, name: 'Rotonda', exit: 99),
              _osrmStep('arrive', points[6], 0),
            ],
          },
          {
            'steps': [
              _osrmStep('turn', points[6], 999, modifier: 'left'),
            ],
          },
        ],
      },
    ],
  };
}

Map<String, dynamic> _osrmStep(
  String type,
  List<double> location,
  double distance, {
  String modifier = '',
  String name = '',
  String ref = '',
  String? exits,
  int? exit,
  List<Map<String, Object>>? intersections,
}) =>
    {
      'distance': distance,
      'name': name,
      'ref': ref,
      if (exits != null) 'exits': exits,
      if (intersections != null) 'intersections': intersections,
      'maneuver': {
        'type': type,
        'modifier': modifier,
        'location': location,
        if (exit != null) 'exit': exit,
      },
    };

Map<String, dynamic> _orsAllManeuvers({List<Object?>? steps}) {
  final coordinates = _coordinates(16);
  final generatedSteps = <Map<String, dynamic>>[
    for (var type = 0; type <= 14; type++)
      {
        'instruction': type == 7 ? 'Take the third exit' : 'ORS $type',
        'distance': type == 10 ? 0 : 100,
        'type': type == 8 ? '$type' : type,
        'way_points': [type, type + 1],
      },
  ];
  return {
    'type': 'FeatureCollection',
    'features': [
      {
        'geometry': {'coordinates': coordinates},
        'properties': {
          'summary': {'distance': 1500, 'duration': 240},
          'segments': [
            {'steps': steps ?? generatedSteps},
          ],
        },
      },
    ],
  };
}

Map<String, dynamic> _graphHopper({List<List<Object?>>? speedIntervals}) {
  final coordinates = _coordinates(16);
  const signs = [-8, -7, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 42];
  return {
    'paths': [
      {
        'distance': 8000,
        'time': 654321,
        'points': {'coordinates': coordinates},
        'instructions': [
          for (var index = 0; index < signs.length; index++)
            {
              'text': signs[index] == 6
                  ? 'At roundabout take 4th exit'
                  : 'GH ${signs[index]}',
              'distance': signs[index] == 4 ? 0 : 100,
              'sign': index == 5 ? '${signs[index]}' : signs[index],
              'interval': [index, index + 1],
            },
        ],
        'details': {
          'max_speed': speedIntervals ??
              const [
                [0, 2, 50],
                [2, 4, null],
                [4, 8, 90.9],
                [99, 100, 30],
              ],
        },
      },
    ],
  };
}

Map<String, dynamic> _valhallaAllManeuvers() {
  final points = [
    for (var index = 0; index < 30; index++)
      LatLng(45 + index * 0.0001, 9 + index * 0.0001),
  ];
  return {
    'trip': {
      'status': 0,
      'summary': {
        'length': 3.5,
        'time': 700,
        'has_highway': true,
        'has_toll': false,
      },
      'legs': [
        {
          'shape': _encodePolyline6(points),
          'maneuvers': [
            for (var type = 1; type <= 29; type++)
              {
                'type': type,
                'instruction': ' Valhalla $type ',
                'length': type == 4 ? 0 : 0.1,
                'begin_shape_index': type - 1,
                if (type == 26) 'roundabout_exit_count': 4,
                if (type == 26)
                  'sign': {
                    'exit_number_elements': [
                      {'text': ' 199 '},
                    ],
                  },
                if (type == 27) 'roundabout_exit_count': 99,
              },
          ],
        },
      ],
    },
  };
}

Map<String, dynamic> _valhallaTwoLegs() {
  const first = [
    LatLng(45.0, 9.0),
    LatLng(45.001, 9.001),
    LatLng(45.002, 9.002),
  ];
  const second = [
    LatLng(45.002, 9.002),
    LatLng(45.003, 9.003),
  ];
  Map<String, dynamic> leg(List<LatLng> points, String label) => {
        'shape': _encodePolyline6(points),
        'maneuvers': [
          {
            'type': 1,
            'instruction': 'Depart $label',
            'length': 0.1,
            'begin_shape_index': 0,
          },
          {
            'type': 4,
            'instruction': 'Arrive $label',
            'length': 0,
            'begin_shape_index': points.length - 1,
          },
        ],
      };
  return {
    'trip': {
      'status': 0,
      'summary': {
        'length': 0.4,
        'time': 80,
        'has_highway': false,
        'has_toll': false,
      },
      'legs': [leg(first, 'one'), leg(second, 'two')],
    },
  };
}

List<List<double>> _coordinates(int count) => [
      for (var index = 0; index < count; index++)
        [9 + index * 0.001, 45 + index * 0.001],
    ];

String _encodePolyline6(List<LatLng> points) {
  final output = StringBuffer();
  var previousLatitude = 0;
  var previousLongitude = 0;
  for (final point in points) {
    final latitude = (point.latitude * 1e6).round();
    final longitude = (point.longitude * 1e6).round();
    _writeDelta(output, latitude - previousLatitude);
    _writeDelta(output, longitude - previousLongitude);
    previousLatitude = latitude;
    previousLongitude = longitude;
  }
  return output.toString();
}

void _writeDelta(StringBuffer output, int delta) {
  var value = delta < 0 ? ~(delta << 1) : delta << 1;
  while (value >= 0x20) {
    output.writeCharCode((0x20 | (value & 0x1f)) + 63);
    value >>= 5;
  }
  output.writeCharCode(value + 63);
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildRoutingResponsesFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it.');
      exitCode = 1;
    }
    return;
  }
  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
}
