import 'dart:convert';
import 'dart:io';

import 'package:roadstr/services/nostr_pending_report_queue.dart';
import 'package:roadstr/services/nostr_protocol_codec.dart';

const outputPath =
    'android/app/src/test/resources/parity/nostr_pending_queue_v1.tsv';
const nostrFixturePath =
    'android/app/src/test/resources/parity/nostr_protocol_v1.tsv';

enum _PublishOutcome { success, failure, throws }

class _Input {
  const _Input(this.id, this.expiresAt, this.valid, this.publish);

  final String id;
  final int expiresAt;
  final bool valid;
  final _PublishOutcome publish;

  String get encoded => '$id,$expiresAt,$valid,${publish.name}';
}

class _Case {
  const _Case(this.id, this.now, this.inputs);

  final String id;
  final int now;
  final List<_Input> inputs;
}

const cases = <_Case>[
  _Case('empty', 1000, []),
  _Case('mixed', 1000, [
    _Input('expired-past', 999, true, _PublishOutcome.success),
    _Input('expired-boundary', 1000, true, _PublishOutcome.success),
    _Input('invalid', 1100, false, _PublishOutcome.success),
    _Input('published', 1100, true, _PublishOutcome.success),
    _Input('retry-failure', 1100, true, _PublishOutcome.failure),
    _Input('retry-throw', 1100, true, _PublishOutcome.throws),
  ]),
  _Case('fifo-retries', 2000, [
    _Input('first', 3000, true, _PublishOutcome.failure),
    _Input('second', 3000, true, _PublishOutcome.success),
    _Input('third', 3000, true, _PublishOutcome.failure),
  ]),
  _Case('all-invalid', 3000, [
    _Input('bad-a', 4000, false, _PublishOutcome.success),
    _Input('bad-b', 4000, false, _PublishOutcome.failure),
  ]),
  _Case('all-published', 4000, [
    _Input('ok-a', 5000, true, _PublishOutcome.success),
    _Input('ok-b', 5000, true, _PublishOutcome.success),
  ]),
  _Case('int64-clock', 4102444800, [
    _Input('future', 4102444801, true, _PublishOutcome.failure),
  ]),
];

String b64(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

String unb64(String value) {
  final padded = value.padRight((value.length + 3) ~/ 4 * 4, '=');
  return utf8.decode(base64Url.decode(padded));
}

String joined(Iterable<String> values) {
  final result = values.join(',');
  return result.isEmpty ? '-' : result;
}

Future<String> buildQueueFixture() async {
  final lines = <String>[
    '# Roadstr pending Nostr report queue fixture v1.',
    '# Generated by tools/kotlin_rewrite/generate_nostr_queue_fixture.dart.',
  ];

  for (final testCase in cases) {
    final byId = {for (final input in testCase.inputs) input.id: input};
    final pending = testCase.inputs
        .map((input) => PendingRoadReportStorage.entry(
              {'id': input.id},
              input.expiresAt,
            ))
        .toList();
    final result = await flushPendingRoadReports(
      pending: pending,
      now: testCase.now,
      verify: (event) => byId[event['id']]!.valid,
      publish: (event) async {
        switch (byId[event['id']]!.publish) {
          case _PublishOutcome.success:
            return;
          case _PublishOutcome.failure:
            throw Exception('relay rejected');
          case _PublishOutcome.throws:
            throw StateError('transport failed');
        }
      },
    );
    lines.add([
      'flush',
      testCase.id,
      '${testCase.now}',
      testCase.inputs.isEmpty
          ? '-'
          : testCase.inputs.map((input) => input.encoded).join(';'),
      joined(result.attemptedIds),
      joined(result.remaining.map(
        (entry) => (entry['event'] as Map)['id'] as String,
      )),
      joined(result.decisions.map(
        (decision) => '${decision.id}=${decision.disposition.name}',
      )),
    ].join('\t'));
  }

  final nostrRows = File(nostrFixturePath)
      .readAsLinesSync()
      .where((line) => line.isNotEmpty && !line.startsWith('#'))
      .map((line) => line.split('\t'))
      .toList();
  final report = nostrRows.singleWhere(
    (row) => row[0] == 'report' && row[1] == 'report-speedCamera',
  );
  final signature = nostrRows.singleWhere((row) => row[0] == 'wire-publish')[3];
  final draft = RoadstrNostrEvents.report(
    pubkey: report[2],
    createdAt: int.parse(report[3]),
    latitude: double.parse(report[4]),
    longitude: double.parse(report[5]),
    category: report[6],
    expiresAt: int.parse(report[7]),
    speedLimit: int.parse(report[8]),
    content: unb64(report[9]),
  );
  final entryExpiresAt = int.parse(report[7]);
  final storageJson = PendingRoadReportStorage.encode([
    PendingRoadReportStorage.entry(
      draft.toJson(signature: signature),
      entryExpiresAt,
    ),
  ]).single;
  lines.add([
    'storage',
    'signed-report',
    'report-speedCamera',
    signature,
    '$entryExpiresAt',
    b64(storageJson),
  ].join('\t'));

  return '${lines.join('\n')}\n';
}

Future<void> main(List<String> arguments) async {
  final generated = await buildQueueFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
