import 'dart:convert';
import 'dart:io';

import 'package:latlong2/latlong.dart';
import 'package:roadstr/models/search_history_item.dart';
import 'package:roadstr/services/search_history_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/search_history_v1.tsv';

typedef _Case = ({String operation, String name, Object? payload});

String buildSearchHistoryFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_search_history_fixture.dart.',
    '# operation\tname\tpayload_b64\texpected_b64',
  ];
  for (final value in _cases()) {
    rows.add([
      value.operation,
      value.name,
      _encode(jsonEncode(value.payload)),
      _encode(_evaluate(value)),
    ].join('\t'));
  }
  return '${rows.join('\n')}\n';
}

String _evaluate(_Case value) {
  return switch (value.operation) {
    'decode' => _canonicalEntries(
        SearchHistoryProtocol.decodeStored(value.payload),
      ),
    'prepend' => _canonicalEntries(
        _prepend(value.payload as Map<String, Object?>),
      ),
    'encode' => _canonicalStorage(
        SearchHistoryProtocol.encodeStored(_entryList(value.payload)),
      ),
    _ => throw StateError('Unknown operation ${value.operation}'),
  };
}

String _canonicalEntries(List<SearchHistoryItem> entries) => _canonicalStorage(
      entries.map(SearchHistoryProtocol.encodeItem).toList(growable: false),
    );

String _canonicalStorage(List<String> values) =>
    'count=${values.length}\n${values.join('\n')}';

List<SearchHistoryItem> _prepend(Map<String, Object?> payload) =>
    SearchHistoryProtocol.prepend(
      _entry(payload['item']),
      _entryList(payload['current']),
    );

List<SearchHistoryItem> _entryList(Object? value) =>
    (value as List<Object?>).map(_entry).toList();

SearchHistoryItem _entry(Object? value) {
  final json = value as Map<String, Object?>;
  return SearchHistoryItem(
    json['label']! as String,
    LatLng(
      (json['lat']! as num).toDouble(),
      (json['lon']! as num).toDouble(),
    ),
  );
}

Map<String, Object?> _item(
  String label,
  double latitude,
  double longitude, [
  Map<String, Object?> extra = const {},
]) =>
    {
      'label': label,
      'lat': latitude,
      'lon': longitude,
      ...extra,
    };

String _stored(Object? value) => jsonEncode(value);

Iterable<_Case> _cases() sync* {
  yield (operation: 'decode', name: 'null-root', payload: null);
  yield (operation: 'decode', name: 'non-list-root', payload: {'x': 1});
  yield (operation: 'decode', name: 'empty-list', payload: <Object?>[]);
  yield (
    operation: 'decode',
    name: 'valid-integral-coordinates',
    payload: [
      _stored({'label': 'Casa', 'lat': 45, 'lon': 9})
    ],
  );
  yield (
    operation: 'decode',
    name: 'skips-malformed-and-non-string',
    payload: [
      7,
      null,
      '{',
      '[]',
      _stored({'label': 'Prima', 'lat': '45', 'lon': 9}),
      _stored({'label': 'Valida', 'lat': 44.5, 'lon': 12.25}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'coordinate-bounds-inclusive',
    payload: [
      _stored({'label': 'Sud Ovest', 'lat': -90.0, 'lon': -180.0}),
      _stored({'label': 'Nord Est', 'lat': 90.0, 'lon': 180.0}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'rejects-coordinate-overflow',
    payload: [
      _stored({'label': 'Lat alta', 'lat': 90.000001, 'lon': 0}),
      _stored({'label': 'Lat bassa', 'lat': -90.000001, 'lon': 0}),
      _stored({'label': 'Lon alta', 'lat': 0, 'lon': 180.000001}),
      _stored({'label': 'Lon bassa', 'lat': 0, 'lon': -180.000001}),
      _stored({'label': 'Ok', 'lat': 0, 'lon': 0}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'rejects-missing-and-wrong-types',
    payload: [
      _stored({'label': 'No lat', 'lon': 1}),
      _stored({'label': 'No lon', 'lat': 1}),
      _stored({'label': true, 'lat': 1, 'lon': 1}),
      _stored({'label': 'Text coords', 'lat': '1', 'lon': '1'}),
      _stored({'label': 'Ok', 'lat': 1, 'lon': 1}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'rejects-empty-and-long-labels',
    payload: [
      _stored({'label': '', 'lat': 1, 'lon': 1}),
      _stored({'label': 'x' * 301, 'lat': 2, 'lon': 2}),
      _stored({'label': 'x' * 300, 'lat': 3, 'lon': 3}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'label-limit-counts-utf16-units',
    payload: [
      _stored({'label': '🚗' * 151, 'lat': 1, 'lon': 1}),
      _stored({'label': '🚗' * 150, 'lat': 2, 'lon': 2}),
    ],
  );
  yield (
    operation: 'decode',
    name: 'preserves-order-duplicates-and-unknown-fields',
    payload: [
      _stored(_item('Uno', 45, 9, {'future': true})),
      _stored(_item('Uno', 45, 9)),
      _stored(_item('Due', 46, 10)),
    ],
  );
  yield (
    operation: 'decode',
    name: 'continues-until-one-hundred-valid',
    payload: [
      '{',
      for (var i = 0; i < 105; i++) _stored(_item('Item $i', i / 10, i / 10)),
    ],
  );
  yield (
    operation: 'decode',
    name: 'unicode-and-control-label',
    payload: [_stored(_item('Caffè 🚗\n"Centro"', 45.1, 9.2))],
  );
  yield (
    operation: 'decode',
    name: 'tiny-and-negative-zero',
    payload: [
      _stored(_item('Tiny', 1e-7, -1e-7)),
      _stored(_item('Zero', -0.0, 0.0)),
    ],
  );

  yield (
    operation: 'prepend',
    name: 'empty-history',
    payload: {'item': _item('Nuova', 45, 9), 'current': <Object?>[]},
  );
  yield (
    operation: 'prepend',
    name: 'exact-position-moves-to-front',
    payload: {
      'item': _item('Nuova etichetta', 45, 9),
      'current': [_item('Vecchia', 45, 9), _item('Altra', 46, 10)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'within-coordinate-window-is-duplicate',
    payload: {
      'item': _item('Nuova', 45, 9),
      'current': [_item('Quasi', 45.00009, 8.99991), _item('Altra', 46, 10)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'decimal-boundary-follows-double-arithmetic',
    payload: {
      'item': _item('Nuova', 0, 0),
      'current': [_item('Confine', 0.0001, -0.0001), _item('Altra', 1, 1)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'outside-latitude-window-stays',
    payload: {
      'item': _item('Nuova', 45, 9),
      'current': [_item('Vicina', 45.0001001, 9)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'outside-longitude-window-stays',
    payload: {
      'item': _item('Nuova', 45, 9),
      'current': [_item('Vicina', 45, 9.0001001)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'same-label-at-different-position-stays',
    payload: {
      'item': _item('Casa', 45, 9),
      'current': [_item('Casa', 46, 10)],
    },
  );
  yield (
    operation: 'prepend',
    name: 'removes-all-near-copies',
    payload: {
      'item': _item('Nuova', 45, 9),
      'current': [
        _item('Copia 1', 45, 9),
        _item('Copia 2', 45.00001, 9.00001),
        _item('Altra', 46, 10),
      ],
    },
  );
  yield (
    operation: 'prepend',
    name: 'caps-at-five-newest',
    payload: {
      'item': _item('Nuova', 0, 0),
      'current': [
        for (var i = 1; i <= 7; i++) _item('Old $i', i * 1.0, i * 1.0)
      ],
    },
  );
  yield (
    operation: 'prepend',
    name: 'duplicates-do-not-consume-capacity',
    payload: {
      'item': _item('Nuova', 0, 0),
      'current': [
        _item('Copia', 0, 0),
        for (var i = 1; i <= 5; i++) _item('Old $i', i * 1.0, i * 1.0),
      ],
    },
  );

  yield (
    operation: 'encode',
    name: 'exact-storage-shape',
    payload: [_item('Casa', 45, 9)],
  );
  yield (
    operation: 'encode',
    name: 'string-escaping-and-unicode',
    payload: [_item('Caffè 🚗\b\t\n\f\r"\\\u0001', 45.25, 9.5)],
  );
  yield (
    operation: 'encode',
    name: 'lone-utf16-surrogate-is-escaped',
    payload: [_item(String.fromCharCode(0xd800), 1, 1)],
  );
  yield (
    operation: 'encode',
    name: 'negative-zero',
    payload: [_item('Zero', -0.0, 0.0)],
  );
  yield (
    operation: 'encode',
    name: 'dart-small-exponent-format',
    payload: [_item('Tiny', 1e-7, -1e-7)],
  );
  yield (
    operation: 'encode',
    name: 'dart-decimal-threshold-format',
    payload: [_item('Threshold', 0.000001, -0.000001)],
  );
  yield (
    operation: 'encode',
    name: 'caps-at-five',
    payload: [for (var i = 0; i < 7; i++) _item('Item $i', i * 1.0, i * 1.0)],
  );
}

String _encode(String value) {
  if (value.isEmpty) return '-';
  return base64Url.encode(utf8.encode(value)).replaceAll('=', '');
}

void main(List<String> args) {
  final generated = buildSearchHistoryFixture();
  final file = File(outputPath);
  if (args.contains('--check')) {
    if (!file.existsSync() || file.readAsStringSync() != generated) {
      stderr.writeln('Stale fixture: $outputPath');
      exitCode = 1;
    }
    return;
  }
  file.writeAsStringSync(generated);
}
