import 'dart:convert';
import 'dart:io';

import 'package:roadstr/services/search_provider_protocol.dart';

const outputPath =
    'android/app/src/test/resources/parity/search_provider_requests_v1.tsv';

typedef _FixtureCase = ({
  String operation,
  String name,
  String text,
  double? latitude,
  double? longitude,
  String option,
  int? limit,
});

String buildSearchProviderRequestsFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_search_provider_requests_fixture.dart.',
    '# operation\tname\ttext_b64\tlatitude\tlongitude\toption_b64\tlimit\texpected_b64',
  ];

  for (final value in _cases) {
    final request = switch (value.operation) {
      'nominatim_search' => SearchProviderProtocol.nominatimSearch(
          value.text,
          latitude: value.latitude,
          longitude: value.longitude,
        ),
      'nominatim_reverse' => SearchProviderProtocol.nominatimReverse(
          latitude: value.latitude!,
          longitude: value.longitude!,
        ),
      'photon_search' => SearchProviderProtocol.photonSearch(
          value.text,
          latitude: value.latitude,
          longitude: value.longitude,
          languageCode: value.option,
          limit: value.limit!,
        ),
      'overpass' => SearchProviderProtocol.overpass(value.option, value.text),
      _ => throw StateError('Unknown provider fixture operation'),
    };
    rows.add([
      value.operation,
      value.name,
      _encode(value.text),
      value.latitude?.toString() ?? '-',
      value.longitude?.toString() ?? '-',
      _encode(value.option),
      value.limit?.toString() ?? '-',
      _encode(_canonical(request)),
    ].join('\t'));
  }

  return '${rows.join('\n')}\n';
}

String _canonical(SearchProviderRequest? request) {
  if (request == null) return 'null';
  final headers = request.headers.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  return [
    'method=${request.method.name}',
    'uri=${request.uri}',
    'headers=${headers.map((e) => '${_encode(e.key)}:${_encode(e.value)}').join(',')}',
    'body=${request.body == null ? '-' : _encode(request.body!)}',
  ].join('\n');
}

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

final _cases = <_FixtureCase>[
  (
    operation: 'nominatim_search',
    name: 'empty',
    text: '',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'whitespace-only',
    text: ' \t\n',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'basic',
    text: 'Via Roma',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'trim',
    text: '  Piazza Castello  ',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'component-punctuation',
    text: "A B+c&d/e?f#x -_.!~*'()",
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'unicode',
    text: 'Caffè 東京',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'unicode-trim',
    text: '\u00a0Torino\ufeff',
    latitude: null,
    longitude: null,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'turin-bias',
    text: 'cinema',
    latitude: 45.0703,
    longitude: 7.6869,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'greenwich-bias',
    text: 'observatory',
    latitude: 51.4779,
    longitude: 0.0000005,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'positive-boundary-bias',
    text: 'edge',
    latitude: 89.75,
    longitude: 179.75,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_search',
    name: 'negative-bias',
    text: 'south west',
    latitude: -33.8688,
    longitude: -151.2093,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'turin',
    text: '',
    latitude: 45.0703,
    longitude: 7.6869,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'zero',
    text: '',
    latitude: 0.0,
    longitude: 0.0,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'negative-zero',
    text: '',
    latitude: -0.0,
    longitude: -0.0,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'tiny-longitude',
    text: '',
    latitude: 51.4779,
    longitude: 0.0000005,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'bounds',
    text: '',
    latitude: -90.0,
    longitude: 180.0,
    option: '',
    limit: null,
  ),
  (
    operation: 'nominatim_reverse',
    name: 'long-decimals',
    text: '',
    latitude: 41.902782123456,
    longitude: 12.496365654321,
    option: '',
    limit: null,
  ),
  (
    operation: 'photon_search',
    name: 'empty',
    text: '',
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'whitespace-only',
    text: '\u3000\t',
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'too-long',
    text: 'x' * 201,
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'exact-cap',
    text: 'x' * 200,
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'basic-en',
    text: 'Via Roma',
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'trim-de',
    text: '  Alexanderplatz  ',
    latitude: null,
    longitude: null,
    option: 'de',
    limit: 6,
  ),
  (
    operation: 'photon_search',
    name: 'unicode-fr',
    text: 'Café de l’Étoile',
    latitude: null,
    longitude: null,
    option: 'fr',
    limit: 5,
  ),
  (
    operation: 'photon_search',
    name: 'form-punctuation',
    text: "A B+c&d/e?f#x -_.!~*'()",
    latitude: null,
    longitude: null,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'unsupported-language',
    text: 'Roma',
    latitude: null,
    longitude: null,
    option: 'it',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'language-case-sensitive',
    text: 'London',
    latitude: null,
    longitude: null,
    option: 'EN',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'turin-bias',
    text: 'museo',
    latitude: 45.0703,
    longitude: 7.6869,
    option: 'en',
    limit: 8,
  ),
  (
    operation: 'photon_search',
    name: 'negative-bias',
    text: 'opera',
    latitude: -33.8688,
    longitude: -151.2093,
    option: 'de',
    limit: 3,
  ),
  (
    operation: 'photon_search',
    name: 'round-down',
    text: 'rounding',
    latitude: 45.074,
    longitude: 7.684,
    option: 'fr',
    limit: 1,
  ),
  (
    operation: 'photon_search',
    name: 'round-up',
    text: 'rounding',
    latitude: 45.076,
    longitude: 7.686,
    option: 'fr',
    limit: 12,
  ),
  (
    operation: 'photon_search',
    name: 'negative-zero-bias',
    text: 'origin',
    latitude: -0.0,
    longitude: -0.0,
    option: 'en',
    limit: 0,
  ),
  (
    operation: 'overpass',
    name: 'preferred-mirror',
    text: '[out:json];node(1);out;',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[0],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'fallback-mirror',
    text: '[out:json];way(2);out;',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[1],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'multiline-query',
    text:
        '[out:json][timeout:25];\nnode["amenity"="cafe"](around:500,45.0703000,7.6869000);\nout body;',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[0],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'form-punctuation',
    text: "A B+c&d/e?f#x -_.!~*'()",
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[0],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'unicode',
    text: '[name="Caffè 東京"];',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[1],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'empty-query',
    text: '',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[0],
    limit: null,
  ),
  (
    operation: 'overpass',
    name: 'percent-plus-ampersand',
    text: '50% + 20% & more',
    latitude: null,
    longitude: null,
    option: SearchProviderProtocol.overpassMirrors[1],
    limit: null,
  ),
];

void main(List<String> arguments) {
  final generated = buildSearchProviderRequestsFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
