import 'dart:convert';
import 'dart:io';

import 'package:roadstr/config/network_config.dart';
import 'package:roadstr/services/http_safety_policy.dart';

const outputPath =
    'android/app/src/test/resources/parity/http_safety_policy_v1.tsv';

String buildHttpSafetyFixture() {
  final rows = <String>[
    '# Generated by tools/kotlin_rewrite/generate_http_safety_fixture.dart.',
    '# operation\tname\targument_1\targument_2\texpected',
  ];

  final timeouts = <String, Duration>{
    'interactive': NetworkTimeouts.interactive,
    'standard': NetworkTimeouts.standard,
    'routing': NetworkTimeouts.routing,
    'transit': NetworkTimeouts.transit,
    'background': NetworkTimeouts.background,
    'socket_handshake': NetworkTimeouts.socketHandshake,
  };
  for (final entry in timeouts.entries) {
    rows.add('timeout\t${entry.key}\t-\t-\t${entry.value.inMilliseconds}');
  }

  const limits = <String, int>{
    'small_json': NetworkLimits.smallJson,
    'route': NetworkLimits.route,
    'transit_plan': NetworkLimits.transitPlan,
    'area_query': NetworkLimits.areaQuery,
    'large_area_query': NetworkLimits.largeAreaQuery,
    'bulk_geometry': NetworkLimits.bulkGeometry,
  };
  for (final entry in limits.entries) {
    rows.add('limit\t${entry.key}\t-\t-\t${entry.value}');
  }

  rows.add(
      'redirect\tfollow_redirects\t-\t-\t${BoundedHttpPolicy.followRedirects}');

  for (final value in <(String, int?, int)>[
    ('absent', null, 16),
    ('zero', 0, 16),
    ('exact', 16, 16),
    ('one-over', 17, 16),
    ('negative-invalid', -1, 16),
    ('route-exact', NetworkLimits.route, NetworkLimits.route),
    ('route-over', NetworkLimits.route + 1, NetworkLimits.route),
  ]) {
    final accepted = BoundedHttpPolicy.acceptsContentLength(value.$2, value.$3);
    rows.add(
      'content_length\t${value.$1}\t${value.$2 ?? 'none'}\t${value.$3}\t$accepted',
    );
  }

  for (final value in <(String, int, List<int>)>[
    ('empty', 8, const []),
    ('zero-chunks', 8, const [0, 0]),
    ('single-exact', 8, const [8]),
    ('split-exact', 8, const [3, 5]),
    ('single-over', 8, const [9]),
    ('cumulative-over', 8, const [4, 5]),
    ('after-exact', 8, const [8, 1]),
    ('many-small', 10, const [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
    ('large-over', NetworkLimits.smallJson, const [2147483647]),
  ]) {
    var received = 0;
    int? rejectedAt;
    for (var index = 0; index < value.$3.length; index++) {
      final chunk = value.$3[index];
      if (!BoundedHttpPolicy.acceptsChunk(
        receivedBytes: received,
        chunkBytes: chunk,
        maxBytes: value.$2,
      )) {
        rejectedAt = index;
        break;
      }
      received += chunk;
    }
    final expected = rejectedAt == null
        ? 'accepted:$received'
        : 'rejected:$received:$rejectedAt';
    rows.add(
      'chunks\t${value.$1}\t${value.$2}\t${value.$3.isEmpty ? '-' : value.$3.join(',')}\t$expected',
    );
  }

  for (final value in <(String, String)>[
    ('https-public', 'https://graphhopper.example.com/route'),
    ('https-port-query', 'https://graphhopper.example.com:8443/route?x=1'),
    ('https-lan-ip', 'https://192.168.1.50:8989/route'),
    ('http-localhost', 'http://localhost:8989/route'),
    ('http-localhost-case', 'HTTP://LOCALHOST:8989/route'),
    ('http-loopback', 'http://127.0.0.1:8989/route'),
    ('http-emulator', 'http://10.0.2.2:8989/route'),
    ('empty-userinfo-compatible', 'https://@graphhopper.example.com/route'),
    ('http-public', 'http://graphhopper.example.com/route'),
    ('http-lan', 'http://192.168.1.50:8989/route'),
    ('http-ipv6-loopback', 'http://[::1]:8989/route'),
    ('http-localhost-subdomain', 'http://route.localhost:8989/route'),
    ('http-localhost-trailing-dot', 'http://localhost.:8989/route'),
    ('userinfo-current-policy', 'https://user@graphhopper.example.com/route'),
    ('ftp-current-policy', 'ftp://graphhopper.example.com/route'),
    ('hostless', 'https:///route'),
    ('relative', '//graphhopper.example.com/route'),
    ('plain-text', 'not a url'),
    ('empty', ''),
  ]) {
    final decision = RoutingEndpointPolicy.graphHopperDecision(value.$2);
    rows.add(
      'endpoint\t${value.$1}\t${_encode(value.$2)}\t-\t${_decisionName(decision)}',
    );
  }

  return '${rows.join('\n')}\n';
}

String _decisionName(RoutingEndpointDecision decision) => switch (decision) {
      RoutingEndpointDecision.accepted => 'accepted',
      RoutingEndpointDecision.invalid => 'invalid',
      RoutingEndpointDecision.cleartextRejected => 'cleartext_rejected',
    };

String _encode(String value) =>
    base64Url.encode(utf8.encode(value)).replaceAll('=', '');

void main(List<String> arguments) {
  final generated = buildHttpSafetyFixture();
  final output = File(outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() || output.readAsStringSync() != generated) {
      stderr.writeln('$outputPath is stale; regenerate it without --check.');
      exitCode = 1;
    }
    return;
  }
  output.writeAsStringSync(generated);
}
