package app.roadstr.core.navigation

/** Generated from the production Dart navigation phrase table. */
internal object NavigationPhrases {
    private val values: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "on" to " on ",
            "depart" to "Start",
            "arrive" to "You have arrived at your destination",
            "turnLeft" to "Turn left",
            "turnRight" to "Turn right",
            "keepLeft" to "Keep left",
            "keepRight" to "Keep right",
            "sharpLeft" to "Sharp left",
            "sharpRight" to "Sharp right",
            "uturn" to "Make a U-turn",
            "continueStraight" to "Continue straight",
            "continueOn" to "Continue",
            "merge" to "Merge onto",
            "rampLeft" to "Turn left onto the on-ramp",
            "rampRight" to "Turn right onto the on-ramp",
            "takeRamp" to "Take the on-ramp",
            "exitLabelled" to "Take exit {label}",
            "exitPlain" to "Take the exit",
            "forkLeft" to "At the fork keep left",
            "forkRight" to "At the fork keep right",
            "endLeft" to "At the end of the road turn left",
            "endRight" to "At the end of the road turn right",
            "roundabout" to "At the roundabout take exit {n}",
            "rotary" to "At the rotary take exit {n}",
        ),
        "it" to mapOf(
            "on" to " su ",
            "depart" to "Parti",
            "arrive" to "Sei arrivato a destinazione",
            "turnLeft" to "Svolta a sinistra",
            "turnRight" to "Svolta a destra",
            "keepLeft" to "Tieni la sinistra",
            "keepRight" to "Tieni la destra",
            "sharpLeft" to "Svolta netta a sinistra",
            "sharpRight" to "Svolta netta a destra",
            "uturn" to "Fai inversione di marcia",
            "continueStraight" to "Continua dritto",
            "continueOn" to "Continua",
            "merge" to "Immettiti",
            "rampLeft" to "Svolta a sinistra sulla rampa",
            "rampRight" to "Svolta a destra sulla rampa",
            "takeRamp" to "Prendi la rampa",
            "exitLabelled" to "Esci all'uscita {label}",
            "exitPlain" to "Esci dalla rampa",
            "forkLeft" to "Al bivio tieni la sinistra",
            "forkRight" to "Al bivio tieni la destra",
            "endLeft" to "Alla fine della strada svolta a sinistra",
            "endRight" to "Alla fine della strada svolta a destra",
            "roundabout" to "Alla rotonda prendi la {n}° uscita",
            "rotary" to "Alla rotatoria prendi la {n}° uscita",
        ),
        "de" to mapOf(
            "on" to " auf ",
            "depart" to "Losfahren",
            "arrive" to "Sie haben Ihr Ziel erreicht",
            "turnLeft" to "Links abbiegen",
            "turnRight" to "Rechts abbiegen",
            "keepLeft" to "Links halten",
            "keepRight" to "Rechts halten",
            "sharpLeft" to "Scharf links abbiegen",
            "sharpRight" to "Scharf rechts abbiegen",
            "uturn" to "Wenden",
            "continueStraight" to "Geradeaus weiter",
            "continueOn" to "Weiter",
            "merge" to "Auffahren",
            "rampLeft" to "Links auf die Auffahrt",
            "rampRight" to "Rechts auf die Auffahrt",
            "takeRamp" to "Auffahrt nehmen",
            "exitLabelled" to "Ausfahrt {label} nehmen",
            "exitPlain" to "Ausfahrt nehmen",
            "forkLeft" to "An der Gabelung links halten",
            "forkRight" to "An der Gabelung rechts halten",
            "endLeft" to "Am Ende der Straße links abbiegen",
            "endRight" to "Am Ende der Straße rechts abbiegen",
            "roundabout" to "Im Kreisverkehr die {n}. Ausfahrt nehmen",
            "rotary" to "Im Kreisverkehr die {n}. Ausfahrt nehmen",
        ),
        "fr" to mapOf(
            "on" to " sur ",
            "depart" to "Démarrez",
            "arrive" to "Vous êtes arrivé à destination",
            "turnLeft" to "Tournez à gauche",
            "turnRight" to "Tournez à droite",
            "keepLeft" to "Serrez à gauche",
            "keepRight" to "Serrez à droite",
            "sharpLeft" to "Tournez franchement à gauche",
            "sharpRight" to "Tournez franchement à droite",
            "uturn" to "Faites demi-tour",
            "continueStraight" to "Continuez tout droit",
            "continueOn" to "Continuez",
            "merge" to "Insérez-vous",
            "rampLeft" to "Tournez à gauche sur la bretelle",
            "rampRight" to "Tournez à droite sur la bretelle",
            "takeRamp" to "Prenez la bretelle",
            "exitLabelled" to "Prenez la sortie {label}",
            "exitPlain" to "Prenez la sortie",
            "forkLeft" to "À la fourche serrez à gauche",
            "forkRight" to "À la fourche serrez à droite",
            "endLeft" to "Au bout de la route tournez à gauche",
            "endRight" to "Au bout de la route tournez à droite",
            "roundabout" to "Au rond-point prenez la {n}e sortie",
            "rotary" to "Au rond-point prenez la {n}e sortie",
        ),
        "es" to mapOf(
            "on" to " en ",
            "depart" to "Comience",
            "arrive" to "Ha llegado a su destino",
            "turnLeft" to "Gire a la izquierda",
            "turnRight" to "Gire a la derecha",
            "keepLeft" to "Manténgase a la izquierda",
            "keepRight" to "Manténgase a la derecha",
            "sharpLeft" to "Gire bruscamente a la izquierda",
            "sharpRight" to "Gire bruscamente a la derecha",
            "uturn" to "Haga un cambio de sentido",
            "continueStraight" to "Siga recto",
            "continueOn" to "Continúe",
            "merge" to "Incorpórese",
            "rampLeft" to "Gire a la izquierda hacia la rampa",
            "rampRight" to "Gire a la derecha hacia la rampa",
            "takeRamp" to "Tome la rampa",
            "exitLabelled" to "Tome la salida {label}",
            "exitPlain" to "Tome la salida",
            "forkLeft" to "En la bifurcación manténgase a la izquierda",
            "forkRight" to "En la bifurcación manténgase a la derecha",
            "endLeft" to "Al final de la calle gire a la izquierda",
            "endRight" to "Al final de la calle gire a la derecha",
            "roundabout" to "En la rotonda tome la salida {n}",
            "rotary" to "En la rotonda tome la salida {n}",
        ),
        "pt" to mapOf(
            "on" to " na ",
            "depart" to "Siga",
            "arrive" to "Chegou ao seu destino",
            "turnLeft" to "Vire à esquerda",
            "turnRight" to "Vire à direita",
            "keepLeft" to "Mantenha-se à esquerda",
            "keepRight" to "Mantenha-se à direita",
            "sharpLeft" to "Vire acentuadamente à esquerda",
            "sharpRight" to "Vire acentuadamente à direita",
            "uturn" to "Faça inversão de marcha",
            "continueStraight" to "Siga em frente",
            "continueOn" to "Continue",
            "merge" to "Entre",
            "rampLeft" to "Vire à esquerda para o ramal",
            "rampRight" to "Vire à direita para o ramal",
            "takeRamp" to "Entre no ramal",
            "exitLabelled" to "Saia na saída {label}",
            "exitPlain" to "Saia",
            "forkLeft" to "Na bifurcação mantenha-se à esquerda",
            "forkRight" to "Na bifurcação mantenha-se à direita",
            "endLeft" to "No fim da rua vire à esquerda",
            "endRight" to "No fim da rua vire à direita",
            "roundabout" to "Na rotunda saia na {n}ª saída",
            "rotary" to "Na rotunda saia na {n}ª saída",
        ),
        "nl" to mapOf(
            "on" to " op ",
            "depart" to "Vertrek",
            "arrive" to "U hebt uw bestemming bereikt",
            "turnLeft" to "Sla linksaf",
            "turnRight" to "Sla rechtsaf",
            "keepLeft" to "Houd links aan",
            "keepRight" to "Houd rechts aan",
            "sharpLeft" to "Scherp linksaf",
            "sharpRight" to "Scherp rechtsaf",
            "uturn" to "Keer om",
            "continueStraight" to "Ga rechtdoor",
            "continueOn" to "Ga verder",
            "merge" to "Voeg in",
            "rampLeft" to "Sla linksaf de oprit op",
            "rampRight" to "Sla rechtsaf de oprit op",
            "takeRamp" to "Neem de oprit",
            "exitLabelled" to "Neem afrit {label}",
            "exitPlain" to "Neem de afrit",
            "forkLeft" to "Houd bij de splitsing links aan",
            "forkRight" to "Houd bij de splitsing rechts aan",
            "endLeft" to "Sla aan het einde van de weg linksaf",
            "endRight" to "Sla aan het einde van de weg rechtsaf",
            "roundabout" to "Neem op de rotonde de {n}e afslag",
            "rotary" to "Neem op de rotonde de {n}e afslag",
        ),
        "pl" to mapOf(
            "on" to " na ",
            "depart" to "Rusz",
            "arrive" to "Dotarłeś do celu",
            "turnLeft" to "Skręć w lewo",
            "turnRight" to "Skręć w prawo",
            "keepLeft" to "Trzymaj się lewej",
            "keepRight" to "Trzymaj się prawej",
            "sharpLeft" to "Skręć ostro w lewo",
            "sharpRight" to "Skręć ostro w prawo",
            "uturn" to "Zawróć",
            "continueStraight" to "Jedź prosto",
            "continueOn" to "Kontynuuj",
            "merge" to "Włącz się",
            "rampLeft" to "Skręć w lewo na wjazd",
            "rampRight" to "Skręć w prawo na wjazd",
            "takeRamp" to "Wjedź na wjazd",
            "exitLabelled" to "Zjedź zjazdem {label}",
            "exitPlain" to "Zjedź",
            "forkLeft" to "Na rozwidleniu trzymaj się lewej",
            "forkRight" to "Na rozwidleniu trzymaj się prawej",
            "endLeft" to "Na końcu drogi skręć w lewo",
            "endRight" to "Na końcu drogi skręć w prawo",
            "roundabout" to "Na rondzie wybierz {n}. zjazd",
            "rotary" to "Na rondzie wybierz {n}. zjazd",
        ),
        "ru" to mapOf(
            "on" to " на ",
            "depart" to "Начните движение",
            "arrive" to "Вы прибыли в пункт назначения",
            "turnLeft" to "Поверните налево",
            "turnRight" to "Поверните направо",
            "keepLeft" to "Держитесь левее",
            "keepRight" to "Держитесь правее",
            "sharpLeft" to "Резко поверните налево",
            "sharpRight" to "Резко поверните направо",
            "uturn" to "Развернитесь",
            "continueStraight" to "Продолжайте прямо",
            "continueOn" to "Продолжайте",
            "merge" to "Перестройтесь",
            "rampLeft" to "Поверните налево на съезд",
            "rampRight" to "Поверните направо на съезд",
            "takeRamp" to "Съезжайте на съезд",
            "exitLabelled" to "Съезд {label}",
            "exitPlain" to "Съезжайте",
            "forkLeft" to "На развилке держитесь левее",
            "forkRight" to "На развилке держитесь правее",
            "endLeft" to "В конце дороги поверните налево",
            "endRight" to "В конце дороги поверните направо",
            "roundabout" to "На круге сверните на {n}-й съезд",
            "rotary" to "На круге сверните на {n}-й съезд",
        ),
        "zh" to mapOf(
            "on" to "在",
            "depart" to "出发",
            "arrive" to "您已到达目的地",
            "turnLeft" to "左转",
            "turnRight" to "右转",
            "keepLeft" to "靠左行驶",
            "keepRight" to "靠右行驶",
            "sharpLeft" to "急左转",
            "sharpRight" to "急右转",
            "uturn" to "调头",
            "continueStraight" to "直行",
            "continueOn" to "继续",
            "merge" to "并线",
            "rampLeft" to "左转进入匝道",
            "rampRight" to "右转进入匝道",
            "takeRamp" to "进入匝道",
            "exitLabelled" to "从{label}出口驶出",
            "exitPlain" to "驶出",
            "forkLeft" to "在岔路口靠左",
            "forkRight" to "在岔路口靠右",
            "endLeft" to "在道路尽头左转",
            "endRight" to "在道路尽头右转",
            "roundabout" to "在环岛走第{n}个出口",
            "rotary" to "在环岛走第{n}个出口",
        ),
        "ja" to mapOf(
            "on" to "を",
            "depart" to "出発",
            "arrive" to "目的地に到着しました",
            "turnLeft" to "左折",
            "turnRight" to "右折",
            "keepLeft" to "左側を進む",
            "keepRight" to "右側を進む",
            "sharpLeft" to "鋭く左折",
            "sharpRight" to "鋭く右折",
            "uturn" to "Uターン",
            "continueStraight" to "直進",
            "continueOn" to "続行",
            "merge" to "合流",
            "rampLeft" to "左折してランプへ",
            "rampRight" to "右折してランプへ",
            "takeRamp" to "ランプに入る",
            "exitLabelled" to "出口{label}へ",
            "exitPlain" to "出口へ",
            "forkLeft" to "分岐を左へ",
            "forkRight" to "分岐を右へ",
            "endLeft" to "突き当たりを左折",
            "endRight" to "突き当たりを右折",
            "roundabout" to "ロータリーで{n}番目の出口",
            "rotary" to "ロータリーで{n}番目の出口",
        ),
        "cs" to mapOf(
            "on" to " na ",
            "depart" to "Vyrazte",
            "arrive" to "Dorazili jste do cíle",
            "turnLeft" to "Odbočte vlevo",
            "turnRight" to "Odbočte vpravo",
            "keepLeft" to "Držte se vlevo",
            "keepRight" to "Držte se vpravo",
            "sharpLeft" to "Ostře odbočte vlevo",
            "sharpRight" to "Ostře odbočte vpravo",
            "uturn" to "Otočte se",
            "continueStraight" to "Pokračujte rovně",
            "continueOn" to "Pokračujte",
            "merge" to "Zařaďte se",
            "rampLeft" to "Odbočte vlevo na nájezd",
            "rampRight" to "Odbočte vpravo na nájezd",
            "takeRamp" to "Najeďte na nájezd",
            "exitLabelled" to "Sjeďte výjezdem {label}",
            "exitPlain" to "Sjeďte",
            "forkLeft" to "Na rozcestí se držte vlevo",
            "forkRight" to "Na rozcestí se držte vpravo",
            "endLeft" to "Na konci silnice odbočte vlevo",
            "endRight" to "Na konci silnice odbočte vpravo",
            "roundabout" to "Na kruhovém objezdu {n}. výjezd",
            "rotary" to "Na kruhovém objezdu {n}. výjezd",
        ),
        "sk" to mapOf(
            "on" to " na ",
            "depart" to "Vyrazte",
            "arrive" to "Dorazili ste do cieľa",
            "turnLeft" to "Odbočte vľavo",
            "turnRight" to "Odbočte vpravo",
            "keepLeft" to "Držte sa vľavo",
            "keepRight" to "Držte sa vpravo",
            "sharpLeft" to "Ostro odbočte vľavo",
            "sharpRight" to "Ostro odbočte vpravo",
            "uturn" to "Otočte sa",
            "continueStraight" to "Pokračujte rovno",
            "continueOn" to "Pokračujte",
            "merge" to "Zaraďte sa",
            "rampLeft" to "Odbočte vľavo na nájazd",
            "rampRight" to "Odbočte vpravo na nájazd",
            "takeRamp" to "Choďte na nájazd",
            "exitLabelled" to "Zíďte výjazdom {label}",
            "exitPlain" to "Zíďte",
            "forkLeft" to "Na rázcestí sa držte vľavo",
            "forkRight" to "Na rázcestí sa držte vpravo",
            "endLeft" to "Na konci cesty odbočte vľavo",
            "endRight" to "Na konci cesty odbočte vpravo",
            "roundabout" to "Na kruhovom objazde {n}. výjazd",
            "rotary" to "Na kruhovom objazde {n}. výjazd",
        ),
        "sv" to mapOf(
            "on" to " på ",
            "depart" to "Starta",
            "arrive" to "Du har kommit fram",
            "turnLeft" to "Sväng vänster",
            "turnRight" to "Sväng höger",
            "keepLeft" to "Håll till vänster",
            "keepRight" to "Håll till höger",
            "sharpLeft" to "Skarp vänstersväng",
            "sharpRight" to "Skarp högersväng",
            "uturn" to "Gör en U-sväng",
            "continueStraight" to "Fortsätt rakt fram",
            "continueOn" to "Fortsätt",
            "merge" to "Kör in",
            "rampLeft" to "Sväng vänster till påfarten",
            "rampRight" to "Sväng höger till påfarten",
            "takeRamp" to "Ta påfarten",
            "exitLabelled" to "Ta avfart {label}",
            "exitPlain" to "Ta avfarten",
            "forkLeft" to "Håll vänster i gaffeln",
            "forkRight" to "Håll höger i gaffeln",
            "endLeft" to "Sväng vänster vid vägens slut",
            "endRight" to "Sväng höger vid vägens slut",
            "roundabout" to "Ta {n}:e avfarten i rondellen",
            "rotary" to "Ta {n}:e avfarten i rondellen",
        ),
        "da" to mapOf(
            "on" to " ad ",
            "depart" to "Start",
            "arrive" to "Du er ankommet til destinationen",
            "turnLeft" to "Drej til venstre",
            "turnRight" to "Drej til højre",
            "keepLeft" to "Hold til venstre",
            "keepRight" to "Hold til højre",
            "sharpLeft" to "Skarpt til venstre",
            "sharpRight" to "Skarpt til højre",
            "uturn" to "Foretag en U-vending",
            "continueStraight" to "Fortsæt ligeud",
            "continueOn" to "Fortsæt",
            "merge" to "Flet ind",
            "rampLeft" to "Drej til venstre ad tilkørslen",
            "rampRight" to "Drej til højre ad tilkørslen",
            "takeRamp" to "Tag tilkørslen",
            "exitLabelled" to "Tag afkørsel {label}",
            "exitPlain" to "Tag afkørslen",
            "forkLeft" to "Hold til venstre ved forgreningen",
            "forkRight" to "Hold til højre ved forgreningen",
            "endLeft" to "Drej til venstre for enden af vejen",
            "endRight" to "Drej til højre for enden af vejen",
            "roundabout" to "Tag den {n}. afkørsel i rundkørslen",
            "rotary" to "Tag den {n}. afkørsel i rundkørslen",
        ),
        "fi" to mapOf(
            "on" to " tielle ",
            "depart" to "Lähde",
            "arrive" to "Olet saapunut määränpäähän",
            "turnLeft" to "Käänny vasemmalle",
            "turnRight" to "Käänny oikealle",
            "keepLeft" to "Pysy vasemmalla",
            "keepRight" to "Pysy oikealla",
            "sharpLeft" to "Käänny jyrkästi vasemmalle",
            "sharpRight" to "Käänny jyrkästi oikealle",
            "uturn" to "Tee U-käännös",
            "continueStraight" to "Jatka suoraan",
            "continueOn" to "Jatka",
            "merge" to "Liity",
            "rampLeft" to "Käänny vasemmalle liittymärampille",
            "rampRight" to "Käänny oikealle liittymärampille",
            "takeRamp" to "Aja rampille",
            "exitLabelled" to "Poistu liittymästä {label}",
            "exitPlain" to "Poistu",
            "forkLeft" to "Pysy risteyksessä vasemmalla",
            "forkRight" to "Pysy risteyksessä oikealla",
            "endLeft" to "Käänny tien päässä vasemmalle",
            "endRight" to "Käänny tien päässä oikealle",
            "roundabout" to "Aja liikenneympyrästä {n}. ulos",
            "rotary" to "Aja liikenneympyrästä {n}. ulos",
        ),
        "el" to mapOf(
            "on" to " στην ",
            "depart" to "Ξεκινήστε",
            "arrive" to "Φτάσατε στον προορισμό σας",
            "turnLeft" to "Στρίψτε αριστερά",
            "turnRight" to "Στρίψτε δεξιά",
            "keepLeft" to "Κρατηθείτε αριστερά",
            "keepRight" to "Κρατηθείτε δεξιά",
            "sharpLeft" to "Στρίψτε απότομα αριστερά",
            "sharpRight" to "Στρίψτε απότομα δεξιά",
            "uturn" to "Κάντε αναστροφή",
            "continueStraight" to "Συνεχίστε ευθεία",
            "continueOn" to "Συνεχίστε",
            "merge" to "Εισέλθετε",
            "rampLeft" to "Στρίψτε αριστερά στη ράμπα",
            "rampRight" to "Στρίψτε δεξιά στη ράμπα",
            "takeRamp" to "Πάρτε τη ράμπα",
            "exitLabelled" to "Βγείτε στην έξοδο {label}",
            "exitPlain" to "Βγείτε",
            "forkLeft" to "Στη διακλάδωση κρατηθείτε αριστερά",
            "forkRight" to "Στη διακλάδωση κρατηθείτε δεξιά",
            "endLeft" to "Στο τέλος του δρόμου στρίψτε αριστερά",
            "endRight" to "Στο τέλος του δρόμου στρίψτε δεξιά",
            "roundabout" to "Στον κυκλικό κόμβο πάρτε την {n}η έξοδο",
            "rotary" to "Στον κυκλικό κόμβο πάρτε την {n}η έξοδο",
        ),
        "hu" to mapOf(
            "on" to " a ",
            "depart" to "Induljon",
            "arrive" to "Megérkezett az úti céljához",
            "turnLeft" to "Forduljon balra",
            "turnRight" to "Forduljon jobbra",
            "keepLeft" to "Tartson balra",
            "keepRight" to "Tartson jobbra",
            "sharpLeft" to "Forduljon élesen balra",
            "sharpRight" to "Forduljon élesen jobbra",
            "uturn" to "Forduljon vissza",
            "continueStraight" to "Haladjon egyenesen",
            "continueOn" to "Folytassa",
            "merge" to "Soroljon be",
            "rampLeft" to "Forduljon balra a felhajtóra",
            "rampRight" to "Forduljon jobbra a felhajtóra",
            "takeRamp" to "Hajtson fel",
            "exitLabelled" to "Hajtson le a {label} kijáraton",
            "exitPlain" to "Hajtson le",
            "forkLeft" to "Az elágazásnál tartson balra",
            "forkRight" to "Az elágazásnál tartson jobbra",
            "endLeft" to "Az út végén forduljon balra",
            "endRight" to "Az út végén forduljon jobbra",
            "roundabout" to "A körforgalomban a {n}. kijárat",
            "rotary" to "A körforgalomban a {n}. kijárat",
        ),
        "ro" to mapOf(
            "on" to " pe ",
            "depart" to "Porniți",
            "arrive" to "Ați ajuns la destinație",
            "turnLeft" to "Virați la stânga",
            "turnRight" to "Virați la dreapta",
            "keepLeft" to "Păstrați stânga",
            "keepRight" to "Păstrați dreapta",
            "sharpLeft" to "Virați brusc la stânga",
            "sharpRight" to "Virați brusc la dreapta",
            "uturn" to "Întoarceți",
            "continueStraight" to "Continuați drept",
            "continueOn" to "Continuați",
            "merge" to "Intrați",
            "rampLeft" to "Virați la stânga pe rampă",
            "rampRight" to "Virați la dreapta pe rampă",
            "takeRamp" to "Luați rampa",
            "exitLabelled" to "Ieșiți la ieșirea {label}",
            "exitPlain" to "Ieșiți",
            "forkLeft" to "La bifurcație păstrați stânga",
            "forkRight" to "La bifurcație păstrați dreapta",
            "endLeft" to "La capătul drumului virați la stânga",
            "endRight" to "La capătul drumului virați la dreapta",
            "roundabout" to "În sensul giratoriu luați ieșirea {n}",
            "rotary" to "În sensul giratoriu luați ieșirea {n}",
        ),
        "bg" to mapOf(
            "on" to " по ",
            "depart" to "Тръгнете",
            "arrive" to "Пристигнахте до целта",
            "turnLeft" to "Завийте наляво",
            "turnRight" to "Завийте надясно",
            "keepLeft" to "Дръжте се вляво",
            "keepRight" to "Дръжте се вдясно",
            "sharpLeft" to "Завийте рязко наляво",
            "sharpRight" to "Завийте рязко надясно",
            "uturn" to "Обърнете",
            "continueStraight" to "Продължете направо",
            "continueOn" to "Продължете",
            "merge" to "Включете се",
            "rampLeft" to "Завийте наляво по рампата",
            "rampRight" to "Завийте надясно по рампата",
            "takeRamp" to "Поемете по рампата",
            "exitLabelled" to "Излезте на изход {label}",
            "exitPlain" to "Излезте",
            "forkLeft" to "На разклона дръжте вляво",
            "forkRight" to "На разклона дръжте вдясно",
            "endLeft" to "В края на пътя завийте наляво",
            "endRight" to "В края на пътя завийте надясно",
            "roundabout" to "На кръговото вземете {n}-ия изход",
            "rotary" to "На кръговото вземете {n}-ия изход",
        ),
        "hr" to mapOf(
            "on" to " na ",
            "depart" to "Krenite",
            "arrive" to "Stigli ste na odredište",
            "turnLeft" to "Skrenite lijevo",
            "turnRight" to "Skrenite desno",
            "keepLeft" to "Držite se lijevo",
            "keepRight" to "Držite se desno",
            "sharpLeft" to "Oštro skrenite lijevo",
            "sharpRight" to "Oštro skrenite desno",
            "uturn" to "Okrenite se",
            "continueStraight" to "Nastavite ravno",
            "continueOn" to "Nastavite",
            "merge" to "Uključite se",
            "rampLeft" to "Skrenite lijevo na priključak",
            "rampRight" to "Skrenite desno na priključak",
            "takeRamp" to "Uđite na priključak",
            "exitLabelled" to "Izađite na izlaz {label}",
            "exitPlain" to "Izađite",
            "forkLeft" to "Na račvanju držite se lijevo",
            "forkRight" to "Na račvanju držite se desno",
            "endLeft" to "Na kraju ceste skrenite lijevo",
            "endRight" to "Na kraju ceste skrenite desno",
            "roundabout" to "Na kružnom toku {n}. izlaz",
            "rotary" to "Na kružnom toku {n}. izlaz",
        ),
        "sl" to mapOf(
            "on" to " na ",
            "depart" to "Speljite",
            "arrive" to "Prispeli ste na cilj",
            "turnLeft" to "Zavijte levo",
            "turnRight" to "Zavijte desno",
            "keepLeft" to "Držite se levo",
            "keepRight" to "Držite se desno",
            "sharpLeft" to "Ostro zavijte levo",
            "sharpRight" to "Ostro zavijte desno",
            "uturn" to "Obrnite se",
            "continueStraight" to "Nadaljujte naravnost",
            "continueOn" to "Nadaljujte",
            "merge" to "Vključite se",
            "rampLeft" to "Zavijte levo na uvoz",
            "rampRight" to "Zavijte desno na uvoz",
            "takeRamp" to "Zapeljite na uvoz",
            "exitLabelled" to "Izvozite na izvozu {label}",
            "exitPlain" to "Izvozite",
            "forkLeft" to "Na razcepu se držite levo",
            "forkRight" to "Na razcepu se držite desno",
            "endLeft" to "Na koncu ceste zavijte levo",
            "endRight" to "Na koncu ceste zavijte desno",
            "roundabout" to "V krožišču zapeljite na {n}. izvoz",
            "rotary" to "V krožišču zapeljite na {n}. izvoz",
        ),
        "et" to mapOf(
            "on" to " teele ",
            "depart" to "Alustage",
            "arrive" to "Olete jõudnud sihtkohta",
            "turnLeft" to "Pöörake vasakule",
            "turnRight" to "Pöörake paremale",
            "keepLeft" to "Hoidke vasakule",
            "keepRight" to "Hoidke paremale",
            "sharpLeft" to "Pöörake järsult vasakule",
            "sharpRight" to "Pöörake järsult paremale",
            "uturn" to "Pöörake tagasi",
            "continueStraight" to "Sõitke otse",
            "continueOn" to "Jätkake",
            "merge" to "Suubuge",
            "rampLeft" to "Pöörake vasakule kaldteele",
            "rampRight" to "Pöörake paremale kaldteele",
            "takeRamp" to "Sõitke kaldteele",
            "exitLabelled" to "Sõitke välja väljasõidul {label}",
            "exitPlain" to "Sõitke välja",
            "forkLeft" to "Hargnemisel hoidke vasakule",
            "forkRight" to "Hargnemisel hoidke paremale",
            "endLeft" to "Tee lõpus pöörake vasakule",
            "endRight" to "Tee lõpus pöörake paremale",
            "roundabout" to "Ringteel valige {n}. väljasõit",
            "rotary" to "Ringteel valige {n}. väljasõit",
        ),
        "lt" to mapOf(
            "on" to " į ",
            "depart" to "Pradėkite",
            "arrive" to "Atvykote į kelionės tikslą",
            "turnLeft" to "Sukite kairėn",
            "turnRight" to "Sukite dešinėn",
            "keepLeft" to "Laikykitės kairės",
            "keepRight" to "Laikykitės dešinės",
            "sharpLeft" to "Sukite staigiai kairėn",
            "sharpRight" to "Sukite staigiai dešinėn",
            "uturn" to "Apsisukite",
            "continueStraight" to "Važiuokite tiesiai",
            "continueOn" to "Tęskite",
            "merge" to "Įsiliekite",
            "rampLeft" to "Sukite kairėn į įvažą",
            "rampRight" to "Sukite dešinėn į įvažą",
            "takeRamp" to "Važiuokite į įvažą",
            "exitLabelled" to "Išvažiuokite išvaža {label}",
            "exitPlain" to "Išvažiuokite",
            "forkLeft" to "Išsišakojime laikykitės kairės",
            "forkRight" to "Išsišakojime laikykitės dešinės",
            "endLeft" to "Kelio gale sukite kairėn",
            "endRight" to "Kelio gale sukite dešinėn",
            "roundabout" to "Žiede pasirinkite {n}-ą išvažiavimą",
            "rotary" to "Žiede pasirinkite {n}-ą išvažiavimą",
        ),
        "lv" to mapOf(
            "on" to " uz ",
            "depart" to "Sāciet",
            "arrive" to "Esat sasniedzis galamērķi",
            "turnLeft" to "Nogriezieties pa kreisi",
            "turnRight" to "Nogriezieties pa labi",
            "keepLeft" to "Turieties pa kreisi",
            "keepRight" to "Turieties pa labi",
            "sharpLeft" to "Strauji nogriezieties pa kreisi",
            "sharpRight" to "Strauji nogriezieties pa labi",
            "uturn" to "Apgriezieties",
            "continueStraight" to "Brauciet taisni",
            "continueOn" to "Turpiniet",
            "merge" to "Iekļaujieties",
            "rampLeft" to "Nogriezieties pa kreisi uz uzbrauktuves",
            "rampRight" to "Nogriezieties pa labi uz uzbrauktuves",
            "takeRamp" to "Brauciet uz uzbrauktuvi",
            "exitLabelled" to "Nobrauciet pa nobrauktuvi {label}",
            "exitPlain" to "Nobrauciet",
            "forkLeft" to "Sazarojumā turieties pa kreisi",
            "forkRight" to "Sazarojumā turieties pa labi",
            "endLeft" to "Ceļa galā nogriezieties pa kreisi",
            "endRight" to "Ceļa galā nogriezieties pa labi",
            "roundabout" to "Aplī izvēlieties {n}. nobrauktuvi",
            "rotary" to "Aplī izvēlieties {n}. nobrauktuvi",
        ),
        "ga" to mapOf(
            "on" to " ar ",
            "depart" to "Tosaigh",
            "arrive" to "Tá tú tagtha ag do cheann scríbe",
            "turnLeft" to "Cas ar chlé",
            "turnRight" to "Cas ar dheis",
            "keepLeft" to "Fan ar chlé",
            "keepRight" to "Fan ar dheis",
            "sharpLeft" to "Cas go géar ar chlé",
            "sharpRight" to "Cas go géar ar dheis",
            "uturn" to "Déan casadh U",
            "continueStraight" to "Lean ar aghaidh díreach",
            "continueOn" to "Lean ar aghaidh",
            "merge" to "Cumaisc",
            "rampLeft" to "Cas ar chlé ar an rampa",
            "rampRight" to "Cas ar dheis ar an rampa",
            "takeRamp" to "Tóg an rampa",
            "exitLabelled" to "Tóg slí amach {label}",
            "exitPlain" to "Tóg an tslí amach",
            "forkLeft" to "Ag an ngabhal fan ar chlé",
            "forkRight" to "Ag an ngabhal fan ar dheis",
            "endLeft" to "Ag deireadh an bhóthair cas ar chlé",
            "endRight" to "Ag deireadh an bhóthair cas ar dheis",
            "roundabout" to "Ag an timpeallán tóg an {n}ú slí amach",
            "rotary" to "Ag an timpeallán tóg an {n}ú slí amach",
        ),
        "mt" to mapOf(
            "on" to " fi ",
            "depart" to "Ibda",
            "arrive" to "Wasalt fid-destinazzjoni tiegħek",
            "turnLeft" to "Dur xellug",
            "turnRight" to "Dur lemin",
            "keepLeft" to "Żomm ix-xellug",
            "keepRight" to "Żomm il-lemin",
            "sharpLeft" to "Dur bil-qawwi xellug",
            "sharpRight" to "Dur bil-qawwi lemin",
            "uturn" to "Agħmel U-turn",
            "continueStraight" to "Kompli dritt",
            "continueOn" to "Kompli",
            "merge" to "Ingħaqad",
            "rampLeft" to "Dur xellug għar-rampa",
            "rampRight" to "Dur lemin għar-rampa",
            "takeRamp" to "Ħu r-rampa",
            "exitLabelled" to "Oħroġ mill-ħruġ {label}",
            "exitPlain" to "Oħroġ",
            "forkLeft" to "Fil-furkettun żomm ix-xellug",
            "forkRight" to "Fil-furkettun żomm il-lemin",
            "endLeft" to "Fl-aħħar tat-triq dur xellug",
            "endRight" to "Fl-aħħar tat-triq dur lemin",
            "roundabout" to "Fir-rawndabawt ħu l-{n} ħruġ",
            "rotary" to "Fir-rawndabawt ħu l-{n} ħruġ",
        ),
    )

    fun phrase(languageCode: String, key: String): String =
        values[languageCode]?.get(key) ?:
            values.getValue("en")[key].orEmpty()
}
